```{r}
requiredPackageList<-c("tseries","ggplot2","scales","gridExtra","knitr","lubridate","reshape2","forecast")
colnames(installed.packages())
notInstalledPackages<-requiredPackageList[!(requiredPackageList %in% installed.packages()[,"Package"])] #apply logical vector to requiredPackageList
if(length(notInstalledPackages)!=0){print(notInstalledPackages);install.packages(notInstalledPackages)}
lapply(requiredPackageList,require,character.only=T)
#Reference 
#http://stackoverflow.com/questions/4090169/elegant-way-to-check-for-missing-packages-and-install-them
#http://stackoverflow.com/questions/8175912/load-multiple-packages-at-once
username<-Sys.info()['user']
pathOutput<-paste("C:/Users/",username,"/Desktop/charts/",sep="")
SD<-Sys.Date()
windowsFonts(Meiryo=windowsFont("Meiryo"))
```

```{r}
ssn<-list()
url<-c(
  "http://solarscience.msfc.nasa.gov/greenwch/spot_num.txt",
  "http://solarscience.msfc.nasa.gov/greenwch/sunspot_area.txt",
  "http://solarscience.msfc.nasa.gov/greenwch/sunspot_area_north.txt",
  "http://solarscience.msfc.nasa.gov/greenwch/sunspot_area_south.txt"
)
chartTitle<-c(
  "太陽黒点数(SSN)と標準偏差(DEV)",
  "黒点総面積(単位:millionths of a hemisphere)",
  "北半球黒点総面積(単位:millionths of a hemisphere)",
  "南半球黒点総面積(単位:millionths of a hemisphere)"
)  
for(iii in 1:length(url)){
  ssn[[iii]]<-read.table(url[[iii]],header=T,skip=0,as.is=T,stringsAsFactor=FALSE)
  print(head(ssn[[iii]]))
  if(grepl("_num",url[[iii]])==T){
    ssn[[iii]]$date<-as.Date(paste(ssn[[iii]]$YEAR,"/",ssn[[iii]]$MON,"/1",sep=""))
    ssn[[iii]]<-ssn[[iii]][,c(5,3,4)]
  }
  else{
    ssn[[iii]]$date<-as.Date(paste(ssn[[iii]]$Year,"/",ssn[[iii]]$Mon,"/1",sep=""))
    if(grepl("_north",url[[iii]])==T){
      colnames(ssn[[iii]])[3]<-paste(colnames(ssn[[iii]])[3],".north",sep="")
    }else if(grepl("_south",url[[iii]])==T){
      colnames(ssn[[iii]])[3]<-paste(colnames(ssn[[iii]])[3],".south",sep="")
    }  
    else{
      colnames(ssn[[iii]])[3]<-paste(colnames(ssn[[iii]])[3],".total",sep="")
    }
    ssn[[iii]]<-ssn[[iii]][,c(4,3)]
  }
  if(iii==1){
    ssn[[(length(url)+1)]]<-ssn[[iii]]
  }else{
    ssn[[(length(url)+1)]]<-merge(ssn[[(length(url)+1)]],ssn[[iii]],by="date")
  }
}
```

```{r}
tailLength<-120
menulength<-10
orderColumn<-0
orderDirection<-"desc" #asc desc
dateFormat<-3 #1:as is , 2:scientific , 3:monthly , 4:dayly , 5:yearly
columnWidth<-"{\"width\":\"10%\",\"targets\":0}"
switch(dateFormat,
  dateFormatType<-"",
  dateFormatType<-"",
  dateFormatType<-"%Y/%m",
  dateFormatType<-"%Y/%m/%d",
  dateFormatType<-"%Y"
)  
```

```{r}
#only html
setwd(pathOutput)
col<-list()
ST<-Sys.time()  
addVer<-gsub("\\.","",paste(year(SD),month(SD),day(SD),hour(ST),minute(ST),second(ST),sep=""))
htmlFile<-paste(addVer,".html",sep="")
cat("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js\"></script>",file=htmlFile,append=F)
cat("<link href=\"http://code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css\" rel=\"stylesheet\">",file=htmlFile,append=T)
cat("<link href=\"http://cdn.datatables.net/plug-ins/f2c75b7247b/integration/jqueryui/dataTables.jqueryui.css\" rel=\"stylesheet\">",file=htmlFile,append=T) 
cat("<script src=\"http://cdn.datatables.net/1.10.5/js/jquery.dataTables.min.js\"></script>",file=htmlFile,append=T) 
cat("<script src=\"http://cdn.datatables.net/plug-ins/f2c75b7247b/integration/jqueryui/dataTables.jqueryui.js\"></script>",file=htmlFile,append=T)
for(rrr in 1:length(ssn)){
  grandData<-NULL
  header<-NULL
  tableID<-paste("am-consulting",rrr,addVer,sep="")
  dataset<-tail(ssn[[rrr]],tailLength)
  if(rrr!=5){
    cat(chartTitle[[rrr]],"\n",file=htmlFile,append=T) 
  }else{
    cat("総合\n",file=htmlFile,append=T) 
  }  
  cat("<script type=\"text/javascript\" charset=\"utf-8\">$(document).ready( function(){",file=htmlFile,append=T)
  cat(paste("$('#",tableID,"').dataTable( {",sep=""),file=htmlFile,append=T)
  cat("\"lengthMenu\": [[",menulength,",-1,100,200], [",menulength,",\"All\",100,200]],",file=htmlFile,append=T)
  cat(paste("\"order\": [[ ",orderColumn,", \"",orderDirection,"\" ]],",sep=""),file=htmlFile,append=T)
  cat("\"searching\": true,",file=htmlFile,append=T)
  cat("\"columnDefs\":[",columnWidth,"],",file=htmlFile,append=T)
  cat("\"language\": {\"decimal\": \".\",\"thousands\": \",\"}",file=htmlFile,append=T)
  cat("});",file=htmlFile,append=T)
  cat("});</script>",file=htmlFile,append=T)
  for(ccc in 1:ncol(dataset)){
    if(ccc==1){
      switch(dateFormat,
      col[[ccc]]<-paste("<td align=\"right\" valign=\"middle\">",dataset[,ccc],"</td>",sep=""),
      col[[ccc]]<-paste("<td align=\"right\" valign=\"middle\">",format(dataset[,ccc],big.mark=",",scientific=F),"</td>",sep=""),
      col[[ccc]]<-paste("<td align=\"right\" valign=\"middle\">",format(as.Date(dataset[,ccc]),dateFormatType),"</td>",sep=""),
      col[[ccc]]<-paste("<td align=\"right\" valign=\"middle\">",format(as.Date(dataset[,ccc]),dateFormatType),"</td>",sep=""),
      col[[ccc]]<-paste("<td align=\"right\" valign=\"middle\">",format(as.Date(dataset[,ccc]),dateFormatType),"</td>",sep="")
      )
    }else{  
      col[[ccc]]<-paste("<td align=\"right\" valign=\"middle\">",format(dataset[,ccc],big.mark=",",scientific=F),"</td>",sep="")
    }  
    grandData<-cbind(grandData,col[[ccc]])
    header<-paste(header,"<th>",colnames(dataset)[ccc],"</th>",sep="")  
  }
  tableHtml<-paste("<table cellpadding=\"0\" cellspacing=\"0\" id=\"",tableID,"\" width=\"100%\" class=\"display\"><thead>",sep="")
  tableHtml<-paste(tableHtml,header,"</thead>",sep="")
  cat(tableHtml,file=htmlFile,append=T)
  grandData<-data.frame("<tr>",grandData,"</tr>",row.names=NULL)
  write.table(grandData,htmlFile,quote=F,col.names=F, append=T,row.names=F)
  cat("</table>",file=htmlFile,append=T)
  cat("<hr>",file=htmlFile,append=T)
}  
cat("Powered by DataTables( http://datatables.net/ )<br>",file=htmlFile,append=T)
```

```{r}
setwd(pathOutput)
subTitle<-"\n※1000(millionths of Hemisphere)は約3,000(million square kilometres)"
datasourceURL<-"\nData Source http://solarscience.msfc.nasa.gov/"
lineColor<-c("blue","red")
for(ppp in 1:3){
  for(iii in 1:(length(url))){
    mainTitle<-chartTitle[iii]
    tmp<-ssn[[iii]]
    if(ppp==3){tmp<-tail(tmp,240)}
    date.s<-format(tmp[,1][1],"%Y/%m")
    date.e<-format(tmp[,1][nrow(tmp)],"%Y/%m")
    if(ppp==1 | ppp==3){
      g<-ggplot()
      if(iii==1){
        ssnTS<-melt(tmp,id="date") 
        g<-g+geom_line(data=ssnTS,aes(x=date,y=value,colour=variable),alpha=0.7,size=0.5)
        g<-g+scale_colour_manual("時系列データ",values=lineColor)
        g<-g+geom_point(data=tmp,aes(x=tmp[,1],y=tmp[,3]),colour=lineColor[2],size=2)
        if(ppp==3){
          g<-g+geom_smooth(data=tmp,aes(x=tmp[,1],y=tmp[,2]),method=loess,color=lineColor[1],size=2,linetype="dashed")
          g<-g+geom_smooth(data=tmp,aes(x=tmp[,1],y=tmp[,3]),method=loess,color=lineColor[2],size=2,linetype="dashed")
        }  
      }else{
        g<-g+geom_line(data=tmp,aes(x=tmp[,1],y=tmp[,2]),colour=lineColor[1],alpha=0.7,size=0.5)
        if(ppp==3){
          g<-g+geom_smooth(data=tmp,aes(x=tmp[,1],y=tmp[,2]),method=loess,color=lineColor[1],size=2,linetype="dashed")
        }  
      }  
      g<-g+geom_point(data=tmp,aes(x=tmp[,1],y=tmp[,2]),colour=lineColor[1],size=2)
      g<-g+scale_x_date(labels=date_format("%Y/%m"))
      plot.title<-"時系列チャート-"
    }else{
      g<-ggplot(data=tmp,aes(x=tmp[,2]))
      if(iii==1){
        bw<-10  
      }else{
        bw<-100
      }  
      g<-g+geom_histogram(binwidth=bw,fill="blue",alpha=0.4,color="black")
      plot.title<-"ヒストグラム-"
      if(iii==1){mainTitle<-"太陽黒点数(SSN)"}
    }
    g<-g+ggtitle(paste(plot.title,mainTitle,"\n期間:",date.s,"-",date.e,subTitle,datasourceURL,sep=""))
    g<-g+theme(axis.text=element_text(size=32,family="Meiryo"))
    g<-g+theme(axis.title=element_text(size=32,face="plain",family="Meiryo"))
    g<-g+theme(title=element_text(size=32,face="plain",family="Meiryo"))
    g<-g+theme(legend.position="top")
    g<-g+theme(legend.text=element_text(colour="black",size=32,face="plain",family="Meiryo"))
    g<-g+theme(legend.title=element_text(colour="black",size=32,face="plain",family="Meiryo"))
    g<-g+xlab("")+ylab("")
    ST<-Sys.time()  
    addVer<-gsub("\\.","",paste(year(SD),month(SD),day(SD),hour(ST),minute(ST),second(ST),sep=""))
    png.file<-paste(addVer,".png",sep="")
    png(file=png.file,width=1600,height=800)
    print(g)
    dev.off()
  }
}
```

```{r}
setwd(pathOutput)
for(ppp in 1:(length(url))){
  mainTitle<-chartTitle[ppp]
  if(ppp==1){mainTitle<-"太陽黒点数(SSN)"}
  tmp<-na.omit(ssn[[ppp]])
  date.s<-format(tmp[,1][1],"%Y/%m")
  date.e<-format(tmp[,1][nrow(tmp)],"%Y/%m")
  ST<-Sys.time()  
  addVer<-gsub("\\.","",paste(year(SD),month(SD),day(SD),hour(ST),minute(ST),second(ST),sep=""))
  png.file<-paste(addVer,".png",sep="")
  png(file=png.file,width=1600,height=800)
  par(cex.main=3,cex.axis=3,cex.lab=3,cex.sub=4,mar=c(8,8,14,2))
  SolarData<-tmp[,2]
  MainTitle<-paste("自己相関関数-",mainTitle,"\n期間:",date.s,"-",date.e,"\n原系列の単位根検定(H1:stationary) p値=",adf.test(SolarData,k=1)$p.value,datasourceURL)
  result<-acf(tmp[,2],type="correlation",main=MainTitle,lag=1200,ci=c(0.9,0.95),family="Meiryo")
  dev.off()
  resultDataframe<-data.frame(lag=result$lag,acf=result$acf)
  rrr<-order(resultDataframe[,2],decreasing=F)
  tmp<-resultDataframe[rrr,]
  tmp[,1]<-ordered(tmp[,1],levels=tmp[,1][1:length(tmp[,1])])
  tmp<-tail(tmp,30)
  g<-ggplot()
  g<-g+geom_bar(data=tmp,aes(x=tmp[,1],y=tmp[,2]),stat="identity",position="identity",fill="blue",alpha=0.2,color="black")
  g<-g+coord_flip()
  g<-g+ylab("自己相関係数")+xlab("ラグ(ヶ月)")
  g<-g+ggtitle(MainTitle)
  g<-g+theme(axis.text=element_text(size=30,family="Meiryo"))   
  g<-g+theme(axis.title=element_text(colour="black",size=30,face="plain",family="Meiryo"))   
  g<-g+theme(title=element_text(size=30,face="plain",family="Meiryo"))   
  g<-g+theme(legend.position="bottom")   
  g<-g+theme(legend.text=element_text(colour="black",size=40,face="plain",family="Meiryo"))   
  g<-g+theme(legend.title=element_text(colour="white",size=20,face="plain",family="Meiryo"))
  g<-g+geom_text(data=tmp,aes(x=tmp[,1],y=tmp[,2],label=tmp[,2]),vjust=0.5,hjust=2,size=5,face="bold",family="Meiryo")
  ST<-Sys.time()  
  addVer<-gsub("\\.","",paste(year(SD),month(SD),day(SD),hour(ST),minute(ST),second(ST),sep=""))
  png.file<-paste(addVer,".png",sep="")
  png(file=png.file,width=1600,height=800)
  print(g)
  dev.off()
}
```