```{r}
windowsFonts(Meiryo=windowsFont("Meiryo"))
options(scipen=9999)
library(RCurl)
script <-
  getURL(
    "https://raw.githubusercontent.com/am-consulting/Rscript/master/importCFTC.r",
    ssl.verifypeer = FALSE
  )
eval(parse(text = script))

for(iii in 1:length(dataset)){
  cat(iii,dataset[[iii]][1,5],'\n')  
  dataset[[iii]]$Col<-ifelse(0<=dataset[[iii]][,4],'blue','red')
}
```

```{r}
username<-Sys.info()['user']
pathOutput<-paste("C:/Users/",username,"/Desktop/charts/",sep="")
setwd(pathOutput)

for(iii in c(1,2,4)){
  csvTitle <- substr(currency[iii],1,regexpr(" -",currency[iii])[1])
  csvFile <- gsub(" ","",paste("IMMポジション.",csvTitle,".csv",sep=""))    
  write.csv(dataset[[iii]],csvFile,row.names=F,append=F,quote=F,fileEncoding="UTF-8")
  for(ccc in c(2,3,4)){
    ST <- Sys.time()  
    pngFile <- paste(
      'am-consulting.co.jp-',
      colnames(dataset[[iii]])[ccc],
      ".png",
      sep=""
    )
    png(file = pngFile , width = 1920 , height = 1080)
    par(mar = c(5, 6, 7, 3), family = 'Meiryo')
    if(ccc!=4){
      barcolor<-'black'  
    }else{
      barcolor<-dataset[[iii]]$Col  
    }
    plot(
      dataset[[iii]][,1],
      dataset[[iii]][,ccc],
      type = 'h',
      main = paste(colnames(dataset[[iii]])[ccc],'\n',dataset[[iii]][1,1],'~',dataset[[iii]][nrow(dataset[[iii]]),1]),
      col = barcolor,
      ylab = dataset[[iii]][1,6],
      xlab = '',
      panel.first = grid(
        nx = NULL,
        ny = NULL,
        lty = 2,
        equilogs = T,
        lwd = 2
      ),
      xaxt = "n",
      cex.axis = 2.5,
      cex.main = 4.0,
      cex.lab = 2.5,
      cex.sub =2.0
    )
    axis.Date(
      side = 1,
      at = dataset[[iii]][,1],
      format = "%Y-%m-%d",
      padj = 1,
      cex.axis = 2.5
    )
    dev.off()
  }
}
```