```{r}
library(lubridate)
library(eeptools)
username<-Sys.info()['user']
SD<-Sys.Date()
needRightRow<-1
addRightRow<-2
needCalStat<-0 #日銀オペレーション用
typeData<-0 #0 非時系列 1 時系列
nonNumeric<-c(1,2)
needsparkline<-0
needRegular<-0
youtubechannel<-1
```

```{r}
#月例経済報告
needRightRow<-0
addRightRow<-1
needCalStat<-0 #日銀オペレーション用
typeData<-1 #0 非時系列 1 時系列
nonNumeric<-c(1,2,3)
needsparkline<-1
needRegular<-1
youtubechannel<-0
#月例経済報告
```

```{r}
#毎月勤労統計調査
needRightRow<-1
addRightRow<-1
needCalStat<-0 #日銀オペレーション用
typeData<-0 #0 非時系列 1 時系列
nonNumeric<-c(1,2,3,4)
needsparkline<-0
needRegular<-0
youtubechannel<-0
#毎月勤労統計調査
```

```{r}
mainTitle<-"電力調査統計 発電設備利用率(一般電気事業者,%)"
mainTitle<-"日本の人口推計 平成27年8月概算値(万人,%)"
mainTitle<-"出入国管理統計(人)"
mainTitle<-"住民基本台帳人口移動報告 2015年7月(外国人を含む移動者、人)"
mainTitle<-"『日本経済の変貌と量的･質的金融緩和』の抽出語出現回数表"
mainTitle<-"被保護者調査-生活保護の被保護世帯数及び実人員(2015年6月分概数)"
mainTitle<-"被保護者調査-生活保護の種類別にみた扶助人員(2015年6月分概数)"
mainTitle<-"日本銀行オペレーション<br>(国債買入,国庫短期証券買入･売却,社債等買入,CP等買入,指数連動型上場投資信託受益権買入,不動産投資法人投資口買入オペレーション)"
mainTitle<-"日本の学校基本調査 卒業後の状況調査(平成27年3月卒業) 大学院の専攻別"
mainTitle<-"日経平均株価"
mainTitle<-"都道府県別建設工事受注高前年同月比"
mainTitle<-"都道府県別法人税(法人所得金額)"
mainTitle<-"都道府県別合計特殊出生率"
mainTitle<-"2015年 訪日外客数(人)"
mainTitle<-"都道府県別交通事故発生状況 2015年8月中(件数、%)"
mainTitle<-"平成27年都道府県地価調査"
mainTitle<-"新規学卒者の産業別職業紹介状況の推移 高卒者"
mainTitle<-"戸籍統計"
mainTitle<-"民間給与実態統計調査結果-1年勤続者の業種別平均給与(千円)"
mainTitle<-"継続等区分別集落営農数"
mainTitle<-"都道府県別預金・現金・貸出金（8月、%、兆円）"
mainTitle<-"被保護者調査 都道府県統計表 2015年7月分"
mainTitle<-"日本の対中国ODA実績と両国のGDPの推移 1979年から2013年(単位:ODA 億ドル,実質GDP 10億ドル)"
mainTitle<-"体力･運動能力調査 平成26年度 年齢別体格測定の結果"
mainTitle<-"日本の鉱工業生産指数 業種別 前月比 2015年8月分(%)"
mainTitle<-"Crude Oil - Closing stocks(kbbl)"
mainTitle<-"日本の建設総合統計 出来高(億円)"
mainTitle<-"ミシガン大学消費者信頼感指数"
mainTitle<-"国・地域別犯罪率 2013年(10万人当たり) "
mainTitle<-"出入国管理統計-外国人入国者数-2015年9月"
mainTitle<-"平成26年度被保護者調査 - 被保護人員数"
mainTitle<-"日本の都道府県別有効求人倍率"
mainTitle<-"平成27年度　9月末租税及び印紙収入、収入額調(百万円、%)"
mainTitle<-"各国成人喫煙率(WHO:Tobacco Atlas(2002))"
mainTitle<-"各国肺がん死亡率(Age-standardised rates per 100 000 population / 10万人あたりの年齢調整死亡率)"
mainTitle<-"月例経済報告と政権・マネタリーベース・日経平均株価・完全失業率"
mainTitle<-"平成26年(2014)人口動態統計(確定数)の概況"
mainTitle<-"毎月勤労統計 毎勤原表 2015年11月"
dataSource<-"\nデータ出所:Federal Reserve Bank of St. Louis"
dataSource<-"\nデータ出所:株式会社東京商工リサーチ"
dataSource<-"\nデータ出所:The U.S. Census Bureau"
dataSource<-"\nデータ出所:内閣府"
dataSource<-"\nデータ出所:資源エネルギー庁"
dataSource<-"\nデータ出所:株式会社東京証券取引所"
dataSource<-"\nデータ出所:日本政府観光局"
dataSource<-"\nデータ出所:警察庁"
dataSource<-"\nデータ出所:国土交通省"
dataSource<-"\nデータ出所:国税庁"
dataSource<-"\nデータ出所:農林水産省"
dataSource<-"\nデータ出所:日本銀行"
dataSource<-"\nデータ出所:外務省,IMF"
dataSource<-"\nデータ出所:文部科学省"
dataSource<-"\nデータ出所:経済産業省"
dataSource<-"\nデータ出所:Joint Organisations Data Initiative"
dataSource<-"\nデータ出所:国土交通省"
dataSource<-"\nデータ出所:The Regents of the University of Michigan"
dataSource<-"\nデータ出所:United Nations Office on Drugs and Crime(国連薬物・犯罪事務所)"
dataSource<-"\nデータ出所:法務省"
dataSource<-"\nデータ出所:財務省"
dataSource<-"\nデータ出所:公益財団法人 健康・体力づくり事業財団"
dataSource<-"\nデータ出所:OECD iLibrary"
dataSource<-"\nデータ出所:内閣府、日本銀行、株式会社日本経済新聞社、総務省"
dataSource<-"\nデータ出所:厚生労働省"
dataset<-read.table("clipboard",header=TRUE,sep="\t",stringsAsFactor=F,na.strings=c("-","－"," ---- ","…"),check.names=FALSE)
#comma削除
tmp<-apply(dataset[,-nonNumeric,drop=F],2,decomma)
dataset<-cbind(dataset[,nonNumeric,drop=F],tmp)
#comma削除
if(needRightRow==1){
  dataset<-cbind(dataset,dataset[,addRightRow])
  colnames(dataset)[ncol(dataset)]<-colnames(dataset)[addRightRow]
} 
dataset[is.na(dataset)==T]<--9999
#dateType
if(typeData==1){
if(length(unique(day(dataset[,1])))==1 & length(unique(month(dataset[,1])))==1){dataset[,1]<-format(as.Date(dataset[,1]),"%Y")}else
if(length(unique(day(dataset[,1])))==1 & length(unique(month(dataset[,1])))!=1){dataset[,1]<-format(as.Date(dataset[,1]),"%Y/%m")}
}
#dateType
print(head(dataset),3)
print(tail(dataset),3)
```

```{r}
if(needRightRow==1){nonNumeric<-c(nonNumeric,addRightRow)}
tablefontsize<-90 #%
cnt<-1
sumColumn<-2
menulength<-"[[20,-1], [20,\"All\"]]"
orderColumn<-0
orderDirection<-"asc" #asc desc
columnWidth<-"{\"width\":\"10%\",\"targets\":0}"
pathOutput<-paste("C:/Users/",username,"/Desktop/R_Data_Write/",sep="")
setwd(pathOutput)
#sparkline
sparklineWidth<-180
sparklineHeight<-50
sparklineType<-"line"
#sparkline
```

```{r}
if(length(grep("毎月勤労統計 毎勤原表",mainTitle))!=0){
htmlFile<-"am-consultingMonthlyLabourSurveyTable.html"
orderColumn<-4
}else if(length(grep("月例経済報告と政権・マネタリーベース・日経平均株価・完全失業率",mainTitle))!=0){
htmlFile<-"am-consultingMonthlyEconomicReport7117.html"
}else{  
htmlFile<-"am-consultingTable.html"
}
cat("",file=htmlFile,append=F)
```

```{r}
#only html
htmldataset<-dataset
cat("<div style=\"text-align:center\"><b>",mainTitle,"</b></div><br>",file=htmlFile,append=T)
col<-list()
grandData<-NULL
header<-NULL
ST<-Sys.time()  
addVer<-gsub("\\.","",paste(year(SD),month(SD),day(SD),hour(ST),minute(ST),second(ST),sep=""))
tableID<-paste("am-consulting",addVer,sep="")
cat("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js\"></script>\n",file=htmlFile,append=T)
cat("<link href=\"http://cdn.datatables.net/1.10.8/css/jquery.dataTables.min.css\" rel=\"stylesheet\">\n",file=htmlFile,append=T)  
cat("<script src=\"http://cdn.datatables.net/1.10.8/js/jquery.dataTables.min.js\"></script>\n\n",file=htmlFile,append=T) 
cat("<script src=\"http://archive.am-consulting.co.jp/jquery.sparkline.2.1.2.js\"></script>\n",file=htmlFile,append=T)
cat("<style>\n",file=htmlFile,append=T)
cat(paste("table{width:100%;border-collapse:collapse;padding:0;border-spacing:1;margin-left: auto;margin-right: auto;font-size:",tablefontsize,"%;}\n",sep=""),file=htmlFile,append=T)
cat("tr, td, th{white-space: nowrap;}\n",file=htmlFile,append=T)
cat("td.highlight {font-weight: plain;color: red;}\n",file=htmlFile,append=T) 
cat("</style>\n",file=htmlFile,append=T)
cat("<script type=\"text/javascript\" charset=\"utf-8\">\n",file=htmlFile,append=T)
cat("$(document).ready( function(){\n",file=htmlFile,append=T)
cat(paste("$('#",tableID,"').dataTable( {\n",sep=""),file=htmlFile,append=T)
cat("\"lengthMenu\":",menulength,"\n",file=htmlFile,append=T)
cat(",\n",file=htmlFile,append=T)
cat(paste("\"order\": [[ ",orderColumn,", \"",orderDirection,"\" ]]\n",sep=""),file=htmlFile,append=T)
cat(",\n",file=htmlFile,append=T)
cat("\"searching\": true\n",file=htmlFile,append=T)
cat(",\n",file=htmlFile,append=T)
cat("\"columnDefs\":[",columnWidth,"]\n",file=htmlFile,append=T)
cat(",\n",file=htmlFile,append=T)
cat("\"language\": {\"decimal\": \".\",\"thousands\": \",\"}\n",file=htmlFile,append=T)
cat(",\n",file=htmlFile,append=T)
#Individual column searching part  
cat("initComplete: function () {\n",file=htmlFile,append=T)
cat("this.api().columns().every( function () {\n",file=htmlFile,append=T)
cat("var column = this;\n",file=htmlFile,append=T)
cat("var select = $('<select><option value=\"\"></option></select>')\n",file=htmlFile,append=T)
cat(".appendTo( $(column.footer()).empty() )\n",file=htmlFile,append=T)
cat(".on( 'change', function () {\n",file=htmlFile,append=T)
cat("var val = $.fn.dataTable.util.escapeRegex(\n",file=htmlFile,append=T)
cat("$(this).val()\n",file=htmlFile,append=T)
cat(");\n",file=htmlFile,append=T)
cat("column\n",file=htmlFile,append=T)
cat(".search( val ? '^'+val+'$' : '', true, false )\n",file=htmlFile,append=T)
cat(".draw();\n",file=htmlFile,append=T)
cat("} );\n",file=htmlFile,append=T)
cat("column.data().unique().sort().each( function ( d, j ) {\n",file=htmlFile,append=T)
cat("select.append( '<option value=\"'+d+'\">'+d+'</option>' )\n",file=htmlFile,append=T)
cat("} );\n",file=htmlFile,append=T)
cat("} );\n",file=htmlFile,append=T)
cat("}\n",file=htmlFile,append=T)
#Individual column searching part  
cat(",\n",file=htmlFile,append=T)
#Row created callback  
cat("createdRow: function ( row, data, index ) {\n",file=htmlFile,append=T)
for(ccc in 1:ncol(dataset)){
  cat(paste("if ( data[",ccc-1,"].replace(',' , '') * 1 < 0 ) {\n",sep=""),file=htmlFile,append=T)
  cat(paste("$('td', row).eq(",ccc-1,").addClass('highlight');\n",sep=""),file=htmlFile,append=T)
  cat("}\n",file=htmlFile,append=T)
}
cat("}\n",file=htmlFile,append=T)  
#Row created callback  
cat("});\n",file=htmlFile,append=T)
#calStat part-datatables  
if(needCalStat==1){
cat(paste("$('#",tableID,"')\n",sep=""),file=htmlFile,append=T)
cat(paste(".on( 'column-sizing.dt', function () {calStat",cnt,"()} )\n",sep=""),file=htmlFile,append=T)
cat(paste(".on( 'column-visibility.dt', function () {calStat",cnt,"()} )\n",sep=""),file=htmlFile,append=T)
cat(paste(".on( 'destroy.dt', function () {calStat",cnt,"()} )\n",sep=""),file=htmlFile,append=T)
cat(paste(".on( 'draw.dt', function () {calStat",cnt,"()} )\n",sep=""),file=htmlFile,append=T)
cat(paste(".on( 'init.dt', function () {calStat",cnt,"()} )\n",sep=""),file=htmlFile,append=T)
cat(paste(".on( 'length.dt', function () {calStat",cnt,"()} )\n",sep=""),file=htmlFile,append=T)
cat(paste(".on( 'order.dt', function () {calStat",cnt,"()} )\n",sep=""),file=htmlFile,append=T)
cat(paste(".on( 'page.dt', function () {calStat",cnt,"()} )\n",sep=""),file=htmlFile,append=T)
cat(paste(".on( 'pre.dt', function () {calStat",cnt,"()} )\n",sep=""),file=htmlFile,append=T)
cat(paste(".on( 'preXhr.dt', function () {calStat",cnt,"()} )\n",sep=""),file=htmlFile,append=T)
cat(paste(".on( 'processing.dt', function () {calStat",cnt,"()} )\n",sep=""),file=htmlFile,append=T)
cat(paste(".on( 'search.dt', function () {calStat",cnt,"()} )\n",sep=""),file=htmlFile,append=T)
cat(paste(".on( 'stateLoaded.dt', function () {calStat",cnt,"()} )\n",sep=""),file=htmlFile,append=T)
cat(paste(".on( 'stateLoadParams.dt', function () {calStat",cnt,"()} )\n",sep=""),file=htmlFile,append=T)
cat(paste(".on( 'stateSaveParams.dt', function () {calStat",cnt,"()} )\n",sep=""),file=htmlFile,append=T)
cat(paste(".on( 'xhr.dt', function () {calStat",cnt,"()} )\n",sep=""),file=htmlFile,append=T)
cat(".dataTable();\n",file=htmlFile,append=T)
}
#calStat part-datatables  
#正規表現
if(needRegular==1){
#javascript
cat(paste("$('#",tableID,"').dataTable();",sep=""),file=htmlFile,append=T)
cat("$('input.global_filter').on( 'keyup click', function () {",file=htmlFile,append=T)
cat("filterGlobal();",file=htmlFile,append=T)
cat("} );",file=htmlFile,append=T)
cat("$('input.column_filter').on( 'keyup click', function () {",file=htmlFile,append=T)
cat("filterColumn( $(this).parents('tr').attr('data-column') );",file=htmlFile,append=T)
cat("} );  ",file=htmlFile,append=T)
#javascript
}
#正規表現
cat("});</script>\n\n\n\n\n",file=htmlFile,append=T)
#calStat part-javascript  
if(needCalStat==1){
cat(paste("<script>window.onload = function(){calStat",cnt,"()};</script>\n",sep=""),file=htmlFile,append=T)
cat("<script>\n",file=htmlFile,append=T)
cat(paste("function calStat",cnt,"(){\n",sep=""),file=htmlFile,append=T)
cat(paste("var sum01 = 0 , count01 = 0 , variance01 = 0, countPlus01 = 0;\n",sep=""),file=htmlFile,append=T)
cat(paste("var sum02 = 0 , count02 = 0 , variance02 = 0, countPlus02 = 0;\n",sep=""),file=htmlFile,append=T)
cat(paste("all = $('#",tableID," > tbody > tr');\n",sep=""),file=htmlFile,append=T)
#対象列
cat("all.each(function() {\n",file=htmlFile,append=T)
cat(paste("sum01 += +$('td:eq(",sumColumn,")', this).text();\n",sep=""),file=htmlFile,append=T)
cat("count01++;\n",file=htmlFile,append=T)
cat("});\n",file=htmlFile,append=T)
cat("mean01 = sum01 / count01;\n",file=htmlFile,append=T)
cat("all.each(function() {\n",file=htmlFile,append=T)
cat(paste("tmp = $('td:eq(",sumColumn,")', this).text()-mean01;\n",sep=""),file=htmlFile,append=T)
cat("variance01 = variance01 + tmp*tmp;\n",file=htmlFile,append=T)
cat(paste("if( 0<= $('td:eq(",sumColumn,")', this).text() ){countPlus01++}\n",sep=""),file=htmlFile,append=T)
cat("});\n",file=htmlFile,append=T)
cat("variance01 = variance01 / count01;\n",file=htmlFile,append=T)
cat("deviation01 = Math.pow(variance01,0.5);\n",file=htmlFile,append=T)
cat(paste("document.form1",cnt,".sum01.value",sep=""),"= sum01.toFixed(2);\n",file=htmlFile,append=T)
cat(paste("document.form1",cnt,".mean01.value",sep=""),"= mean01.toFixed(2);\n",file=htmlFile,append=T)
#cat(paste("document.form1",cnt,".variance01.value",sep=""),"= variance01.toFixed(2);\n",file=htmlFile,append=T)
#cat(paste("document.form1",cnt,".deviation01.value",sep=""),"= deviation01.toFixed(2);\n",file=htmlFile,append=T)
cat(paste("document.form1",cnt,".countPlus01.value",sep=""),"= countPlus01;\n",file=htmlFile,append=T)
cat("}\n",file=htmlFile,append=T)
cat("</script>\n",file=htmlFile,append=T)
#calStat part-javascript  
#calStat part-html  
cat(paste("<form name=\"form1",cnt,"\">\n",sep=""),file=htmlFile,append=T)
cat("<table width=\"90%\"><tbody>\n",file=htmlFile,append=T)
cat("<tr>\n",file=htmlFile,append=T)
cat(paste("<td style=\"text-align:center\" colspan=\"6\"><b>テーブル表示範囲の基本統計量 - ",colnames(htmldataset)[sumColumn+1],"</b></td>\n"),file=htmlFile,append=T)
cat("</tr>\n",file=htmlFile,append=T)
cat("<tr>\n",file=htmlFile,append=T)
cat("<td style=\"width:15%;text-align:right\" bgcolor=\"#F5F5F5\">平均値</td>\n",file=htmlFile,append=T)
cat("<td style=\"width:15%;\"><input type=\"number\" style=\"ime-mode:disabled;text-align:right\" name=\"mean01\" size=\"10\"></td>\n",file=htmlFile,append=T)
cat("<td style=\"width:15%;text-align:right\" bgcolor=\"#F5F5F5\">回数</td>\n",file=htmlFile,append=T)
cat("<td style=\"width:15%;\"><input type=\"number\" style=\"ime-mode:disabled;text-align:right\" name=\"countPlus01\" size=\"10\"></td>\n",file=htmlFile,append=T)
cat("<td style=\"width:15%;text-align:right\" bgcolor=\"#F5F5F5\">合計</td>\n",file=htmlFile,append=T)
cat("<td style=\"width:15%;\"><input type=\"number\" style=\"ime-mode:disabled;text-align:right\" name=\"sum01\" size=\"10\"></td>\n",file=htmlFile,append=T)
cat("</tr>\n",file=htmlFile,append=T)
cat("</tbody></table>\n",file=htmlFile,append=T)
cat("</form>\n",file=htmlFile,append=T)
#Reference http://stackoverflow.com/questions/12212567/jquery-calculate-average-of-column-values-and-put-it-in-each-td-of-another-co  
#calStat part-html
}
#正規表現パート
if(needRegular==1){
#html
cat("<b>正規表現対応フィルターボックス</b>",file=htmlFile,append=T)  
cat("\n<table width=\"100%\"><thead><tr><th width=\"15%\" style=\"text-align:center\">Target</th><th width=\"75%\" style=\"text-align:center\">Search text</th><th style=\"text-align:center\">Regex</th></tr></thead><tbody>\n",file=htmlFile,append=T)
for(rccc in 1:ncol(htmldataset)){
cat(paste("<tr id=\"filter_col",rccc,"\" data-column=\"",rccc-1,"\">\n",sep=""),file=htmlFile,append=T)
cat(paste("<td>",colnames(htmldataset)[rccc],"</td>",sep=""),file=htmlFile,append=T)
cat(paste("<td align=\"center\"><input type=\"text\" class=\"column_filter\" id=\"col",rccc-1,"_filter\"  style=\"width:100%\"></td>\n",sep=""),file=htmlFile,append=T)
cat(paste("<td align=\"center\"><input type=\"checkbox\" class=\"column_filter\" id=\"col",rccc-1,"_regex\" checked=\"checked\"></td>\n",sep=""),file=htmlFile,append=T)
#cat(paste("<td align=\"center\"><input type=\"checkbox\" class=\"column_filter\" id=\"col",rccc-1,"_smart\" checked=\"checked\"></td>\n",sep=""),file=htmlFile,append=T)
cat("</tr>\n",file=htmlFile,append=T)
}  
cat("\n</tbody></table>",file=htmlFile,append=T)  
#html
#javascript
cat("<script>\n",file=htmlFile,append=T)  
cat("function filterGlobal () {\n",file=htmlFile,append=T) 
cat(paste("$('#",tableID,"').DataTable().search(\n",sep=""),file=htmlFile,append=T) 
cat("$('#global_filter').val(),\n",file=htmlFile,append=T) 
cat("$('#global_regex').prop('checked'),\n",file=htmlFile,append=T) 
cat("$('#global_smart').prop('checked')\n",file=htmlFile,append=T) 
cat(").draw();\n",file=htmlFile,append=T) 
cat("}\n",file=htmlFile,append=T) 
cat("function filterColumn ( i ) {\n",file=htmlFile,append=T)
cat(paste("$('#",tableID,"').DataTable().column( i ).search(\n",sep=""),file=htmlFile,append=T)
cat("$('#col'+i+'_filter').val(),\n",file=htmlFile,append=T)
cat("$('#col'+i+'_regex').prop('checked'),\n",file=htmlFile,append=T)
cat("$('#col'+i+'_smart').prop('checked')\n",file=htmlFile,append=T)
cat(").draw();\n",file=htmlFile,append=T)
cat("}\n",file=htmlFile,append=T)
cat("</script>\n",file=htmlFile,append=T)  
#javascript
}  
#正規表現パート
cat(dataSource,"<br>",file=htmlFile,append=T)
#cat("- 最新データは\"数表リスト\"( http://equations.am-consulting.co.jp/?page_id=2074 )から確認ください<br>",file=htmlFile,append=T)
cat("- -9999は「データなし」または「データ欠損」または「NA」を意味します<br>",file=htmlFile,append=T)
for(ccc in 1:ncol(htmldataset)){
  if(needCalStat!=1){
  tmpCheck<-(nonNumeric==ccc)  
  tmpCheck<-length(tmpCheck[tmpCheck==TRUE])  
  if(tmpCheck==0){  
  col[[ccc]]<-paste("<td align=\"right\" valign=\"middle\">",format(htmldataset[,ccc],big.mark=",",scientific=F),"</td>",sep="")
  }else{
  col[[ccc]]<-paste("<td align=\"right\" valign=\"middle\">",htmldataset[,ccc],"</td>",sep="")
  }  
  }else{
  col[[ccc]]<-paste("<td align=\"right\" valign=\"middle\">",htmldataset[,ccc],"</td>",sep="")
  }  
  grandData<-cbind(grandData,col[[ccc]])
  header<-paste(header,"<th>",colnames(htmldataset)[ccc],"</th>",sep="")  
}
#sparkline
sparkLineHeader<-""
if(needsparkline==1){
cat("<script type=\"text/javascript\">$(function(){\n\n",file=htmlFile,append=T)
for(ccc in 1:(ncol(htmldataset))){
tmpCheck<-(nonNumeric==ccc)  
tmpCheck<-length(tmpCheck[tmpCheck==TRUE])  
if(tmpCheck==0){    
#tmp<-paste(htmldataset[,ccc],collapse=",") 
tmp<-paste(htmldataset[,ccc][-9999!=htmldataset[,ccc]],collapse=",")
cat(paste("$(\"#amccsparkline",ccc,"\").sparkline([",tmp,"], {\n",sep=""),file=htmlFile,append=T)
cat(paste("type: '",sparklineType,"',\n",sep=""),file=htmlFile,append=T)
cat(paste("width: '",sparklineWidth,"',\n",sep=""),file=htmlFile,append=T)
cat(paste("height: '",sparklineHeight,"'\n",sep=""),file=htmlFile,append=T)
cat("});\n\n",file=htmlFile,append=T)
}
}  
cat("});</script>\n\n",file=htmlFile,append=T)
for(ccc in 1:(ncol(htmldataset))){
tmpCheck<-(nonNumeric==ccc)  
tmpCheck<-length(tmpCheck[tmpCheck==TRUE])  
if(tmpCheck==0){    
sparkLineHeader<-paste(sparkLineHeader,"<th><div id=\"amccsparkline",ccc,"\"></div></th>",sep="")
}else{  
sparkLineHeader<-paste(sparkLineHeader,"<th>",colnames(htmldataset)[ccc],"</th>",sep="")
}  
}
sparkLineHeader<-paste("<tr>",sparkLineHeader,"</tr>",sep="")
}
#sparkline
tableHtml<-paste("<table cellpadding=\"0\" cellspacing=\"0\" id=\"",tableID,"\" width=\"100%\" class=\"display compact\"><thead>",sep="")
tableHtml<-paste(tableHtml,sparkLineHeader,header,"</thead><tfoot>",sep="")
tableHtml<-paste(tableHtml,header,"</tfoot>",sep="")
cat("<div style=\"overflow-x:scroll;\">\n",file=htmlFile,append=T)
cat(tableHtml,file=htmlFile,append=T)
grandData<-data.frame("<tr>",grandData,"</tr>",row.names=NULL)
write.table(grandData,htmlFile,quote=F,col.names=F, append=T,row.names=F)
cat("</table>",file=htmlFile,append=T)
cat("</div>\n",file=htmlFile,append=T)
cat("Powered by<br>-DataTables( http://datatables.net/ )<br>-jQuery( https://jquery.com )",file=htmlFile,append=T)  
if(needsparkline==1){
cat("<br>-jQuery Sparklines( http://omnipotent.net/jquery.sparkline/#s-about )",file=htmlFile,append=T)  
}  
#youtubegallery
if(youtubechannel==1){
cat("<style>.youtube_channel.ytc_wall_1-6 .ytc_video_container {padding: 5px;box-sizing: border-box;font-size: 15px;}</style>",file=htmlFile,append=T)
cat("<hr>",file=htmlFile,append=T)
cat("[youtube_channel class=ytc_wall_1-6 channel=UC56EoMsVlhV-OpB7Ua4KJ1Q playlist=PLu2t-yT4OTt-iS_cv9NAOUaWQ3SKZzWJA resource=2 cache=300 num=6 random=0 ratio=3 responsive=0 width=140 display=thumbnail]",file=htmlFile,append=T)
}
#youtubegallery
#only html
```