```{r}
library(RCurl)
fileName <- 'functionList.csv'
functionList <-
  read.csv(
    file = paste0('https://raw.githubusercontent.com/am-consulting/am-consulting.github.io/master/csv/',
                  fileName),
    header = F,
    as.is = T)
for(iii in 1:nrow(functionList)){
  script <- 
    getURL(paste0("https://raw.githubusercontent.com/am-consulting/am-consulting.github.io/master/", functionList[iii,1]),
    ssl.verifypeer = F
  )
  eval(parse(text = script))
}
```

```{r}
library(grid);library(gridExtra);library(XLConnect);library(quantmod);library(forecast)
options(scipen = 999)
windowsFonts(Meiryo = windowsFont("Meiryo"))
username <- Sys.info()['user']
pathOutput <-
  paste("C:/Users/", username, "/Desktop/R_Data_Write/", sep = "")
setwd(pathOutput)
fileName <- 'psw09.xls'
```

```{r}
if(!file.exists(paste0(pathOutput, fileName))) {
download.file(paste0('http://ir.eia.gov/wpsr/', fileName), fileName , mode = "wb")
}
```

```{r}
# tmp0 <- getSymbols('DCOILWTICO', src = 'FRED', auto.assign = F)
# tmp <-
#   data.frame(
#     Date = as.Date(index(tmp0)),
#     tmp0[, 1],
#     check.names = F,
#     row.names = NULL
#   )
# colnames(tmp)[2] <- 'Crude Oil Prices: West Texas Intermediate (WTI) - Cushing, Oklahoma(Dollars per Barrel)'
# wtiOil <- tmp
```

```{r}
targetSheet <- c(2:22)
dateFormat <- '%Y-%m-%d'
for (sss in 1:length(targetSheet)) {
  buf <-
    readWorksheetFromFile(
      paste0(pathOutput, fileName),
      sheet = targetSheet[sss]   ,
      check.names = F,
      header = F
    )
  colnames(buf) <-  unlist(buf[3,])
  buf <- buf[-c(1:3),]
  if (sss == 1) {
    EIAData <- buf
  } else{
    EIAData <- merge(EIAData, buf, by = 'Date', all = T)
  }
}
EIAData[, 1] <- as.Date(EIAData[, 1])
EIAData <- EIAData[order(EIAData[, 1]),]
EIAData <-
  data.frame(EIAData[, 1, drop = F], apply(EIAData[, -1], 2, as.numeric), check.names = F)
obj <- c(
  'Weekly U.S. Ending Stocks excluding SPR of Crude Oil  ',
  'Weekly Cushing, OK Ending Stocks excluding SPR of Crude Oil  ',
  'Weekly U.S. Ending Stocks of Total Gasoline  ',
  'Weekly U.S. Ending Stocks of Distillate Fuel Oil  ',
  'Weekly U.S. Ending Stocks of Propane and Propylene  ',
  'Weekly U.S. Refiner Net Input of Crude Oil  ',
  'Weekly U.S. Percent Utilization of Refinery Operable Capacity ',
  'Weekly U.S. Imports of Crude Oil  ',
  'Weekly U.S. Imports of Total Gasoline  '
)
JapaneseTitle <- c(
  '戦略石油備蓄を除いた週間米国原油在庫量(1000バレル)',
  '戦略石油備蓄を除いたオクラホマ州クッシングの週間米国原油在庫量(1000バレル)',
  '週間米国ガソリン在庫量(1000バレル)',
  '週間米国留出油在庫量(1000バレル)',
  '週間米国プロパンおよびプロピレン在庫量(1000バレル)',
  '週間米国製油所原油処理量(1000バレル/日)',
  '週間米国製油所稼働率(%)',
  '週間米国原油輸入量(1000バレル/日)',
  '週間米国ガソリン輸入量(1000バレル/日)'
)
```

```{r}
imageWidth <- 1920; imageHeight <- 1080
htmlFile <- paste0(Sys.Date(),'-amcc_EIA.md')
durationYear <- 10
cat('', file = htmlFile, append = F)
cat('<style>table{width:100%}</style>', file = htmlFile, append = T)
for (ooo in 1:length(obj)) {
  ccc <- grep(obj[ooo] , colnames(EIAData))
  tmp <- EIAData[, c(1, ccc)]
  tmp0 <- data.frame(tmp[-1, ], round(diff(tmp[, 2]), 10), check.names = F)
  colnames(tmp0)[3] <- '前週差' # 'Changes from last week'
  if(length(grep('percent', obj[ooo], ignore.case = T)) == 0){
    tmp0 <- data.frame(tmp0, round(diff(tmp[, 2])/head(tmp[,2],-1)*100,1), check.names = F)
    colnames(tmp0)[4] <- '前週比(%)' # 'Changes from last week(%)'
  }
  dataSet <- na.omit(tail(tmp0, ceiling(365 * durationYear / 7 )))
  # wtiOil0 <- na.omit(subset(wtiOil, first(dataSet[, 1]) <= wtiOil[, 1] & wtiOil[, 1] <= last(dataSet[, 1])))
  # dataSet <- merge(dataSet,wtiOil0,by='Date',all = T)
  cat('\n***\n', file = htmlFile, append = T)
  cat('<b>',paste0(colnames(dataSet)[2], '</b><br>'), file = htmlFile, append = T)
  cat('<b>',paste0(JapaneseTitle[ooo], '</b>\n\n'), file = htmlFile, append = T)
  dataSet0 <- na.omit(dataSet)
  colnames(dataSet0)[2] <- '結果'
  bufTable0 <- tail(dataSet0, 30)
  bufTable0$No <- seq(nrow(bufTable0))
  cat(paste0(knitr::kable(bufTable0,row.names = F), '\n'), file = htmlFile, append = T)
  bufTable0 <- tail(dataSet0, 10)
  bufTable0$No <- seq(nrow(bufTable0))
  png.file <- paste0('EIA', ooo, ".png")
  png(file = png.file, width = imageWidth, height = imageHeight)
  fun_plotTimeSeries(obj = dataSet,
                     chartType = 0, objX = 1, objYL = 2, typeL = 'l',
                     dataTitle = JapaneseTitle[ooo],
                     dataSource = 'U.S. Energy Information Administration (EIA)',
                     cex.axis = 2.5, cex.main = 2.5, cex.lab = 2.0, 
                     mar = c(6, 6, 13, 4), needLefLab = 0,
                     lwdL = 2, fitLcolor = 2)
  amccTheme <- 
    gridExtra::ttheme_minimal(
      core = list(fg_params = list(hjust=1, cex = 3.0, x = 1, fontfamily = 'Meiryo')),
      colhead = list(fg_params = list(hjust=1, cex = 3.0, x = 1, fontfamily = 'Meiryo')),
      rowhead = list(fg_params = list(hjust=1, cex = 3.0, x = 1, fontfamily = 'Meiryo')))
  # https://stat.ethz.ch/R-manual/R-devel/library/grid/html/gpar.html
  pushViewport(viewport(x = .2, y = .65))
  grid.table(cbind(summary(na.omit(dataSet[,2]))), theme = amccTheme)
  pushViewport(viewport(x = .8, y = .4))
  grid.table(bufTable0, theme = amccTheme, rows = NULL)
  abline(h = summary(na.omit(dataSet[,2]))[2], col = 'lightcoral')
  text(x = head(dataSet[,1],1) ,y = summary(na.omit(dataSet[,2]))[2],labels = '1st Qu.', pos = 4, cex = 3)
  abline(h = summary(na.omit(dataSet[,2]))[5], col = 'lightcoral')
  text(x = head(dataSet[,1],1) ,y = summary(na.omit(dataSet[,2]))[5],labels = '3rd Qu.', pos = 4, cex = 3)
  dev.off()
  png.file <- paste0('EIA', ooo, "-ACF.png")
  png(file = png.file, width = imageWidth, height = imageHeight)
  par(family = 'Meiryo', mar =c(7,7,12,4))
  acfResult0 <-
    na.omit(dataSet)
  acfResult <-
    acf(acfResult0[,2],
        plot = T,
        lag.max = 52 * 3,
        col = 'blue',
        main = NA,
        lwd = 2,
        panel.first = grid(nx = NULL,
                           ny = NULL,
                           lty = 2,
                           equilogs = T),
        cex.axis = 2.5, cex.lab = 2.0)
  mtext(text = paste0('自己相関係数\n',
                      colnames(acfResult0)[2],
                      '\n',
                      JapaneseTitle[ooo],
                      '\n',
                      paste0(range(acfResult0[,1]),collapse = '~')), 
        side = 3,
        cex = 2.5,
        line = 1)
  acfResult <-
    data.frame(acfResult$lag, acfResult$acf)
  colnames(acfResult) <- 
    c('Lag','ACF')
  # plot, chart 内にデーブルを表示
  # 参照 ftp://cran.r-project.org/pub/R/web/packages/gridExtra/vignettes/tableGrob.html
  dev.off()
  # arfima part 自己回帰実数和分移動平均モデル
  png.file <- paste0('EIA', ooo, "-ARFIMA.png")
  png(file = png.file, width = imageWidth, height = imageHeight)
  h <- 8
  result_arfima <-
    arfima(
      y = dataSet[,2],
      drange = c(0,1),
      estim = 'mle',
      lambda = NULL)
  ciLevel <- c(0.99, 0.95, 0.9, 0.8)
  forecastResult <- 
    forecast(result_arfima, level = ciLevel, h = h, plot = F)
  par(family = 'Meiryo', mfrow = c(1,2), mar = c(3,4,3,3), oma = c(6,3,9,3))
  plot(forecastResult,
       panel.first = grid(nx = NULL, ny = NULL, lty = 2, equilogs = T),
       xaxt = 'n',
       yaxt = 'n',
       font.axis = 1,
       font.main = 1,
       font.lab = 1,
       font.sub = 1,
       cex.main = 2.5)
  axis(side = 2, cex.axis = 2)
  text(x = 1, 
       y = forecastResult$x[1],
       labels = dataSet[1,1],
       pos = 4,
       font = 1,
       cex = 2.0)
  lines(x = 1, 
        y = forecastResult$x[1],
        pch = 20,
        type = 'p',
        cex = 1.5,
        col = 'red')
  text(x = length(dataSet[,2]), 
       y = forecastResult$x[length(dataSet[,2])],
       labels = dataSet[length(dataSet[,2]),1],
       pos = 2,
       font = 1,
       cex = 2.0)
  lines(x = length(dataSet[,2]), 
        y = forecastResult$x[length(dataSet[,2])],
        pch = 20,
        type = 'p',
        cex = 1.5,
        col = 'red')
  ylim <- 
    c(min(forecastResult$lower), max(forecastResult$upper))
  xlim <- 
    c(length(forecastResult$x) + 1, length(forecastResult$x) + h)
  plot(forecastResult,
       xlim = xlim,
       ylim = ylim,
       xaxt = 'n',
       yaxt = 'n',
       main = paste0('After This Week:C.I = ',paste0(ciLevel,collapse = ',')),
       font.axis = 1,
       font.main = 1,
       font.lab = 1,
       font.sub = 1,
       cex.main = 2.5, cex.lab = 2.0)
  panel.first = grid(nx = NULL,ny = NULL,lty = 2,equilogs = T)
  axis(side = 1, 
       at = seq(xlim[1],xlim[2]), 
       labels = c('1st week','2nd week','3rd week','4th week','5th week','6th week','7th week','8th week'),
       cex.axis = 2.0)
  axis(side = 2, cex.axis = 2.0)
  adfResult <- 
    adf.test(dataSet[,2])
  mtext(side = 3, 
        line = 1, 
        outer = T, 
        text = paste0(JapaneseTitle[ooo],'\n',
                      colnames(dataSet)[2],
                      '\nADF Test:Lag order=',
                      adfResult$parameter,
                      ',p value=',
                      round(adfResult$p.value,3),
                      ',Alternative=',
                      adfResult$alternative), 
        cex = 2.5,
        font = 1)
  mtext(side = 1, 
        line = 1, 
        outer = T, 
        text = 'Financial transactions and future forecasts based on the data of this video are absolutely prohibited.', 
        cex = 2.5,
        font = 3)
  dev.off()
  # arfima part
  # historical volatility part
  png.file <- paste0('EIA', ooo, "-HV.png")
  png(file = png.file, width = imageWidth, height = imageHeight)
  width <- 30
  fun_historicalVolatility(obj = dataSet,objColumn = 2,width = width)
  fun_plotTimeSeries(obj = historicalVolatility,
                     chartType = 0,
                     lwdL = 2,
                     fitLcolor = 2,
                     cex.axis = 2.5, cex.main = 2.5, cex.lab = 2.0,mar = c(6, 6, 13, 4),
                     dataSource = 'EIA',dataTitle = paste0(JapaneseTitle[ooo],'. Width:',width,'weeks'))
  dev.off()
  # historical volatility part
}
```
