```{r}
requiredPackageList<-c(
  "base64enc",
  "classInt",
  "devtools",
  "fields",
  "forecast",
#  "ggplot2",
#  "gridExtra",
  "HH",
  "lubridate",
  "maps",
  "maptools",
  "plotrix",
  "png",
  "quantmod",
  "raster",
  "RColorBrewer",
  "Rcpp",
  "reshape",
  "rworldmap",
  "scales",
  "tseries",
  "viridis",
  "XLConnect",
  "ggrepel", #Error: package ‘ggplot2’ 1.0.0 is loaded, but >= 2.0.0 is required by ‘ggrepel’
  "proto", #ggplot2のインストールに必須
  "knitr",
  "PerformanceAnalytics",
  "eeptools",
  "Imap",
  "geosphere",
  "rgl",
  "scatterplot3d",
  "gtrendsR",
  "RCurl",
  "dplyr", #Pipe Operator %>% dataset<-tmp%>%filter(nikkei225 < 20000, usdjpy > 100)
  #http://www.r-statistics.com/2014/08/simpler-r-coding-with-pipes-the-present-and-future-of-the-magrittr-package/
  "XML",
  "viridis",
  #要求されたパッケージ viridis をロード中です 
  #Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  #名前空間 ‘ggplot2’ 1.0.0 は既にロードされましたが、>= 1.0.1 が要求されています 
  "installr",
  "compare",
  "roxygen2",
  "testthat",
  "beepr"
)
colnames(installed.packages())
notInstalledPackages<-requiredPackageList[!(requiredPackageList %in% installed.packages()[,"Package"])] #apply logical vector to requiredPackageList
notInstalledPackages
if(length(notInstalledPackages)!=0){print(notInstalledPackages);install.packages(notInstalledPackages)}
#Reference 
#http://stackoverflow.com/questions/4090169/elegant-way-to-check-for-missing-packages-and-install-them
#http://stackoverflow.com/questions/8175912/load-multiple-packages-at-once
```

```{r}
packageurl <- "http://cran.r-project.org/src/contrib/Archive/ggplot2/ggplot2_1.0.0.tar.gz"
packageurl <- "http://cran.r-project.org/src/contrib/Archive/ggplot2/ggplot2_1.0.1.tar.gz"
install.packages(packageurl, repos=NULL, type="source")
packageurl <- "http://cran.r-project.org/src/contrib/Archive/gridExtra/gridExtra_0.9.1.tar.gz"
install.packages(packageurl, repos=NULL, type="source")
packageurl <- "http://cran.r-project.org/src/contrib/Archive/seasonal/seasonal_0.80.0.tar.gz"
install.packages(packageurl, repos=NULL, type="source")
```

```{r}
username<-Sys.info()['user']
Sys.setenv(X13_PATH=paste("C:\\Users\\",username,"\\Downloads\\x13asall_V1.1_B19\\x13as",sep=""))
```

```{r}
devtools::install_github("PMassicotte/gtrendsR")
devtools::install_github("lionel-/gghorizon")
devtools::install_github("animalito/rformat")
devtools::install_github("am-consulting/performanceAsLeader")
#devtools::install_github("christophsax/seasonal")
devtools::install_github("ellisp/ggseas/pkg")
devtools::install_github("rstudio/addinexamples", type = "source")
devtools::install_github("rich-iannone/DiagrammeR")
```

```{r}
#https://cran.r-project.org/web/packages/gpclib/index.html
fileName<-"gpclib_1.5-5.tar.gz"
URL<-paste("https://cran.r-project.org/src/contrib/",fileName,sep="")
username<-Sys.info()['user']
path<-paste("C:/Users/",username,"/Desktop/packageForR/",sep="")
setwd(path)
download.file(url=URL,destfile=fileName,mode="wb")
install.packages(paste(path,fileName,sep=""),repos=NULL,type="source")
# > gpclibPermit()
# [1] TRUE
# Warning message:
# In gpclibPermit() :
#   support for gpclib will be withdrawn from maptools at the next major release
#> packageVersion("maptools")
#[1] ‘0.8.37’
#https://cran.r-project.org/src/contrib/maptools_0.8-39.tar.gz
```

```{r}
#https://cran.r-project.org/web/packages/x13binary/index.html
fileName<-"x13binary_0.1.0.tar.gz"
URL<-paste("https://cran.r-project.org/src/contrib/",fileName,sep="")
username<-Sys.info()['user']
path<-paste("C:/Users/",username,"/Desktop/packageForR/",sep="")
setwd(path)
download.file(url=URL,destfile=fileName,mode="wb")
install.packages(paste(path,fileName,sep=""),repos=NULL,type="source")
```