```{r}
library(lubridate)
username<-Sys.info()['user']
pathOutput<-paste("C:/Users/",username,"/Desktop/charts/",sep="")
SD<-Sys.Date()
windowsFonts(Meiryo=windowsFont("Meiryo"))
fun.readData<-function(){
  dataset<-read.table("clipboard",header=TRUE,sep="\t",stringsAsFactor=F)
  print(head(dataset))
  print(tail(dataset))
  dataset<<-dataset # caution
}
funPreTitle<-function(){
  preTitle<-colnames(buf)[2]
  preTitle<-gsub("\\.\\.","\\.",preTitle)
  preTitle<-gsub("前年同月比","前年同月比(%)",preTitle)
  preTitle<-gsub("割合","割合(%)",preTitle)
  preTitle<-gsub("break","\n",preTitle)
  preTitle<-gsub("パーセント","%",preTitle)
  preTitle<<-preTitle
}
```

```{r}
fun.readData()#dataset<-dataset[order(dataset[,2],decreasing=T),]
if(colnames(dataset)[1]=="Date"){
  dataset[,1]<-as.Date(dataset[,1])
}else{
  dataset[,1]<-ordered(dataset[,1],levels=dataset[,1][1:length(dataset[,1])]) #1列目が日付でない場合、強制的にオーダー化する
}
monthly<-2
```

```{r}
commonTitle<-"株式平均利回り:"
dataSource<-"\nデータ出所:株式会社日本取引所グループ"
plotType<-1 #1:line , 2:bar
if(length(unique(day(dataset[,1])))==1){#月次データの日付は14日または15日に変更
  if(unique(day(dataset[,1]))==1){
    dataset[,1]<-as.Date(paste(year(dataset[,1]),"-",month(dataset[,1]),"-",floor(days_in_month(dataset[,1])/2),sep=""))
    monthly<-1
  }
}
switch(monthly,
  dateFormatType<-"%Y/%m",
  dateFormatType<-"%Y/%m/%d",
  dateFormatType<-"%Y"
)
```

```{r}
labelValue<-0
data<-list()
periodResult<-list()
setwd(pathOutput)
cols<-c("red","green","blue")
ltys<-c(1,1,1)
labels<-c("1989年4月消費税導入前後4年間","1997年4月消費税増税前後4年間","2014年4月消費税増税前後4年間")
changePoint<-as.Date(c("1989/4/1","1997/4/1","2014/4/1"))
interval<-24
for(ccc in 2:ncol(dataset)){
  ylimMin<-10^10
  ylimMax<-(-1)*10^10
  result<-NULL
  buf<-dataset[,c(1,ccc)]
  funPreTitle()
  mainTitle<-paste("消費税導入･増税前後の時系列推移\n",commonTitle,preTitle,dataSource)
  ST<-Sys.time()  
  addVer<-gsub("\\.","",paste(year(SD),month(SD),day(SD),hour(ST),minute(ST),second(ST),sep=""))
  png.file<-paste(addVer,".png",sep="")
  png(file=png.file,width=1920,height=1080)
  par(ps=20,mar=c(5,10,10,3),cex.main=1.5,cex.lab=1,cex.axis=1.5,family="Meiryo") 
  tmp<-buf
  for(mmm in 1:length(changePoint)){
    data[[mmm]]<-subset(tmp,(changePoint[mmm]-months(interval))<=tmp[,1] & tmp[,1]<=(changePoint[mmm]+months(interval)))
    ylimMin<-min(ylimMin,min(data[[mmm]][,2]))
    ylimMax<-max(ylimMax,max(data[[mmm]][,2]))
  }
  ylimMax<-(ylimMax-ylimMin)/5+ylimMax
  plot(0,0,type="n",xlim=c(-interval,interval),ylim=c(ylimMin,ylimMax+(ylimMax-ylimMin)/5),xlab="",ylab="",main=mainTitle,las=1)
  for(mmm in 1:length(changePoint)){
    start<-nrow(subset(data[[mmm]],data[[mmm]][,1]<changePoint[mmm]))
    end<-nrow(subset(data[[mmm]],data[[mmm]][,1]>changePoint[mmm]))
    data[[mmm]]$monthID<-rep(-start:end,length=nrow(data[[mmm]]))
    points(data[[mmm]][,3],data[[mmm]][,2],col=cols[mmm])
    lines(data[[mmm]][,3],data[[mmm]][,2],type="l",col=cols[mmm])
    text(head(data[[mmm]][,3],1),head(data[[mmm]][,2],1),labels=format(head(data[[mmm]][,1],1),dateFormatType),srt=0,cex=1.2,adj=c(0,0),col="black",family="Meiryo")
    text(0,data[[mmm]][25,2],labels=format(data[[mmm]][25,1],dateFormatType),srt=0,cex=1.2,adj=c(0,0),col="black",family="Meiryo")
    text(tail(data[[mmm]][,3],1),tail(data[[mmm]][,2],1),labels=format(tail(data[[mmm]][,1],1),dateFormatType),srt=0,cex=1.2,adj=c(1,0),col="black",family="Meiryo")
    if(labelValue==1){
      text(data[[mmm]][,3],data[[mmm]][,2],labels=paste(data[[mmm]][,2],sep=""),srt=90,cex=1.5,adj=0,col=cols[mmm],family="Meiryo")
    }
    resultBefore<-lm(head(data[[mmm]][,2],start)~head(data[[mmm]][,3],start))
    x0<--start
    y0<-resultBefore$coe[1]+resultBefore$coe[2]*x0
    x1<--1
    y1<-resultBefore$coe[1]+resultBefore$coe[2]*x1
    segments(x0,y0,x1,y1,col=cols[mmm],lty="dashed",lwd=3) 
    resultAfter<-lm(tail(data[[mmm]][,2],end)~tail(data[[mmm]][,3],end))
    x0<-0
    y0<-resultAfter$coe[1]+resultAfter$coe[2]*x1
    x1<-end
    y1<-resultAfter$coe[1]+resultAfter$coe[2]*x1
    segments(x0,y0,x1,y1,col=cols[mmm],lty="dashed",lwd=3)
    #before 増税月は含まず
    beforeData<-head(data[[mmm]][,2],start)
    result01<-format(mean(beforeData),digits=3)
    result02<-median(beforeData)  
    result03<-max(beforeData)  
    result04<-min(beforeData)
    result05<-format(var(beforeData),digits=3)
    result11<-head(beforeData,1)
    result12<-tail(beforeData,1)
    #after
    afterData<-tail(data[[mmm]][,2],end)
    result06<-format(mean(afterData),digits=3)
    result07<-median(afterData)  
    result08<-max(afterData)  
    result09<-min(afterData)
    result10<-format(var(afterData),digits=3)
    result21<-head(afterData,1)
    result22<-tail(afterData,1)
    periodResult[[mmm]]<-paste(
      "\n増税前-平均:",result01,",中央値:",result02,"最大値:",result03,"最小値:",result04,",不偏分散:",result05,",開始:",result11,",終了:",result12,
      "\n増税後-平均:",result06,",中央値:",result07,"最大値:",result08,"最小値:",result09,",不偏分散:",result10,",開始:",result21,",終了:",result22,
      sep="")
    result<-c(result,periodResult[[mmm]])
  }
  outputlabels<-paste(labels,result)
  legend("topleft",legend=outputlabels,col=cols,lty=ltys,inset=0,cex=1.2,bty="n",x.intersp=0,y.intersp=3,lwd=3)
  dev.off()
}
```

```{r}
labelValue<-0
data<-list()
setwd(pathOutput)
labels<-c("民主党政権:2009/9/16-2012/12/25\n","自民党政権:2012/12/26-\n")
changePoint<-as.Date(c("2009/9/16","2012/12/26"))
cols<-c("red","blue")
ltys<-c(1,1)
for(ccc in 2:ncol(dataset)){
  buf<-dataset[,c(1,ccc)]
  funPreTitle()
  mainTitle<-paste("民主党政権と自民党政権(第二次安倍政権以降)の比較\n",commonTitle,preTitle,dataSource)
  dpj<-subset(buf,changePoint[1]<=buf[,1] & buf[,1]<changePoint[2])
  ldp<-subset(buf,changePoint[2]<=buf[,1])
  data[[1]]<-dpj
  data[[2]]<-ldp
  xlimEnd<-max(nrow(data[[1]]),nrow(data[[2]]))
  ST<-Sys.time()  
  addVer<-gsub("\\.","",paste(year(SD),month(SD),day(SD),hour(ST),minute(ST),second(ST),sep=""))
  png.file<-paste(addVer,".png",sep="")
  png(file=png.file,width=1920,height=1080)
  par(ps=20,mar=c(5,10,10,3),cex.main=1.5,cex.lab=1,cex.axis=1.5,family="Meiryo")  
  ylimMin<-min(subset(buf,changePoint[1]<=buf[,1])[,2])
  ylimMax<-max(subset(buf,changePoint[1]<=buf[,1])[,2])
  ylimMax<-ylimMax+(ylimMax-ylimMin)/5
  plot(0,0,type="n",xlim=c(1,xlimEnd),ylim=c(ylimMin,ylimMax+(ylimMax-ylimMin)/5),xlab="",ylab="",main=mainTitle,las=1)
  for(mmm in 1:length(data)){
    tmp<-data.frame(id=c(1:nrow(data[[mmm]])),data[[mmm]])
    points(tmp[,1],tmp[,3],col=cols[mmm])
    lines(tmp[,1],tmp[,3],type="l",col=cols[mmm])
    if(labelValue==1){
      text(tmp[,1],tmp[,3],labels=tmp[,3],srt=0,cex=1.5,adj=c(0.5,-0.5),col=cols[mmm],family="Meiryo")
    }
    text(tmp[1,1],tmp[1,3],labels=format(tmp[1,2],dateFormatType),srt=0,cex=1.2,adj=c(0,0),col="black",family="Meiryo")
    text(tmp[nrow(tmp),1],tmp[nrow(tmp),3],labels=format(tmp[nrow(tmp),2],dateFormatType),srt=0,cex=1.2,adj=c(1,0),col="black",family="Meiryo")
    abline(lm(tmp[,3]~tmp[,1]),col=cols[mmm],lty="dashed",lwd=3)
  }
  dpjData<-data[[1]][,2]
  resultDPJ01<-format(mean(dpjData),digits=3)
  resultDPJ02<-median(dpjData)  
  resultDPJ03<-max(dpjData)  
  resultDPJ04<-min(dpjData)
  resultDPJ05<-format(var(dpjData),digits=3)
  resultDPJ11<-head(dpjData,1)
  resultDPJ12<-tail(dpjData,1)
  ldpData<-data[[2]][,2]
  resultLDP01<-format(mean(ldpData),digits=3)
  resultLDP02<-median(ldpData)  
  resultLDP03<-max(ldpData)  
  resultLDP04<-min(ldpData)  
  resultLDP05<-format(var(ldpData),digits=3)
  resultLDP11<-head(ldpData,1)
  resultLDP12<-tail(ldpData,1)
  resultDPJ<-paste("平均:",resultDPJ01,",中央値:",resultDPJ02,",最大値:",resultDPJ03,",最小値:",resultDPJ04,",不偏分散:",resultDPJ05,",開始:",resultDPJ11,",終了:",resultDPJ12,sep="")
  resultLDP<-paste("平均:",resultLDP01,",中央値:",resultLDP02,",最大値:",resultLDP03,",最小値:",resultLDP04,",不偏分散:",resultLDP05,",開始:",resultLDP11,",終了:",resultLDP12,sep="")
  result<-c(resultDPJ,resultLDP)
  outputlabels<-paste(labels,result,sep="")
  legend("topleft",legend=outputlabels,col=cols,lty=ltys,inset=0,cex=1.2,bty="n",x.intersp=0,y.intersp=3,lwd=3)
  dev.off()
}
```