```{r}
library(lubridate)
username<-Sys.info()['user']
pathOutput<-paste("C:/Users/",username,"/Desktop/charts/",sep="")
SD<-Sys.Date()
fun.preReadData<-function(){
  tmp<-read.table(
    "clipboard",
    header=TRUE,
    sep="\t",
    stringsAsFactor=F
  )
  tmp<<-tmp
}
fun.readData<-function(){
  dataset<-read.table(
    "clipboard",
    header=TRUE,
    sep="\t",
    stringsAsFactor=F,
    na.strings=c("-","...","X"),
    colClasses=c("character",rep(NA,ncol(tmp)-1))
  )
  colnames(dataset)<-gsub("X","",colnames(dataset))
  dataset[,2]<-gsub("\\s","",dataset[,2])
  dataset<<-dataset # caution
  print(head(dataset))
  print(tail(dataset))
}
```

```{r}
#=SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(CLEAN(E3),"　",""),"～","から")," ","")
fun.preReadData()
fun.readData()
seireiShiteiToshi<-c(
"大阪市",
"名古屋市",
"京都市",
"横浜市",
"神戸市",
"北九州市",
"札幌市",
"川崎市",
"福岡市",
"広島市",
"仙台市",
"千葉市",
"さいたま市",
"静岡市",
"堺市",
"新潟市",
"浜松市",
"岡山市",
"相模原市",
"熊本市",
"特別区部"
)
naalt<--999999
```

```{r}
allData<-NULL
noPref<-unique(substr(dataset[,1],1,2))
for(ppp in 1:length(noPref)){
  buf<-subset(dataset,substr(dataset[,1],1,2)==noPref[ppp])#各都道府県ごとのデータを抽出
  prefecture<-buf[1,2]#都道府県名を抽出  
  for(ccc in 2:nrow(buf)){#1行目は都道府県名
    tmp<-buf[ccc,2]
    if(length(tmp[tmp==seireiShiteiToshi])==1){  
      seirei<-tmp
      buf[ccc,2]<-paste(prefecture,buf[ccc,2],sep="")  
    }else if(substr(buf[ccc,1],3,3)=="1"){
      buf[ccc,2]<-paste(prefecture,seirei,buf[ccc,2],sep="")  
    }else{
      buf[ccc,2]<-paste(prefecture,buf[ccc,2],sep="")  
    }  
  }
  allData<-rbind(allData,buf)
}
allData<-data.frame(No=c(1:nrow(allData)),allData)
allData[is.na(allData)]<-naalt
colnames(allData)<-gsub("X","",colnames(allData))
colnames(allData)
```

```{r}
subtitle<-"K 安全"
menulength<-10
orderColumn<-0
orderDirection<-"asc" #asc desc
columnWidth<-"{\"width\":\"5%\",\"targets\":0}"
```

```{r}
#only html
setwd(pathOutput)
dataset<-allData
col<-list()
grandData<-NULL
header<-NULL
ST<-Sys.time()  
addVer<-gsub("\\.","",paste(year(SD),month(SD),day(SD),hour(ST),minute(ST),second(ST),sep=""))
tableID<-paste("am-consulting",addVer,sep="")
htmlFile<-paste(addVer,".html",sep="")
cat("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js\"></script>",file=htmlFile,append=F)
cat("<link href=\"http://cdn.datatables.net/1.10.7/css/jquery.dataTables.min.css\" rel=\"stylesheet\">",file=htmlFile,append=T)
cat("<script src=\"http://cdn.datatables.net/1.10.7/js/jquery.dataTables.min.js\"></script>",file=htmlFile,append=T)
#cat("<link href=\"http://code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css\" rel=\"stylesheet\">",file=htmlFile,append=T)
#cat("<link href=\"http://cdn.datatables.net/plug-ins/f2c75b7247b/integration/jqueryui/dataTables.jqueryui.css\" rel=\"stylesheet\">",file=htmlFile,append=T) 
#cat("<script src=\"http://cdn.datatables.net/1.10.5/js/jquery.dataTables.min.js\"></script>",file=htmlFile,append=T) 
#cat("<script src=\"http://cdn.datatables.net/plug-ins/f2c75b7247b/integration/jqueryui/dataTables.jqueryui.js\"></script>",file=htmlFile,append=T)  
cat("<script type=\"text/javascript\" charset=\"utf-8\">$(document).ready( function(){",file=htmlFile,append=T)
cat(paste("$('#",tableID,"').dataTable( {",sep=""),file=htmlFile,append=T)
cat("\"lengthMenu\": [[",menulength,",-1,100,200], [",menulength,",\"All\",100,200]],",file=htmlFile,append=T)
cat(paste("\"order\": [[ ",orderColumn,", \"",orderDirection,"\" ]],",sep=""),file=htmlFile,append=T)
cat("\"searching\": true,",file=htmlFile,append=T)
cat("\"columnDefs\":[",columnWidth,"],",file=htmlFile,append=T)
cat("\"language\": {\"decimal\": \".\",\"thousands\": \",\"}",file=htmlFile,append=T)
cat("});",file=htmlFile,append=T)
cat("});</script>",file=htmlFile,append=T)
#css
cat("<style type=\"text/css\">",file=htmlFile,append=T)
cat("body{",file=htmlFile,append=T)
cat("font-family:'ヒラギノ角ゴ Pro W3','Hiragino Kaku Gothic Pro','Meiryo UI','メイリオ',Verdana,'ＭＳ Ｐゴシック',sans-serif;",file=htmlFile,append=T)
cat("}",file=htmlFile,append=T)
cat(".divsrcollbar {",file=htmlFile,append=T)
cat("width:       auto;",file=htmlFile,append=T)
cat("border:      0px;",file=htmlFile,append=T)
cat("overflow-x:  scroll;",file=htmlFile,append=T)
cat("overflow-y:  hidden;",file=htmlFile,append=T)
cat("white-space: nowrap;",file=htmlFile,append=T)
cat("}",file=htmlFile,append=T)
cat("th,td{",file=htmlFile,append=T)
cat("white-space:nowrap;",file=htmlFile,append=T)
cat("}",file=htmlFile,append=T)
cat("</style>",file=htmlFile,append=T)
#css
cat("統計でみる市区町村のすがた2015(データ出所:総務省 統計局)<br>",file=htmlFile,append=T)
cat(subtitle,"<br>",file=htmlFile,append=T)
cat("(注1)表中\"",naalt,"\"はNAを表す<br>",file=htmlFile,append=T)
cat("(注2)データの年度他詳細は作成機関Webサイトを確認ください - http://www.stat.go.jp/data/ssds/<br>",file=htmlFile,append=T)
cat("<div class=\"divsrcollbar\">",file=htmlFile,append=T)
for(ccc in 1:ncol(dataset)){
  col[[ccc]]<-paste("<td align=\"right\" valign=\"middle\">",format(dataset[,ccc],big.mark=",",scientific=F),"</td>",sep="")
  grandData<-cbind(grandData,col[[ccc]])
  header<-paste(header,"<th>",colnames(dataset)[ccc],"</th>",sep="")  
}
tableHtml<-paste("<table cellpadding=\"0\" cellspacing=\"0\" id=\"",tableID,"\" class=\"display\"><thead>",sep="")
tableHtml<-paste(tableHtml,header,"</thead>",sep="")
cat(tableHtml,file=htmlFile,append=T)
grandData<-data.frame("<tr>",grandData,"</tr>",row.names=NULL)
write.table(grandData,htmlFile,quote=F,col.names=F, append=T,row.names=F)
cat("</table>",file=htmlFile,append=T)
cat("</div>",file=htmlFile,append=T)
cat("Powered by DataTables( http://datatables.net/ )",file=htmlFile,append=T)
```