```{r}
requiredPackageList<-c(
  "ggplot2","lubridate","scales","maps","maptools","RColorBrewer","fields","rworldmap",
  "classInt","plotrix","HH","reshape","gridExtra","XLConnect","eeptools"
)
colnames(installed.packages())
notInstalledPackages<-requiredPackageList[!(requiredPackageList %in% installed.packages()[,"Package"])] #apply logical vector to requiredPackageList
if(length(notInstalledPackages)!=0){print(notInstalledPackages);install.packages(notInstalledPackages)}
lapply(requiredPackageList,require,character.only=T)
#Reference 
#http://stackoverflow.com/questions/4090169/elegant-way-to-check-for-missing-packages-and-install-them
#http://stackoverflow.com/questions/8175912/load-multiple-packages-at-once
username<-Sys.info()['user']
pathOutput<-paste("C:/Users/",username,"/Desktop/R_Data_Write/",sep="")
setwd(pathOutput)
SD<-Sys.Date()
```

```{r}
#World Economic Outlook database
url<-"http://www.imf.org/external/pubs/ft/weo/2015/02/weodata/"
filename<-"WEOOct2015all.xls"
buf<-read.delim(paste(url,filename,sep=""),header=T,skip=0,stringsAsFactor=F,na.strings=c("n/a","NA"),check.names=FALSE,sep="\t")
#拡張子はxlsであるが実体はタブ区切りテキストであるため次のスクリプトは利用できない
#buf<-readWorksheetFromFile(filename,sheet=1,header=F,startCol=1,startRow=1,check.names=F)
colnames(buf)
tmp<-buf[,c(4,5,7,8,46:50)]
colnames(tmp)
#comma削除
ntmp<-apply(tmp[,5:9,drop=F],2,decomma)
tmp<-cbind(tmp[,1:4,drop=F],ntmp)
#comma削除
tmp[,c(5:9)]<-apply(tmp[,c(5:9)],2,as.numeric)
tmp[,1]<-gsub("S縊 Tom\xe9 and Pr匤cipe","São Tomé and Príncipe",tmp[,1])
tmp[,1]<-gsub("Ce d'Ivoire","Côte d'Ivoire",tmp[,1])
tmp<-tmp[tmp[,1]!="",]
tmp[is.na(tmp)==T]<--9999
tmp[tmp==""]<-"-"
dataset<-tmp
```

```{r}
#項目絞り込み
selectedData<-list()
tableItem<-unique(dataset[,2])
nItem<-4
nLoop<-ceiling(length(tableItem)/nItem)
sItem<-1  
eItem<-1*nItem
subjectHtml<-"subjectHtml.html"
cat("",file=subjectHtml,append=F)
for(ggg in 1:nLoop){
  selectItem<-na.omit(tableItem[sItem:eItem])
  selectedData[[ggg]]<-subset(dataset,dataset[,2] %in% selectItem)
  print(selectItem)
  print(unique(selectedData[[ggg]][,2]))
  print(selectItem==unique(selectedData[[ggg]][,2]))
  print(head(selectedData[[ggg]]))
  sItem<-eItem+1  
  eItem<-eItem+nItem  
  cat(paste("<b>世界経済の見通し一覧表",ggg,"</b><br>\n"),file=subjectHtml,append=T)
  cat(paste(unique(selectedData[[ggg]][,2]),col="<br>",sep=""),file=subjectHtml,append=T)
}
#項目絞り込み
#World Economic Outlook database
```

```{r}
menulength<-5
orderColumn<-0
orderDirection<-"asc" #asc desc
columnWidth<-"{\"width\":\"10%\",\"targets\":0}"
mainTitle<-"『World Economic Outlook』/『世界経済の見通し』"
dataSource<-"International Monetary Fund/国際通貨基金"
#loop
for(ggg in 1:nLoop){
#only html
htmldataset<-selectedData[[ggg]]
col<-list()
grandData<-NULL
header<-NULL
ST<-Sys.time()  
addVer<-gsub("\\.","",paste(year(SD),month(SD),day(SD),hour(ST),minute(ST),second(ST),sep=""))
tableID<-paste("am-consulting",addVer,sep="")
htmlFile<-paste("WorldEconomicOutlookdatabase",ggg,".html",sep="")
htmlFile<<-htmlFile
cat("",file=htmlFile,append=F)
#html
cat("<html>\n",file=htmlFile,append=T)
#header
cat("<head><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n",file=htmlFile,append=T)
cat("<style>\n",file=htmlFile,append=T)
cat("body{font-family:'Hiragino Kaku Gothic Pro','Meiryo UI',Verdana,sans-serif;}\n",file=htmlFile,append=T)
cat("table{width:100%;border-collapse:collapse;padding:0;border-spacing:1;margin-left: auto;margin-right: auto;white-space: nowrap;}\n",file=htmlFile,append=T)
cat("tr, td, th{}\n",file=htmlFile,append=T)
cat(".dataTables_filter input {width: 50%;}\n",file=htmlFile,append=T)
cat("td.highlight {font-weight: plain;color: red;}\n",file=htmlFile,append=T) #Row created callback
cat("</style>\n",file=htmlFile,append=T)
cat("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js\"></script>\n",file=htmlFile,append=T)
cat("<link href=\"http://archive.am-consulting.co.jp/jquery.dataTables.1.10.7.css\" rel=\"stylesheet\">\n",file=htmlFile,append=T)  
cat("<script src=\"http://cdn.datatables.net/1.10.9/js/jquery.dataTables.min.js\"></script>\n",file=htmlFile,append=T) 
cat("<script src=\"http://archive.am-consulting.co.jp/dataTables.colVis.js\"></script>\n",file=htmlFile,append=T)
cat("<link href=\"http://archive.am-consulting.co.jp/dataTables.colVis.css\" rel=\"stylesheet\">\n",file=htmlFile,append=T)
#cat("<script src=\"http://archive.am-consulting.co.jp/dataTables.fixedColumns.js\"></script>\n",file=htmlFile,append=T)
#cat("<link href=\"http://archive.am-consulting.co.jp/dataTables.fixedColumns.css\" rel=\"stylesheet\">\n",file=htmlFile,append=T)
cat("<link href=\"http://archive.am-consulting.co.jp/paceCSS.css\" rel=\"stylesheet\">",file=htmlFile,append=T)
cat("<script src=\"http://archive.am-consulting.co.jp/pace.min.js\"></script>",file=htmlFile,append=T)
cat("</head>\n",file=htmlFile,append=T)
#header
#body
cat("<body>\n",file=htmlFile,append=T)
#datatables-javascript
cat("<script type=\"text/javascript\" charset=\"utf-8\">\n$(document).ready( function(){\n",file=htmlFile,append=T)
cat(paste("var table = $('#",tableID,"').dataTable( {\n",sep=""),file=htmlFile,append=T)
cat(" \"lengthMenu\": [[",menulength,",10,20,-1,100,200], [",menulength,",10,20,\"All\",100,200]],\n",file=htmlFile,append=T)
cat(paste(" \"order\": [[ ",orderColumn,", \"",orderDirection,"\" ]],\n",sep=""),file=htmlFile,append=T)
cat(" \"searching\": true,\n",file=htmlFile,append=T)
cat(" \"columnDefs\":[",columnWidth,"],\n",file=htmlFile,append=T)
#cat(" \"scrollX\": true,\n",file=htmlFile,append=T)
#cat(" \"scrollCollapse\": true,\n",file=htmlFile,append=T)
cat(" \"language\": {\"decimal\": \".\",\"thousands\": \",\"}\n",file=htmlFile,append=T)
#Individual column searching part  
cat(" ,initComplete: function () {\n",file=htmlFile,append=T)
cat("   this.api().columns().every( function () {\n",file=htmlFile,append=T)
cat("   var column = this;\n",file=htmlFile,append=T)
cat("   var select = $('<select><option value=\"\"></option></select>')\n",file=htmlFile,append=T)
cat("   .appendTo( $(column.footer()).empty() )\n",file=htmlFile,append=T)
cat("   .on( 'change', function () {\n",file=htmlFile,append=T)
cat("   var val = $.fn.dataTable.util.escapeRegex(\n",file=htmlFile,append=T)
cat("   $(this).val()\n",file=htmlFile,append=T)
cat("   );\n",file=htmlFile,append=T)
cat("   column\n",file=htmlFile,append=T)
cat("   .search( val ? '^'+val+'$' : '', true, false )\n",file=htmlFile,append=T)
cat("   .draw();\n",file=htmlFile,append=T)
cat("   } );\n",file=htmlFile,append=T)
cat("   column.data().unique().sort().each( function ( d, j ) {\n",file=htmlFile,append=T)
cat("   select.append( '<option value=\"'+d+'\">'+d+'</option>' )\n",file=htmlFile,append=T)
cat("   } );\n",file=htmlFile,append=T)
cat("   } );\n",file=htmlFile,append=T)
cat("  }\n",file=htmlFile,append=T)
#Individual column searching part  
#Row created callback  
cat(" ,\"createdRow\": function ( row, data, index ) {\n",file=htmlFile,append=T)
for(ccc in 1:ncol(htmldataset)){
  cat(paste("   if ( data[",ccc-1,"].replace(',' , '') * 1 < 0 ) {\n",sep=""),file=htmlFile,append=T)
  cat(paste("   $('td', row).eq(",ccc-1,").addClass('highlight');\n",sep=""),file=htmlFile,append=T)
  cat("   }\n",file=htmlFile,append=T)
}
cat("  }\n",file=htmlFile,append=T)  
#Row created callback  
cat("});\n\n",file=htmlFile,append=T)
#fixed column JS
#cat("new $.fn.dataTable.FixedColumns( table, {\n",file=htmlFile,append=T)
#cat("leftColumns: 2,\n",file=htmlFile,append=T)
#cat("rightColumns: 0\n",file=htmlFile,append=T)
#cat("});\n\n",file=htmlFile,append=T)
#fixed column JS
#正規表現  
cat(paste("$('#",tableID,"').dataTable();\n",sep=""),file=htmlFile,append=T)
cat("$('input.global_filter').on( 'keyup click', function () {\n",file=htmlFile,append=T)
cat("filterGlobal();\n",file=htmlFile,append=T)
cat("} );\n",file=htmlFile,append=T)
cat("$('input.column_filter').on( 'keyup click', function () {\n",file=htmlFile,append=T)
cat("filterColumn( $(this).parents('tr').attr('data-column') );\n",file=htmlFile,append=T)
cat("} );  \n",file=htmlFile,append=T)
#正規表現  
#calStat part  
cat("/*\n",file=htmlFile,append=T)
cat(paste("$('#",tableID,"')\n",sep=""),file=htmlFile,append=T)
cat(".on( 'column-sizing.dt', function () {calStat()} )\n",file=htmlFile,append=T)
cat(".on( 'column-visibility.dt', function () {calStat()} )\n",file=htmlFile,append=T)
cat(".on( 'destroy.dt', function () {calStat()} )\n",file=htmlFile,append=T)
cat(".on( 'draw.dt', function () {calStat()} )\n",file=htmlFile,append=T)
cat(".on( 'init.dt', function () {calStat()} )\n",file=htmlFile,append=T)
cat(".on( 'length.dt', function () {calStat()} )\n",file=htmlFile,append=T)
cat(".on( 'order.dt', function () {calStat()} )\n",file=htmlFile,append=T)
cat(".on( 'page.dt', function () {calStat()} )\n",file=htmlFile,append=T)
cat(".on( 'pre.dt', function () {calStat()} )\n",file=htmlFile,append=T)
cat(".on( 'preXhr.dt', function () {calStat()} )\n",file=htmlFile,append=T)
cat(".on( 'processing.dt', function () {calStat()} )\n",file=htmlFile,append=T)
cat(".on( 'search.dt', function () {calStat()} )\n",file=htmlFile,append=T)
cat(".on( 'stateLoaded.dt', function () {calStat()} )\n",file=htmlFile,append=T)
cat(".on( 'stateLoadParams.dt', function () {calStat()} )\n",file=htmlFile,append=T)
cat(".on( 'stateSaveParams.dt', function () {calStat()} )\n",file=htmlFile,append=T)
cat(".on( 'xhr.dt', function () {calStat()} )\n",file=htmlFile,append=T)
cat(".dataTable();\n",file=htmlFile,append=T)
cat("*/\n",file=htmlFile,append=T)
#calStat part  
cat("});</script>\n\n",file=htmlFile,append=T)
#datatables-javascript
#calStat part-javascript  
cat("<!--\n",file=htmlFile,append=T)
cat("<script>window.onload = function(){calStat()};</script>\n",file=htmlFile,append=T)
cat("<script>\n",file=htmlFile,append=T)
cat("function calStat(){\n",file=htmlFile,append=T)
cat(paste("var sum = 0 , count = 0 , all = $('#",tableID," > tbody > tr') , variance = 0, countPlus = 0;\n",sep=""),file=htmlFile,append=T)
cat("all.each(function() {\n",file=htmlFile,append=T)
cat("sum += +$('td:eq(1)', this).text();\n",file=htmlFile,append=T)
cat("count++;\n",file=htmlFile,append=T)
cat("});\n",file=htmlFile,append=T)
cat("//all.find('td:eq(5)').text((sum / count).toFixed(1));\n",file=htmlFile,append=T)
cat("mean = sum / count;\n",file=htmlFile,append=T)
cat("all.each(function() {\n",file=htmlFile,append=T)
cat("tmp = $('td:eq(1)', this).text()-mean;\n",file=htmlFile,append=T)
cat("variance = variance + tmp*tmp;\n",file=htmlFile,append=T)
cat("if( 0<= $('td:eq(1)', this).text() ){countPlus++}\n",file=htmlFile,append=T)
cat("});\n",file=htmlFile,append=T)
cat("variance = variance / count;\n",file=htmlFile,append=T)
cat("deviation = Math.pow(variance,0.5);\n",file=htmlFile,append=T)
cat("document.form1.mean.value = mean.toFixed(2);\n",file=htmlFile,append=T)
cat("document.form1.variance.value = variance.toFixed(2);\n",file=htmlFile,append=T)
cat("document.form1.deviation.value = deviation.toFixed(2);\n",file=htmlFile,append=T)
cat("document.form1.countPlus.value = countPlus.toFixed(2);\n",file=htmlFile,append=T)
cat("}\n",file=htmlFile,append=T)
cat("</script>\n",file=htmlFile,append=T)
cat("-->\n",file=htmlFile,append=T)
#calStat part-javascript
#html-table
cat("<div style=\"text-align:center\">\n",file=htmlFile,append=T)
cat("<b>",mainTitle,"</b><br>",file=htmlFile,append=T)
cat("Data Source:",dataSource,"<br>",file=htmlFile,append=T)
cat("データ確認日:",year(SD),"年",month(SD),"月",day(SD),"日<br><hr>",file=htmlFile,append=T)
cat("</div>\n",file=htmlFile,append=T)
#calStat part  
cat("<!--\n",file=htmlFile,append=T)
cat("<form name=\"form1\">\n",file=htmlFile,append=T)
cat("<table width=\"100%\">\n<tbody>\n",file=htmlFile,append=T)
cat("<tr>",file=htmlFile,append=T)
cat("<td style=\"text-align:center\" colspan=\"4\">テーブル表示範囲の基本統計量</td>",file=htmlFile,append=T)
cat("</tr>\n",file=htmlFile,append=T)
cat("<tr>",file=htmlFile,append=T)
cat("<td style=\"width:25%;text-align:right\" bgcolor=\"#F5F5F5\">平均値</td>",file=htmlFile,append=T)
cat("<td style=\"width:25;\"><input type=\"number\" style=\"ime-mode:disabled;text-align:right\" name=\"mean\" size=\"10\"></td>",file=htmlFile,append=T)
cat("<td style=\"width:25%;text-align:right\" bgcolor=\"#F5F5F5\">標本分散</td>",file=htmlFile,append=T)
cat("<td style=\"width:25%;\"><input type=\"number\" style=\"ime-mode:disabled;text-align:right\" name=\"variance\" size=\"10\"></td>",file=htmlFile,append=T)
cat("</tr>\n",file=htmlFile,append=T)
cat("<tr>",file=htmlFile,append=T)
cat("<td style=\"text-align:right\" bgcolor=\"#F5F5F5\">標本偏差</td>",file=htmlFile,append=T)
cat("<td><input type=\"number\" style=\"ime-mode:disabled;text-align:right\" name=\"deviation\" size=\"10\"></td>",file=htmlFile,append=T)
cat("<td style=\"text-align:right\" bgcolor=\"#F5F5F5\">プラス値データ数</td>",file=htmlFile,append=T)
cat("<td><input type=\"number\" style=\"ime-mode:disabled;text-align:right\" name=\"countPlus\" size=\"10\"></td>",file=htmlFile,append=T)
cat("</tr>\n",file=htmlFile,append=T)
cat("</tbody>\n</table>\n",file=htmlFile,append=T)
cat("</form>\n",file=htmlFile,append=T)
cat("-->\n",file=htmlFile,append=T)
#Reference http://stackoverflow.com/questions/12212567/jquery-calculate-average-of-column-values-and-put-it-in-each-td-of-another-co  
#calStat part
#正規表現
cat("<div style=\"text-align:center\">\n",file=htmlFile,append=T)
cat("<b>正規表現対応フィルターボックス</b>",file=htmlFile,append=T)  
cat("</div>\n",file=htmlFile,append=T)
cat("\n<table width=\"100%\"><thead><tr><th width=\"15%\" style=\"text-align:center\">Target</th><th width=\"75%\" style=\"text-align:center\">Search text</th><th style=\"text-align:center\">Regex</th></tr></thead><tbody>\n",file=htmlFile,append=T)
for(rccc in 1:ncol(htmldataset)){
cat(paste("<tr id=\"filter_col",rccc,"\" data-column=\"",rccc-1,"\">\n",sep=""),file=htmlFile,append=T)
cat(paste("<td>",colnames(htmldataset)[rccc],"</td>",sep=""),file=htmlFile,append=T)
cat(paste("<td align=\"center\"><input type=\"text\" class=\"column_filter\" id=\"col",rccc-1,"_filter\"  style=\"width:100%\"></td>\n",sep=""),file=htmlFile,append=T)
cat(paste("<td align=\"center\"><input type=\"checkbox\" class=\"column_filter\" id=\"col",rccc-1,"_regex\" checked=\"checked\"></td>\n",sep=""),file=htmlFile,append=T)
#cat(paste("<td align=\"center\"><input type=\"checkbox\" class=\"column_filter\" id=\"col",rccc-1,"_smart\" checked=\"checked\"></td>\n",sep=""),file=htmlFile,append=T)
cat("</tr>\n",file=htmlFile,append=T)
}  
cat("\n</tbody></table>",file=htmlFile,append=T)  
cat("<script>\n",file=htmlFile,append=T)  
cat("function filterGlobal () {\n",file=htmlFile,append=T) 
cat(paste("$('#",tableID,"').DataTable().search(\n",sep=""),file=htmlFile,append=T) 
cat("$('#global_filter').val(),\n",file=htmlFile,append=T) 
cat("$('#global_regex').prop('checked'),\n",file=htmlFile,append=T) 
cat("$('#global_smart').prop('checked')\n",file=htmlFile,append=T) 
cat(").draw();\n",file=htmlFile,append=T) 
cat("}\n",file=htmlFile,append=T) 
cat("function filterColumn ( i ) {\n",file=htmlFile,append=T)
cat(paste("$('#",tableID,"').DataTable().column( i ).search(\n",sep=""),file=htmlFile,append=T)
cat("$('#col'+i+'_filter').val(),\n",file=htmlFile,append=T)
cat("$('#col'+i+'_regex').prop('checked'),\n",file=htmlFile,append=T)
cat("$('#col'+i+'_smart').prop('checked')\n",file=htmlFile,append=T)
cat(").draw();\n",file=htmlFile,append=T)
cat("}\n",file=htmlFile,append=T)
cat("</script>\n",file=htmlFile,append=T)  
#正規表現
#table
for(ccc in 1:ncol(htmldataset)){
  if(4<=ccc){
    col[[ccc]]<-paste("<td align=\"right\" valign=\"middle\">",format(htmldataset[,ccc],big.mark=",",scientific=F),"</td>",sep="")
  }else{  
    col[[ccc]]<-paste("<td align=\"right\" valign=\"middle\">",htmldataset[,ccc],"</td>",sep="")
  }  
  grandData<-cbind(grandData,col[[ccc]])
  header<-paste(header,"<th>",colnames(htmldataset)[ccc],"</th>",sep="")  
}
tableHtml<-paste("<table cellpadding=\"0\" cellspacing=\"0\" id=\"",tableID,"\" width=\"100%\" class=\"display\"><thead>",sep="")
tableHtml<-paste(tableHtml,header,"</thead><tfoot>",sep="")
tableHtml<-paste(tableHtml,header,"</tfoot>",sep="")
cat("<div style=\"overflow-x:scroll;\">\n",file=htmlFile,append=T)  
cat(tableHtml,file=htmlFile,append=T)
grandData<-data.frame("<tr>",grandData,"</tr>",row.names=NULL)
write.table(grandData,htmlFile,quote=F,col.names=F, append=T,row.names=F)
cat("</table>",file=htmlFile,append=T)
cat("</div>\n",file=htmlFile,append=T)
cat("Powered by<br>",file=htmlFile,append=T)
cat("- jQuery : <a href=\"https://jquery.com/\" target=\"_blank\">https://jquery.com/</a><br>",file=htmlFile,append=T)
cat("- DataTables : <a href=\"http://datatables.net/\" target=\"_blank\">http://datatables.net/</a><br>",file=htmlFile,append=T)
cat("- PACE : <a href=\"http://github.hubspot.com/pace/docs/welcome/\" target=\"_blank\">http://github.hubspot.com/pace/docs/welcome/</a>",file=htmlFile,append=T)
#table
cat("<hr><div style=\"text-align:center\">アセット･マネジメント･コンサルティング株式会社 <a href=\"http://am-consulting.co.jp\" target=\"_blank\">http://am-consulting.co.jp</a></div>",file=htmlFile,append=T)
#ga  
cat("<script>\n",file=htmlFile,append=T)
cat("(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){\n",file=htmlFile,append=T)
cat("(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),\n",file=htmlFile,append=T)
cat("m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)\n",file=htmlFile,append=T)
cat("})(window,document,'script','//www.google-analytics.com/analytics.js','ga');\n",file=htmlFile,append=T)
cat("ga('create', 'UA-3077339-2', 'auto');\n",file=htmlFile,append=T)
cat("ga('send', 'pageview');\n",file=htmlFile,append=T)
cat("</script>\n",file=htmlFile,append=T)
#ga  
cat("</body>\n",file=htmlFile,append=T)
#body
cat("</html>",file=htmlFile,append=T)
#html
#only html
}
#loop
```