
```{r}
requiredPackageList<-c("quantmod","PerformanceAnalytics","lubridate","ggplot2","forecast")
colnames(installed.packages())
notInstalledPackages<-requiredPackageList[!(requiredPackageList %in% installed.packages()[,"Package"])] #apply logical vector to requiredPackageList
if(length(notInstalledPackages)!=0){print(notInstalledPackages);install.packages(notInstalledPackages)}
lapply(requiredPackageList,require,character.only=T)
#Reference 
#http://stackoverflow.com/questions/4090169/elegant-way-to-check-for-missing-packages-and-install-them
#http://stackoverflow.com/questions/8175912/load-multiple-packages-at-once
username<-Sys.info()['user']
pathOutput<-paste("C:/Users/",username,"/Desktop/charts/",sep="")
SD<-Sys.Date()
windowsFonts(Meiryo=windowsFont("Meiryo"))
setwd(pathOutput)
```

```{r}
ts.source<-list()
dataset<-list()
reference<-list()
allData<-xts()
ts.source[[1]]<-c("oanda",1,"http://www.oanda.com/","JPY","EUR")
cnt<-0
for(lll in 1:length(ts.source)){
  for(iii in 4:length(ts.source[[lll]])){
    cnt<-cnt+1
    if(ts.source[[lll]][1]=="oanda"){
      if(ts.source[[lll]][iii]=="JPY" | ts.source[[lll]][iii]=="CHF" | ts.source[[lll]][iii]=="ZAR" | ts.source[[lll]][iii]=="KRW"){
        item<-paste("USD/",ts.source[[lll]][iii],sep="")
      }else{
        item<-paste(ts.source[[lll]][iii],"/USD",sep="")
      }
    }
    else{
      item<- ts.source[[lll]][iii]
    }
    dataset[[cnt]]<-getSymbols(item,src=ts.source[[lll]][1],auto.assign=FALSE)
    dataset[[cnt]]<-dataset[[cnt]][,as.double(ts.source[[lll]][2])]
    allData<-merge(allData,dataset[[cnt]])
    dataset[[cnt]]<-na.omit(dataset[[cnt]])
    reference[[cnt]]<-ts.source[[lll]][3]
  }
}
```

```{r}
########## arima
setwd(pathOutput)
confidenceInterval<-c(50,90,95,99)
ci<-paste(confidenceInterval,"%",sep="",collapse=", ") 
forecast.interval<-20
for(zzz in 1:length(dataset)){
  ST<-Sys.time()  
  addVer<-gsub("\\.","",paste(year(SD),month(SD),day(SD),hour(ST),minute(ST),second(ST),sep=""))
  png.file<-paste(addVer,".png",sep="")
  png(file=png.file,width=1400,height=900)
  par(mfrow=c(1,3),ps=20,mar=c(5,5,5,5),cex.main=1,cex.lab=1,cex.axis=1)
  tmp<-data.frame(date=index(dataset[[zzz]]),dataset[[zzz]], row.names=NULL) #一旦データフレームにする  
  ### left part  
    result.arima<-auto.arima(tmp[,2],ic="aic",trace=F,stepwise=T)
    result.forecast<-forecast(result.arima,level=confidenceInterval,h=forecast.interval) 
    plot(result.forecast,main=paste(colnames(tmp)[2],"\nC.I.:",ci,"\nOriginal Data source:",reference[[zzz]]),type="l",lwd=1,family="Meiryo",ylab=colnames(tmp)[2])
    xx<-c(
      first(index(tmp)),
      floor(index(tmp)[nrow(tmp)/4]),
      floor(index(tmp)[nrow(tmp)/2]),
      floor(index(tmp)[nrow(tmp)*3/4]),
      last(index(tmp))
    )
    yy<-tmp[,2][xx]
    ll<-paste(tmp[,1][xx],yy)
    text(x=xx,y=yy,labels=ll,srt=0,cex=0.8,adj=0.5,col="blue",family="Meiryo")
    text(x=first(index(tmp)),y=(max(tmp[,2])+min(tmp[,2]))/2,labels=paste("Forecast by ",result.forecast$method,sep=""),srt=-1,cex=1.2,adj=0,col="blue",family="Meiryo")
  ### left part  
  ### middle part
    fowardLength<-10
    result.arima<-auto.arima(tmp[,2],ic="aic",trace=F,stepwise=T)
    result.forecast<-forecast(result.arima,level=confidenceInterval,h=forecast.interval) 
    ymin<-min(min(tail(tmp[,2],fowardLength)),min(result.forecast$lower[,4]))
    ymax<-max(max(tail(tmp[,2],fowardLength)),max(result.forecast$upper[,4]))
    xmin<-nrow(tmp)-fowardLength  
    xmax<-nrow(tmp)+forecast.interval 
    plot(result.forecast,main=paste(colnames(tmp)[2],"\nC.I.:",ci,"\nOriginal Data source:",reference[[zzz]]),type="o",lwd=1,xlim=c(xmin,xmax),ylim=c(ymin,ymax),family="Meiryo",ylab=colnames(tmp)[2])
    text(x=index(tmp),y=tmp[,2],labels=paste(index(tmp),"-",tmp[,1]),srt=90,cex=0.8,adj=1.1,family="Meiryo")
    selectedPoint<-c(1,floor(forecast.interval/2),forecast.interval)
    xx<-last(index(tmp))+selectedPoint
    dd<-last(tmp[,1])+selectedPoint
    yyLower<-result.forecast$lower[,4][selectedPoint]  
    llLower<-format(yyLower,digits=4)
    yyUpper<-result.forecast$upper[,4][selectedPoint]  
    llUpper<-format(yyUpper,digits=4)
    text(x=xx,y=yyLower,labels=paste(dd,"-",llLower,sep=""),srt=0,cex=0.8,adj=1,col=2,family="Meiryo")
    text(x=xx,y=yyUpper,labels=paste(dd,"-",llUpper,sep=""),srt=0,cex=0.8,adj=1,col=2,family="Meiryo")
    text(x=xmin,y=ymin,labels=paste("Forecast by ",result.forecast$method,sep=""),srt=-1,cex=1.2,adj=0,col="blue",family="Meiryo")
  ### middle part
  ### right part
    fowardLength<-100
    tmpTest<-tmp[1:(nrow(tmp)-forecast.interval),]   
    result.arima<-auto.arima(tmpTest[,2],ic="aic",trace=T,stepwise=T)       
    result.forecast<-forecast(result.arima,level=confidenceInterval,h=forecast.interval)  
    ymin<-min(min(tail(tmp[,2],fowardLength)),min(result.forecast$lower[,4]))
    ymax<-max(max(tail(tmp[,2],fowardLength)),max(result.forecast$upper[,4]))
    xmin<-nrow(tmp)-fowardLength  
    xmax<-nrow(tmp) 
    plot(result.forecast,main=paste(colnames(tmp)[2],"\nC.I.:",ci,"\nOriginal Data source:",reference[[zzz]]),lwd="1",xlim=c(xmin,xmax),ylim=c(ymin,ymax),family="Meiryo",ylab=colnames(tmp)[2]) 
    par(new=T)
    ymin<-min(min(tail(tmp[,2],fowardLength)),min(result.forecast$lower[,4]))
    ymax<-max(max(tail(tmp[,2],fowardLength)),max(result.forecast$upper[,4]))
    xmin<-nrow(tmp)-fowardLength  
    xmax<-nrow(tmp)
    plot(x=tail(index(tmp),forecast.interval),y=tail(tmp[,2],forecast.interval),type="l",xlim=c(xmin,xmax),ylim=c(ymin,ymax),main="",xlab="",ylab="",axes=F) 
    lines(x=tail(index(tmp),forecast.interval),y=tail(tmp[,2],forecast.interval),col="red",lwd=4)
    xx<-c(
      index(tmp)[xmin]+floor(fowardLength/2)-forecast.interval,
      nrow(tmp)-forecast.interval,
      nrow(tmp)-forecast.interval+1,
      last(index(tmp))
    )
    yy<-tmp[,2][xx]  
    ll<-paste(tmp[,1][xx],tmp[,2][xx])  
    text(x=xx,y=yy,labels=ll,srt=0,cex=0.8,adj=0.5,col="blue",family="Meiryo")
    text(x=xmin,y=ymin,labels=paste("Forecast by ",result.forecast$method,sep=""),srt=-1,cex=1.2,adj=0,col="blue",family="Meiryo")
  ### right part
  dev.off()
}  
```