```{r}
requiredPackageList<-c("ggplot2","lubridate","maptools")
colnames(installed.packages())
notInstalledPackages<-requiredPackageList[!(requiredPackageList %in% installed.packages()[,"Package"])] #apply logical vector to requiredPackageList
if(length(notInstalledPackages)!=0){print(notInstalledPackages);install.packages(notInstalledPackages)}
lapply(requiredPackageList,require,character.only=T)
#Reference 
#http://stackoverflow.com/questions/4090169/elegant-way-to-check-for-missing-packages-and-install-them
#http://stackoverflow.com/questions/8175912/load-multiple-packages-at-once
SD<-Sys.Date()
username<-Sys.info()['user']
pathOutput<-paste("C:/Users/",username,"/Desktop/charts/",sep="")
shapeFolder<-"ne_50m_admin_0_countries" # ne_50m_admin_0_countries shapeFile ne_50m_urban_areas
pathShapeFile<-paste("C:/Users/",username,"/Desktop/",shapeFolder,"/",sep="")
windowsFonts(Meiryo=windowsFont("Meiryo"))
# The following codes are cited from http://stackoverflow.com/questions/6862742/draw-a-circle-with-ggplot2
circleFun <- function(center = c(0,0),diameter = 1, npoints = 100){
    r = diameter / 2
    tt <- seq(0,2*pi,length.out = npoints)
    xx <- center[1] + r * cos(tt)
    yy <- center[2] + r * sin(tt)
    return(data.frame(x = xx, y = yy))
}
# The above codes are cited from http://stackoverflow.com/questions/6862742/draw-a-circle-with-ggplot2
```

```{r}
regionName<-"iso_a3"
setwd(pathShapeFile)
file.name<-dir(pathShapeFile,pattern=".shp")
map.obj<-readShapeSpatial(file.name)
print(names(map.obj));print(ncol(map.obj));print(class(map.obj))
plot(map.obj)
map.df<-fortify(map.obj,region=regionName)
print(head(map.df));print(tail(map.df));print(unique(map.df[,ncol(map.df)]))
mapData<-map.df[order(map.df$order),]
```

```{r}
data.location<-2 #1:local 2:web
data.file<-"all_month.csv"
if(data.location==1){
  pathEarthquake<-paste("C:/Users/",username,"/Desktop/Earthquake_Data/",sep="")
  dataset<-read.table(file=paste(pathEarthquake,data.file,sep=""),sep=",",header=T,as.is=T,skip=0)
}else{
  dataTime<-Sys.time()
  dataset<-read.csv(paste("http://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/",data.file,sep=""),header=T,as.is=T,skip=0) 
}
dataset$JST<-as.POSIXct(sub("Z","",sub("T"," ",dataset$time)))+3600*9 #UTC+9
dataset$Energy.GJ<-round(10^((dataset$mag)*1.5+4.8)*(10^-9),4)
```

```{r}
sourceURL<-"ソースデータ:http://earthquake.usgs.gov/"
selectedCountry<-c("JPN","JPN","entireworld")
selectedRegion<-c("","tohoku","")
for(eee in 1:length(selectedCountry)){
  if(selectedCountry[eee]=="JPN"){
    datasetMap<-dataset[grep("Japan",dataset$place),]
    subTitle<-"過去30日間において日本周辺に発生した地震\n"
    diameter<-2
    MagBy<-0.5
    tohokuRegion<-0
    if(selectedRegion[eee]=="tohoku"){
      datasetMap<-subset(datasetMap,36<=(datasetMap$latitude) & (datasetMap$latitude)<=41 & 139<=datasetMap$longitude)
      subTitle<-"過去30日間において東北地方(緯度:35度-41度,経度:139度以東)に発生した地震\n"
      MagBy<-0.1
      tohokuRegion<-1
    }  
  }else if(selectedCountry[eee]=="entireworld"){
    datasetMap<-subset(dataset,5<=dataset$mag)
    subTitle<-"過去30日間において発生したマグニチュード5.0以上の地震\n"
    diameter<-8
    MagBy<-0.5
    tohokuRegion<-0
  }
  date.f<-head(datasetMap$JST)[1]
  date.e<-tail(datasetMap$JST)[1]
##### making a map part  
  q<-ggplot()
  selectedMap<-NULL
  if(selectedCountry[eee]=="entireworld"){
    selectedMap<-mapData  
  }else{
    selectedMap<-subset(mapData,mapData$id==selectedCountry[eee])
  }  
  q<-q+geom_polygon(data=selectedMap,aes(long,lat,group=group),alpha=0.0,colour="black")
##### making a map part  
  for(mmm in seq(floor(min(datasetMap$mag)),ceiling(max(datasetMap$mag)),by=MagBy)){
    earthquakeList<-NULL
    tmp<-subset(datasetMap,mmm<=(datasetMap$mag) & (datasetMap$mag)<(mmm+MagBy))
    if(nrow(tmp)!=0){
      for(rrr in 1:nrow(tmp)){
        dat<-circleFun(c(tmp$longitude[rrr],tmp$latitude[rrr]),diameter,100)
        dat<-cbind(dat,id=rrr)  
        earthquakeList<-rbind(earthquakeList,dat)
      }
      mainTitle<-paste(subTitle,date.e,"から",date.f,"\nマグニチュード",mmm,"以上",mmm+MagBy,"未満.地震数計=",nrow(tmp),"\nソースデータ確認日時:",dataTime," , ",sourceURL)
      g<-q+geom_polygon(data=earthquakeList,aes(earthquakeList$x,earthquakeList$y,group=earthquakeList$id),alpha=0.1,colour="blue")
      g<-g+geom_point(data=tmp,aes(x=longitude, y=latitude),col="red") #aes(,size=tmp$mag)
      g<-g+geom_text(data=tmp,aes(x=longitude, y=latitude,label=paste("Mag(",magType,"):",mag,"\nDepth(km):",depth,"\n",JST,sep="")),hjust=0.5,size=4,family="Meiryo")
      g<-g+theme(legend.position="none")
      g<-g+coord_equal()
      g<-g+xlab("")+ylab("")
      g<-g+ggtitle(mainTitle)
      g<-g+theme(axis.text=element_text(size=20,family="Meiryo"))   
      g<-g+theme(axis.title=element_text(colour="white",size=1,face="bold",family="Meiryo"))   
      g<-g+theme(title=element_text(size=20,face="bold",family="Meiryo"))   
      g<-g+theme(legend.position="bottom")   
      g<-g+theme(legend.text=element_text(colour="black",size=40,face="bold",family="Meiryo"))   
      g<-g+theme(legend.title=element_text(colour="white",size=0,face="bold",family="Meiryo"))   
      setwd(pathOutput)
      ST<-Sys.time()  
      addVer<-gsub("\\.","",paste(year(SD),month(SD),day(SD),hour(ST),minute(ST),second(ST),sep=""))
      if(selectedRegion[eee]=="tohoku"){
        addVer<-paste("TOHOKU",addVer,sep="")
      }  
      png.file<-paste(addVer,".png",sep="")
      png(file=png.file,width=1200,height=900)
      par(mar=c(0,0,12,0),ps=40)
      print(g)
      dev.off()
    }  
  }
}
```

```{r}
for(eee in 1:length(selectedCountry)){
  if(selectedCountry[eee]=="JPN"){
    datasetMap<-dataset[grep("Japan",dataset$place),]
    subTitle<-"過去30日間において日本周辺に発生した地震\n"
    tohokuRegion<-0
    if(selectedRegion[eee]=="tohoku"){
      datasetMap<-subset(datasetMap,36<=(datasetMap$latitude) & (datasetMap$latitude)<=41 & 139<=datasetMap$longitude)
      subTitle<-"過去30日間において東北地方(緯度:35度-41度,経度:139度以東)に発生した地震\n"
      tohokuRegion<-1
    }  
  }else if(selectedCountry[eee]=="entireworld"){
    datasetMap<-subset(dataset,5<=dataset$mag)
    subTitle<-"過去30日間において発生したマグニチュード5.0以上の地震\n"
    tohokuRegion<-0
  }
  date.f<-head(datasetMap$JST)[1]
  date.e<-tail(datasetMap$JST)[1]
  for(pppp in 1:2){
    tmp<-datasetMap
    if(pppp==1){
      mainTitle<-paste(subTitle,date.e,"から",date.f,"\nマグニチュード降順(上位20)\nソースデータ確認日時:",dataTime,"\n",sourceURL)
      barColor<-"blue"
      objectCol<-grep("mag",colnames(datasetMap)) #magとmagTypeの両方が選択される
      ylabTitle<-"マグニチュード"
    }else{
      mainTitle<-paste(subTitle,date.e,"から",date.f,"\nエネルギー降順(上位20)\nソースデータ確認日時:",dataTime,"\n",sourceURL)
      barColor<-"red"  
      objectCol<-grep("Energy.GJ",colnames(datasetMap))
      ylabTitle<-"エネルギー(GJ)\n(注)本チャートではマグニチュードタイプ(Mb,Mw等)に関らず\nE(GJ)=10^(マグニチュード*1.5+4.8)*(10^-9)"
    }
    tmp<-data.frame(paste(tmp$JST,"\n",tmp$place,sep=""),tmp[,objectCol],tmp$depth,tmp$latitude,tmp$longitude)
    rrr<-order(tmp[,2],decreasing=F)
    tmp<-tmp[rrr,]
    tmp[,1]<-ordered(tmp[,1],levels=tmp[,1][1:length(tmp[,1])])
    tmp<-tail(tmp,20)
    setwd(pathOutput)
    g<-ggplot()
    g<-g+geom_bar(data=tmp,aes(x=tmp[,1],y=tmp[,2]),stat="identity",position="identity",fill=barColor,alpha=0.2,color="black")
    g<-g+coord_flip()
    g<-g+xlab("")+ylab(ylabTitle)
    g<-g+ggtitle(mainTitle)
    g<-g+theme(axis.text=element_text(size=15,family="Meiryo"))   
    g<-g+theme(axis.title=element_text(colour="black",size=20,face="bold",family="Meiryo"))   
    g<-g+theme(title=element_text(size=20,face="bold",family="Meiryo",hjust=0.5))   
    g<-g+theme(legend.position="bottom")   
    g<-g+theme(legend.text=element_text(colour="black",size=40,face="bold",family="Meiryo"))   
    g<-g+theme(legend.title=element_text(colour="white",size=20,face="bold",family="Meiryo"))
    if(pppp==1){  
      g<-g+geom_text(data=tmp,aes(x=tmp[,1],y=tmp[,2],
        label=paste("Mag(",tmp[,3],"):",tmp[,2],",Depth(km):",tmp[,4],",lat:",tmp[,5],",lon:",tmp[,6],sep="")),vjust=0.5,hjust=1,size=5,face="bold",family="Meiryo") 
    }
    ST<-Sys.time()  
    addVer<-gsub("\\.","",paste(year(SD),month(SD),day(SD),hour(ST),minute(ST),second(ST),sep=""))
    if(selectedRegion[eee]=="tohoku"){
      addVer<-paste("TOHOKU",addVer,sep="")
    }  
    png.file<-paste(addVer,".png",sep="")
    png(file=png.file,width=1200,height=900)
    par(mar=c(10,0,12,0),ps=40)
    print(g)
    dev.off()
  }
}  
```
