```{r}
requiredPackageList<-c("ggplot2","lubridate","maptools","plotrix")
colnames(installed.packages())
notInstalledPackages<-requiredPackageList[!(requiredPackageList %in% installed.packages()[,"Package"])] #apply logical vector to requiredPackageList
if(length(notInstalledPackages)!=0){print(notInstalledPackages);install.packages(notInstalledPackages)}
lapply(requiredPackageList,require,character.only=T)
#Reference 
#http://stackoverflow.com/questions/4090169/elegant-way-to-check-for-missing-packages-and-install-them
#http://stackoverflow.com/questions/8175912/load-multiple-packages-at-once
SD<-Sys.Date()
username<-Sys.info()['user']
pathOutput<-paste("C:/Users/",username,"/Desktop/charts/",sep="")
shapeFolder<-"ne_50m_admin_0_countries" # ne_50m_admin_0_countries shapeFile ne_50m_urban_areas
pathShapeFile<-paste("C:/Users/",username,"/Desktop/",shapeFolder,"/",sep="")
windowsFonts(Meiryo=windowsFont("Meiryo"))
```

```{r}
regionName<-"iso_a3"
setwd(pathShapeFile)
file.name<-dir(pathShapeFile,pattern=".shp")
map.obj<-readShapeSpatial(file.name)
print(names(map.obj));print(ncol(map.obj));print(class(map.obj))
plot(map.obj)
map.df<-fortify(map.obj,region=regionName)
print(head(map.df));print(tail(map.df));print(unique(map.df[,ncol(map.df)]))
mapData<-map.df[order(map.df$order),]
```

```{r}
location<-c(
  141.033611,37.421389,"福島第一原子力発電所",
  139.744901,35.676777,"国会議事堂",
  140.467521,37.750498,"福島県庁",
  140.123340,35.605298,"千葉県庁", 
  140.446750,36.342059,"茨城県庁", 
  139.883597,36.565971,"栃木県庁",
  139.060464,36.390900,"群馬県庁",
  139.648922,35.857693,"埼玉県庁", 
  140.872146,38.269113,"宮城県庁", 
  141.152624,39.703774,"岩手県庁" 
  )
setwd(pathOutput)
data<-list()
data.location<-2 #1:local 2:web
data.file<-"http://radioactivity.nsr.go.jp/ja/contents/10000/9290/24/inside_20km_airdose.csv"
if(data.location==1){
#  pathEarthquake<-paste("C:/Users/",username,"/Desktop/Earthquake_Data/",sep="")
#  dataset<-read.table(file=paste(pathEarthquake,data.file,sep=""),sep=",",header=T,as.is=T,skip=0)
}else{
  dataTime<-Sys.time()
  dataset<-read.csv(data.file,header=T,skip=0,stringsAsFactor=F,na.strings=c("")) 
}
dataset<-dataset[-1,]
dataset<-dataset[is.na(dataset[,12])==F,]
convertTonumeric<-c(3,8,9,10,12)
for(ttt in 1:length(convertTonumeric)){
  dataset[,convertTonumeric[ttt]]<-as.numeric(dataset[,convertTonumeric[ttt]])
}
dataset[,1]<-as.Date(dataset[,1])
colnames(dataset)
tmp<-dataset[,c(1,2,4,8,9,10,11,12,13)]
colnames(tmp)
colnames(tmp)[6]<-gsub("km\\.","km",colnames(tmp)[6])
colnames(tmp)[8]<-gsub("\\.h\\.","/h",colnames(tmp)[8])
tmp<-subset(tmp,tmp[,2]!="NA")
tmp$latlon<-paste(tmp[,4],":",tmp[,5],sep="")
tmp$time<-as.POSIXct(paste(tmp[,1],paste(tmp[,2],":00",sep="")))
tmp<-subset(tmp,tmp[,9]=="NaI")
cnt<-0
for(ddd in 1:length(unique(tmp$latlon))){
  buf<-subset(tmp,unique(tmp$latlon)[ddd]==tmp$latlon)
  buf<-subset(buf,unique(buf[,6])[1]==buf[,6])
  if(100<=nrow(buf) & 5<=tail(buf[,8],1)){
    ST<-Sys.time()  
    addVer<-gsub("\\.","",paste(year(SD),month(SD),day(SD),hour(ST),minute(ST),second(ST),sep=""))
    png.file<-paste(addVer,".png",sep="")
    png(file=png.file,width=1600,height=1000)
    par(oma=c(1,1,7,1),mfrow=c(1,2),ps=20,mar=c(5,5,5,5),cex.main=1.2,cex.lab=1.5,cex.axis=1.2,family="Meiryo")
    cnt<-cnt+1
    data[[cnt]]<-buf
    cat(cnt,"-",nrow(data[[cnt]]),"-",max(data[[cnt]][,8]),"\n")
    ranking<-order(data[[cnt]][,11],decreasing=F)
    data[[cnt]]<-data[[cnt]][ranking,]
    title<-paste(
      "線量計:NaI(ヨウ化ナトリウム)シンチレータ\n",
      format(head(data[[cnt]][,11],1),"%Y/%m/%d %H:%M")," ~ ",
      format(tail(data[[cnt]][,11],1),"%Y/%m/%d %H:%M"),
    sep="")
    positionY<-(max(data[[cnt]][,8])-min(data[[cnt]][,8]))/1.5+max(data[[cnt]][,8])
    plot(
      x=data[[cnt]][,11],
      y=data[[cnt]][,8],
      type="h",
      main=title,xaxt="n",
      col="blue",
      ylim=c(min(data[[cnt]][,8]),positionY),
      xlab="",
      ylab=""
    )
    axis.POSIXct(side=1,data[[cnt]][,11],format="%Y/%m/%d")
    tmpTable<-data[[cnt]][,c(11,8)]
    tmpTable[,1]<-format(tmpTable[,1],"%Y/%m/%d %H:%M")
    addtable2plot(x=head(data[[cnt]][,11],1),y=positionY,table=tail(tmpTable,10),
      bty="o",hlines=T,vlines=T,yjust=-0.02)
    ##### making a map part  
    plot(subset(map.obj,map.obj@data$iso_a3=="JPN"),axes=TRUE,asp=1,
      panel.first=grid(NULL,NULL,lty=2,col="#E9DECA"),xlim=c(138,144),ylim=c(34,40))
    text(unique(data[[cnt]][,5]),unique(data[[cnt]][,4]),unique(data[[cnt]][,3]),cex=1,col="black",font=1,pos=2)
    draw.circle(unique(data[[cnt]][,5]),unique(data[[cnt]][,4]),0.05,col=rgb(255,0,0,80,maxColorValue=255),
      border=rgb(255,0,0,maxColorValue=255))
    for(sss in 0:(length(location)/3-1)){
      text(as.numeric(location[sss*3+1]),as.numeric(location[sss*3+2]),location[sss*3+3],cex=1,col="black",font=1,pos=4)
      draw.circle(as.numeric(location[sss*3+1]),as.numeric(location[sss*3+2]),0.05,col=rgb(0,255,255,80,maxColorValue=255),
        border=rgb(0,255,255,maxColorValue=255))
    }  
    ##### making a map part 
    overallTitle<-paste(
    "No.",cnt,"-",unique(data[[cnt]][,3]),
    "-北緯(度):",unique(data[[cnt]][,4]),"-東経(度):",unique(data[[cnt]][,5]),
      "-",colnames(data[[cnt]])[6],":",unique(data[[cnt]][,6]),
      "\n直近データの年間換算積算線量(mSv/年):",
      tail(data[[cnt]][,8],1),"×(8+0.4×16)×365=",tail(data[[cnt]][,8],1)*(8+0.4*16)*365/1000,
      " , (",tail(data[[cnt]][,8],1),"-0.04)×(8+0.4×16)×365=",(tail(data[[cnt]][,8],1)-0.04)*(8+0.4*16)*365/1000,
      "\nData Source:原子力規制委員会 Download Date:",dataTime,
    sep="")
    title(overallTitle,outer=TRUE,cex.main=1.2,family="Meiryo")
    dev.off()
  }  
}
```