```{r}
library(lubridate)
username<-Sys.info()['user']
pathOutput<-paste("C:/Users/",username,"/Desktop/charts/",sep="")
pathOutput<-paste("C:/Users/",username,"/Desktop/R_Data_Write/",sep="")
SD<-Sys.Date()
needSpeechPart<-0
```

```{r}
#sapplyによると行名と列名が削除される
#fun01<-function(ccc){
#  buf[,ccc]<-as.numeric(buf[,ccc])  
#}  
#ccc<-c(2:ncol(buf))
#buf<-sapply(ccc,fun01)
#sapplyによると行名と列名が削除される
nDate<-100
url<-"http://www.mizuhobank.co.jp/rate/market/csv/quote.csv"
buf<-read.csv(url,header=T,skip=1,stringsAsFactor=F,na.strings=c("*****","NA"))#本rmdではcheck.names=FALSEをつけないこと。本rmdに限らずX処理等を挟んでいる場合は要注意。
buf<-buf[-1,]
buf[,1]<-as.Date(buf[,1])
colnames(buf)[1]<-"Date"
buf<-buf[,regexpr(".1",colnames(buf))==-1]
buf<-tail(buf,nDate)#
for(ccc in 2:ncol(buf)){
  buf[,ccc]<-as.numeric(buf[,ccc])  
}
buf<-buf[,colSums(is.na(buf))==0]
head(buf)
tail(buf)
```

```{r}
variance<-function(x){
  tmp<-sqrt(var(x)*(length(x)-1)/length(x))
  value<-floor(1000*as.numeric(tmp)+0.5)/1000
  return(value)
}
meanValue=as.vector(colMeans(buf[,-1]),mode='numeric')
sdValue=as.vector(apply(buf[,-1],2,variance),mode='numeric')
latest1Data<-as.vector(buf[nrow(buf)-0,-1],mode='numeric')
latest2Data<-as.vector(buf[nrow(buf)-1,-1],mode='numeric')
tmpDataset<-data.frame(
  通貨=colnames(buf[,-1]),
  latest1=latest1Data,
  latest2=latest2Data,
  中央値=as.vector(apply(buf[,-1],2,median),mode='numeric'),
  標本標準偏差=sdValue,
  最大値=as.vector(apply(buf[,-1],2,max),mode='numeric'),
  最小値=as.vector(apply(buf[,-1],2,min),mode='numeric'),
  変動係数=sdValue/meanValue*100,
  前営業日比=(latest1Data-latest2Data)/latest2Data*100,
  row.names=NULL
)
tmpDataset[,c(5,8,9)]<-floor(1000*(tmpDataset[,c(5,8,9)])+0.5)/1000
colnames(tmpDataset)[2:3]<-c(as.character(buf[,1][nrow(buf)-0]),as.character(buf[,1][nrow(buf)-1]))
dataset<-tmpDataset
```

```{r}
menulength<-15
orderColumn<-1
orderDirection<-"desc" #asc desc
dateFormat<-1 #1:as is , 2:scientific , 3:monthly , 4:dayly , 5:yearly
columnWidth<-"{\"width\":\"21%\",\"targets\":0}"
switch(dateFormat, #columa=1のデータフォーマット
  dateFormatType<-"",
  dateFormatType<-"",
  dateFormatType<-"%Y/%m",
  dateFormatType<-"%Y/%m/%d",
  dateFormatType<-"%Y"
)  
```

```{r}
#only html
setwd(pathOutput)
col<-list()
grandData<-NULL
header<-NULL
ST<-Sys.time()  
addVer<-gsub("\\.","",paste(year(SD),month(SD),day(SD),hour(ST),minute(ST),second(ST),sep=""))
tableID<-paste("am-consulting",addVer,sep="")
htmlFile<-paste(addVer,".html",sep="")
htmlFile<-"AssetManagementConsultingCorporation_historicalFXdata.html"
cat("",file=htmlFile,append=F)
cat("<html><head><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n",file=htmlFile,append=T)
cat("<meta http-equiv=\"Pragma\" content=\"no-cache\" />\n",file=htmlFile,append=T)
cat("<meta http-equiv=\"cache-control\" content=\"no-cache\" />\n",file=htmlFile,append=T)
cat("<meta http-equiv=\"expires\" content=\"0\" />\n",file=htmlFile,append=T)
cat("<style>\n",file=htmlFile,append=T)
cat("body{font-family:'Hiragino Kaku Gothic Pro','Meiryo UI',Verdana,sans-serif;}\n",file=htmlFile,append=T)
cat("table{width:100%;border-collapse:collapse;padding:0;border-spacing:1;margin-left: auto;margin-right: auto;}\n",file=htmlFile,append=T)
cat("tr, td, th{white-space: nowrap;}\n",file=htmlFile,append=T)
cat(".dataTables_filter input {width: 50%;}\n",file=htmlFile,append=T)
cat("</style></head><body>\n",file=htmlFile,append=T)
#speech part
if(needSpeechPart==1){
cat("<form name=\"speechDIV\"><b>Speech Recognition APIを利用した簡易分析結果の読み上げ</b><br>\n",file=htmlFile,append=T)
cat(" - 聴取可能ウェブブラウザは http://caniuse.com/#feat=speech-recognition で確認ください。<br>\n",file=htmlFile,append=T)
cat(" - chrome44での動作は確認済みです。\n",file=htmlFile,append=T)
cat("<div style=\"text-align:center\">\n",file=htmlFile,append=T)
cat("<INPUT type=\"button\" value=\"聴 く\" onclick=\"speech();\">&nbsp;\n",file=htmlFile,append=T)
cat("<INPUT type=\"button\" value=\"中 止\" onclick=\"speechStop();\">&nbsp;\n",file=htmlFile,append=T)
cat("<INPUT type=\"button\" value=\"中 断\" onclick=\"speechPause();\">&nbsp;\n",file=htmlFile,append=T)
cat("<INPUT type=\"button\" value=\"再 開\" onclick=\"speechResume();\">&nbsp;\n",file=htmlFile,append=T)
cat("スピード:<select name=\"speechrate\">\n",file=htmlFile,append=T)
cat("<option value=\"1\">1</option>\n",file=htmlFile,append=T)
for(qqq in seq(0.5,2,by=0.1)){  
  cat(paste("<option value=\"",qqq,"\">",qqq,"</option>\n",sep=""),file=htmlFile,append=T)
}
cat("</select>\n",file=htmlFile,append=T) 
cat("</div></form><hr>\n",file=htmlFile,append=T)  
}
#speech part
cat("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js\"></script>",file=htmlFile,append=T)
cat("<link href=\"http://cdn.datatables.net/1.10.7/css/jquery.dataTables.min.css\" rel=\"stylesheet\">",file=htmlFile,append=T) 
cat("<script src=\"http://cdn.datatables.net/1.10.7/js/jquery.dataTables.min.js\"></script>",file=htmlFile,append=T) 
cat("<script src=\"http://archive.am-consulting.co.jp/dataTables.fixedColumns.js\"></script>\n",file=htmlFile,append=T)
cat("<link href=\"http://archive.am-consulting.co.jp/dataTables.fixedColumns.css\" rel=\"stylesheet\">\n",file=htmlFile,append=T)
cat("<script type=\"text/javascript\" charset=\"utf-8\">\n",file=htmlFile,append=T)
cat("$(document).ready( function(){\n",file=htmlFile,append=T)
cat(paste("var table =$('#",tableID,"').dataTable( {\n",sep=""),file=htmlFile,append=T)
cat("\"lengthMenu\": [[",menulength,",-1], [",menulength,",\"All\"]],",file=htmlFile,append=T)
cat(paste("\"order\": [[ ",orderColumn,", \"",orderDirection,"\" ]],",sep=""),file=htmlFile,append=T)
cat("\"searching\": true,",file=htmlFile,append=T)
cat("\"columnDefs\":[",columnWidth,"],",file=htmlFile,append=T)
cat("\"language\": {\"decimal\": \".\",\"thousands\": \",\"},",file=htmlFile,append=T)
cat("\"scrollX\": true,",file=htmlFile,append=T)
cat("\"scrollCollapse\": true\n",file=htmlFile,append=T)
#Row created callback JS
cat(",\"createdRow\": function ( row, data, index ) {\n",file=htmlFile,append=T)
for(ccc in 2:ncol(dataset)){
  cat(paste("if ( data[",ccc-1,"].replace('', '') * 1 < 0 ) {\n",sep=""),file=htmlFile,append=T)
  cat("$('td', row).eq(",ccc-1,").addClass('highlight');\n",file=htmlFile,append=T)
  cat("}\n",file=htmlFile,append=T)
}
cat("}\n",file=htmlFile,append=T)  
#Row created callback JS
cat("});",file=htmlFile,append=T)
#fixed column JS
cat("new $.fn.dataTable.FixedColumns( table, {\n",file=htmlFile,append=T)
cat("leftColumns: 1,\n",file=htmlFile,append=T)
cat("rightColumns: 0\n",file=htmlFile,append=T)
cat("});\n\n",file=htmlFile,append=T)
#fixed column JS
cat("});</script>",file=htmlFile,append=T)
#datatabels css
cat("<style>\ntd.highlight {font-weight: plain;color: red;} \ndiv.ColVis {float: left;}\n</style>\n",file=htmlFile,append=T) 
#datatabels css
for(ccc in 1:ncol(dataset)){
  if(ccc==1){
    switch(dateFormat,
    col[[ccc]]<-paste("<td align=\"right\" valign=\"middle\">",dataset[,ccc],"</td>",sep=""),
    col[[ccc]]<-paste("<td align=\"right\" valign=\"middle\">",format(dataset[,ccc],big.mark=",",scientific=F),"</td>",sep=""),
    col[[ccc]]<-paste("<td align=\"right\" valign=\"middle\">",format(as.Date(dataset[,ccc]),dateFormatType),"</td>",sep=""),
    col[[ccc]]<-paste("<td align=\"right\" valign=\"middle\">",format(as.Date(dataset[,ccc]),dateFormatType),"</td>",sep=""),
    col[[ccc]]<-paste("<td align=\"right\" valign=\"middle\">",format(as.Date(dataset[,ccc]),dateFormatType),"</td>",sep="")
    )
  }else{  
    col[[ccc]]<-paste("<td align=\"right\" valign=\"middle\">",format(dataset[,ccc],big.mark=",",scientific=F),"</td>",sep="")
  }  
  grandData<-cbind(grandData,col[[ccc]])
  header<-paste(header,"<th>",colnames(dataset)[ccc],"</th>",sep="")  
}
cat(paste(year(tail(buf[,1],1)),"年",month(tail(buf[,1],1)),"月",day(tail(buf[,1],1)),"日"," 外国為替公示相場(仲値、データ出所:株式会社みずほ銀行)<br>\n",sep=""),file=htmlFile,append=T)
cat(paste("中央値、標本標準偏差、最大値、最小値、変動係数の対象は",nDate,"営業日分(",head(buf[,1],1),"から",tail(buf[,1],1),")<br>\n"),file=htmlFile,append=T)
cat(paste("変動係数(%)=標本標準偏差/平均値×100<br>\n"),file=htmlFile,append=T)
cat(paste("前営業日比単位：パーセント<br>\n"),file=htmlFile,append=T)
tableHtml<-paste("<table cellpadding=\"0\" cellspacing=\"0\" id=\"",tableID,"\" width=\"100%\" class=\"display\"><thead>",sep="")
tableHtml<-paste(tableHtml,header,"</thead>",sep="")
cat(tableHtml,file=htmlFile,append=T)
grandData<-data.frame("<tr>",grandData,"</tr>",row.names=NULL)
write.table(grandData,htmlFile,quote=F,col.names=F, append=T,row.names=F)
cat("</table>",file=htmlFile,append=T)
cat("Powered by DataTables( http://datatables.net/ )",file=htmlFile,append=T)
#youtubegallery
#cat("<style>.youtube_channel.ytc_wall_1-6 .ytc_video_container {padding: 5px;box-sizing: border-box;font-size: 15px;}</style>",file=htmlFile,append=T)
#cat("<hr>",file=htmlFile,append=T)
#cat("[youtube_channel class=ytc_wall_1-6 channel=UC56EoMsVlhV-OpB7Ua4KJ1Q resource=0 cache=300 num=6 random=0 ratio=3 responsive=0 width=140 display=thumbnail]",file=htmlFile,append=T)
#youtubegallery
cat("<hr><div style=\"text-align:center\">アセット･マネジメント･コンサルティング株式会社 <a href=\"http://am-consulting.co.jp\" target=\"_blank\">http://am-consulting.co.jp</a></div>",file=htmlFile,append=T)
if(needSpeechPart!=1){
cat("</body></html>\n",file=htmlFile,append=T)
}  
```

```{r}
#SpeechRecognitionAPI
#冗長に過ぎるので要改良
phrase<-""
usd<-subset(dataset,dataset[,1]=="米ドル")
euro<-subset(dataset,dataset[,1]=="ユーロ")
pound<-subset(dataset,dataset[,1]=="英ポンド")
franc<-subset(dataset,dataset[,1]=="スイスフラン")
aud<-subset(dataset,dataset[,1]=="オーストラリアドル")
maxCurrency<-dataset[which.max(dataset[,8]),]#変動係数
minCurrency<-dataset[which.min(dataset[,8]),]#変動係数
maxCurrency2<-dataset[which.max(dataset[,9]),]#前営業日比
minCurrency2<-dataset[which.min(dataset[,9]),]#前営業日比
prePhrase<-list()
prePhrase[[1]]="、アセットマネジメントコンサルティング株式会社、です。それでは為替レート簡易分析結果を紹介します。なお原数値データ引用元は、株式会社みずほ銀行、の、外国為替公示相場ヒストリカルデータ、です。"
prePhrase[[2]]=paste(nDate,"営業日分、",head(buf[,1],1),"、から",tail(buf[,1],1),"、までの最高値、最安値、変動係数を紹介します。",sep="")
prePhrase[[3]]="紹介対象通貨は、米ドル、ユーロ、イギリスポンド、スイスフラン、オーストラリアドルの5通貨です。"
prePhrase[[4]]="米ドル、の"
prePhrase[[5]]=paste("最高値は、1ドル",usd[1,6],"円、",sep="")
prePhrase[[6]]=paste("最安値は、1ドル",usd[1,7],"円、",sep="")
prePhrase[[7]]=paste("変動係数は、",usd[1,8],"パーセント、です。",sep="")
prePhrase[[8]]="ユーロ、の"
prePhrase[[9]]=paste("最高値は、1ユーロ",euro[1,6],"円、",sep="")
prePhrase[[10]]=paste("最安値は、1ユーロ",euro[1,7],"円、",sep="")
prePhrase[[11]]=paste("変動係数は、",euro[1,8],"パーセント、です。",sep="")
prePhrase[[12]]="イギリスポンド、の"
prePhrase[[13]]=paste("最高値は、1ポンド",pound[1,6],"円、",sep="")
prePhrase[[14]]=paste("最安値は、1ポンド",pound[1,7],"円、",sep="")
prePhrase[[15]]=paste("変動係数は、",pound[1,8],"パーセント、です。",sep="")
prePhrase[[16]]="スイスフラン、の"
prePhrase[[17]]=paste("最高値は、1スイスフラン",franc[1,6],"円、",sep="")
prePhrase[[18]]=paste("最安値は、1スイスフラン",franc[1,7],"円、",sep="")
prePhrase[[19]]=paste("変動係数は、",franc[1,8],"パーセント、です。",sep="")
prePhrase[[20]]="オーストラリアドル、の"
prePhrase[[21]]=paste("最高値は、1オーストラリアドル",aud[1,6],"円、",sep="")
prePhrase[[22]]=paste("最安値は、1オーストラリアドル",aud[1,7],"円、",sep="")
prePhrase[[23]]=paste("変動係数は、",aud[1,8],"パーセント、です。",sep="")
prePhrase[[24]]="対象期間内で、"
prePhrase[[25]]=paste("最も変動係数の大きい通貨は、",maxCurrency[1,1],"、で",maxCurrency[1,8],"パーセント、",sep="")
prePhrase[[26]]=paste("最も変動係数の小さい通貨は、",minCurrency[1,1],"、で",minCurrency[1,8],"パーセント、です。",sep="")
prePhrase[[27]]=paste("最も前営業日比の大きい通貨は、",maxCurrency2[1,1],"、で",maxCurrency2[1,9],"パーセント、",sep="")
prePhrase[[28]]=paste("最も前営業日比の小さい通貨は、",minCurrency2[1,1],"、で",minCurrency2[1,9],"パーセント、です。",sep="")
prePhrase[[29]]="以上で終了です。ご聴取、ありがとうございました"
for(ppp in 1:length(prePhrase)){
  phrase<-paste(phrase,prePhrase[[ppp]],sep="")
}
phrase<-gsub("、|。","<<>>",phrase)
phrase
cat("\n\n\n\n<script>\n",file=htmlFile,append=T)
cat("//Reference http://www.nickdesteffen.com/blog/html5-speech-synthesis-api-tips-and-tricks\n",file=htmlFile,append=T)
cat("function speechStop(){\n",file=htmlFile,append=T)
cat("window.speechSynthesis.cancel();\n",file=htmlFile,append=T)
cat("}\n",file=htmlFile,append=T)
cat("function speechPause(){\n",file=htmlFile,append=T)
cat("window.speechSynthesis.pause();\n",file=htmlFile,append=T)
cat("}\n",file=htmlFile,append=T)
cat("function speechResume(){\n",file=htmlFile,append=T)
cat("window.speechSynthesis.resume();\n",file=htmlFile,append=T)
cat("}\n",file=htmlFile,append=T)
cat("function speech(){\n",file=htmlFile,append=T)
cat("window.speechSynthesis.cancel();\n",file=htmlFile,append=T)
cat("today=new Date();\n",file=htmlFile,append=T)
cat("hour=today.getHours();\n",file=htmlFile,append=T)
cat("if(5<=hour && hour<=12){\n",file=htmlFile,append=T)
cat("greeting=\"おはようございます\";\n",file=htmlFile,append=T)
cat("}else if(12<hour && hour<=16){\n",file=htmlFile,append=T)
cat("greeting=\"こんにちは\";\n",file=htmlFile,append=T)
cat("}else{\n",file=htmlFile,append=T)
cat("greeting=\"こんばんは\";\n",file=htmlFile,append=T)
cat("}  \n",file=htmlFile,append=T)
cat(paste("phrase=\"",phrase,"\"\n",sep=""),file=htmlFile,append=T)
cat("phrase = greeting + phrase\n",file=htmlFile,append=T)
cat("sentences = phrase.split(\"<<>>\")\n",file=htmlFile,append=T)
cat("for (i = 0; i < sentences.length; i++) {\n",file=htmlFile,append=T)
cat("sentence = sentences[i]\n",file=htmlFile,append=T)
cat("audio = new SpeechSynthesisUtterance(sentence)\n",file=htmlFile,append=T)
cat("audio.lang = \"ja-JP\"\n",file=htmlFile,append=T)
cat("audio.rate=parseFloat(document.speechDIV.speechrate.value);\n",file=htmlFile,append=T)
cat("window.speechSynthesis.speak(audio)\n",file=htmlFile,append=T)
cat("}\n",file=htmlFile,append=T)
cat("}\n",file=htmlFile,append=T)
cat("</script>\n",file=htmlFile,append=T)
#SpeechRecognitionAPI
cat("</body></html>\n",file=htmlFile,append=T)
```