```{r}
requiredPackageList<-c("ggplot2","lubridate","scales","maps","maptools","RColorBrewer","fields","rworldmap","classInt","plotrix","HH","reshape","quantmod")
colnames(installed.packages())
notInstalledPackages<-requiredPackageList[!(requiredPackageList %in% installed.packages()[,"Package"])] #apply logical vector to requiredPackageList
if(length(notInstalledPackages)!=0){print(notInstalledPackages);install.packages(notInstalledPackages)}
lapply(requiredPackageList,require,character.only=T)
#Reference 
#http://stackoverflow.com/questions/4090169/elegant-way-to-check-for-missing-packages-and-install-them
#http://stackoverflow.com/questions/8175912/load-multiple-packages-at-once
username<-Sys.info()['user']
pathOutput<-paste("C:/Users/",username,"/Desktop/charts/",sep="")
pathInput<-paste("C:/Users/",username,"/Desktop/pathToCSV/",sep="")
folder.path<-file.path(pathInput)
setwd(folder.path)
tmp<-read.csv(file=dir(folder.path),header=F,as.is=T,skip=0,na.strings=c("", "NA"))
dir.list<-paste("C:/Users/",username,tmp[1,2],sep="")
SD<-Sys.Date()
creationDate<-paste("作成日:",year(SD),"-",month(SD),"-",day(SD),sep="")  
setwd(pathOutput)
windowsFonts(Meiryo=windowsFont("Meiryo"))
fun.readData<-function(){
  dataset[[cnt]]<<-read.table("clipboard",header=TRUE,sep="\t",stringsAsFactor=F,na.strings=c("-"))
  head(dataset)
  tail(dataset)
}
cnt<-0
```

```{r}
cnt<-cnt+1
fun.readData()
```

```{r}
##################################################### from FRED part ####################################################
binWidthCalibration<-1
tsSource<-list()
dataset<-list()
histgramMonthTail<-120
#tsSource[[1]]<-c("FRED",1,"http://research.stlouisfed.org/","DGS10","GOLDAMGBD228NLBM","DCOILWTICO")
#tsSource[[2]]<-c("FRED",1,"http://research.stlouisfed.org/","NIKKEI225","SP500","DJIA","NASDAQ100")
#tsSource[[3]]<-c("FRED",1,"http://research.stlouisfed.org/","DTWEXM","DEXJPUS","DEXUSEU","DEXUSUK","DEXUSAL")
#tsSource[[4]]<-c("FRED",1,"http://research.stlouisfed.org/","DEXNOUS","DEXSZUS","DEXSFUS","DEXKOUS","DEXUSNZ","DEXCHUS")
tsSource[[1]]<-c("FRED",1,"http://research.stlouisfed.org/","DCOILWTICO")
for(lll in 1:length(tsSource)){
  for(iii in 4:length(tsSource[[lll]])){
    cnt<-cnt+1
    item<- tsSource[[lll]][iii]
    tmp<-getSymbols(item,src=tsSource[[lll]][1],auto.assign=FALSE)
    tmp<-tmp[,as.numeric(tsSource[[lll]][2])]
    dataset[[cnt]]<-data.frame(Date=index(tmp),tmp, row.names=NULL)
  }
}
##################################################### from FRED part ####################################################
```

```{r}
#data reshape part
histgramMonth<-list()
for(ddd in 1:length(dataset)){
  tmpHistogram<-NULL
  buf<-na.omit(dataset[[ddd]])  
  buf$Month<-format(buf[,1],"%Y/%m")
  buf$Year<-format(buf[,1],"%Y")
  nMonth<-unique(buf$Month)
  for(mmm in 1:length(nMonth)){
    tmp<-subset(buf,buf$Month==nMonth[mmm])  
    tmp01<-tmp[which.max(tmp[,2]),]  
    tmp02<-tmp[which.min(tmp[,2]),]  
    tmp03<-rbind(tail(tmp01,1),tail(tmp02,1))  
    range<-round(tmp03[which.max(tmp03[,1]),][2]-tmp03[which.min(tmp03[,1]),][2],3)  
    tmpHistogram<-rbind(tmpHistogram,
      data.frame(
        Date=as.Date(paste(unique(year(tmp[,1])),"-",unique(month(tmp[,1])),"-1",sep="")),
        Range=range,
        MaxDate=tmp03[which.max(tmp03[,2]),][1,1],
        Max=tmp03[which.max(tmp03[,2]),][1,2],
        MinDate=tmp03[which.min(tmp03[,2]),][1,1],
        Min=tmp03[which.min(tmp03[,2]),][1,2]
      )
    )  
  }
  histgramMonth[[ddd]]<-tail(na.omit(tmpHistogram),histgramMonthTail)
  binWidth<-10^(floor(log10(range(histgramMonth[[ddd]][,2])[2]-range(histgramMonth[[ddd]][,2])[1]))-binWidthCalibration)
  histLeft<-floor((range(histgramMonth[[ddd]][,2])[1])/binWidth)*binWidth
  histright<-ceiling((range(histgramMonth[[ddd]][,2])[2])/binWidth)*binWidth
  histgramData<-NULL
  for(iii in 0:((histright-histLeft)/binWidth)){
    number<-nrow(subset(histgramMonth[[ddd]],
      histLeft+iii*binWidth<=histgramMonth[[ddd]][,2] & histgramMonth[[ddd]][,2]<histLeft+(iii+1)*binWidth)) 
    histgramData<-rbind(histgramData,data.frame(Bin=histLeft+iii*binWidth,Frequency=number))
  }
  histgramData$Ratio<-round(histgramData[,2]/sum(histgramData[,2])*100,2)
  setwd(dir.list)
  csvFile<-paste("1ヶ月の値幅.",colnames(histgramMonth[[ddd]])[2],".csv",sep="")    
  write.csv(histgramMonth[[ddd]],csvFile,row.names=F,append=F,quote=F,fileEncoding="UTF-8")
  csvFile<-paste("1ヶ月の値幅.頻度.割合.",colnames(histgramMonth[[ddd]])[2],".csv",sep="")    
  write.csv(histgramData,csvFile,row.names=F,append=F,quote=F,fileEncoding="UTF-8")
  #####chart part
  setwd(pathOutput)
  title<-paste("1ヶ月間の値幅:最高値-最低値\n",colnames(histgramMonth[[ddd]])[2],"\n",
    format(head(histgramMonth[[ddd]][,1],1),"%Y/%m"),"-",format(tail(histgramMonth[[ddd]][,1],1),"%Y/%m"))  
  #chart01
  ST<-Sys.time()  
  addVer<-gsub("\\.","",paste(year(SD),month(SD),day(SD),hour(ST),minute(ST),second(ST),sep=""))
  png.file<-paste(addVer,".png",sep="")
  png(file=png.file,width=1920,height=1080)
  par(ps=20,mar=c(5,10,10,3),cex.main=2,cex.lab=2,cex.axis=1.5,family="Meiryo") 
  hist(histgramMonth[[ddd]][,2],
    breaks=seq(histLeft,histright,binWidth),
    col="#0000ff40",freq=F,xlab="",main=paste(title,": bin幅=",binWidth))
  lines(density(histgramMonth[[ddd]][,2]),col="red",lwd=2)
  rug(histgramMonth[[ddd]][,2])
  dev.off()  
  #chart02
  ST<-Sys.time()  
  addVer<-gsub("\\.","",paste(year(SD),month(SD),day(SD),hour(ST),minute(ST),second(ST),sep=""))
  png.file<-paste(addVer,".png",sep="")
  png(file=png.file,width=1920,height=1080)
  par(ps=20,mar=c(5,10,10,3),cex.main=2,cex.lab=2,cex.axis=1.5,family="Meiryo") 
  ymin<-min(histgramMonth[[ddd]][,2])
  ymax<-(max(histgramMonth[[ddd]][,2])-ymin)/1.5+max(histgramMonth[[ddd]][,2])
  plot(histgramMonth[[ddd]][,1:2],type="h",main=title,ylim=c(ymin,ymax),col="#0000ff")
  addtable2plot(x=head(histgramMonth[[ddd]][,1],1),y=ymax,table=tail(histgramMonth[[ddd]],10),
      bty="o",hlines=T,vlines=T,yjust=-0.02)
  dev.off()
  #chart03
  ST<-Sys.time()  
  addVer<-gsub("\\.","",paste(year(SD),month(SD),day(SD),hour(ST),minute(ST),second(ST),sep=""))
  png.file<-paste(addVer,".png",sep="")
  png(file=png.file,width=1920,height=1080)
  par(oma=c(1,1,14,1),ps=20,mar=c(5,10,8,3),cex.main=1.5,cex.lab=1.5,cex.axis=1.5,family="Meiryo",mfrow=c(1,2)) 
  #left part
  qqnorm(histgramMonth[[ddd]][,2])
  qqline(histgramMonth[[ddd]][,2],col="red",lwd=2)
  #right part
  plot(ecdf(histgramMonth[[ddd]][,2]),main="ecdf")
  x<-seq(floor(min(histgramMonth[[ddd]][,2])),ceiling(max(histgramMonth[[ddd]][,2])),0.01)
  lines(x,pnorm(x,mean=mean(histgramMonth[[ddd]][,2]),sd=sqrt(var(histgramMonth[[ddd]][,2]))),col=2,lwd=2)
  title(paste(title,"\nShapiro-Wilk normality test. p value=",
    shapiro.test(histgramMonth[[ddd]][,2])$p.value),outer=TRUE,cex.main=2,family="Meiryo")
  dev.off()
  #chart04
  ST<-Sys.time()  
  addVer<-gsub("\\.","",paste(year(SD),month(SD),day(SD),hour(ST),minute(ST),second(ST),sep=""))
  png.file<-paste(addVer,".png",sep="")
  png(file=png.file,width=1920,height=1080)
  objectDate<-subset(buf,as.Date(paste(year(Sys.Date())-3,"-1-1",sep=""))<=buf[,1])
  colnames(objectDate)[2]<-"Index"
  meltDate<-melt(objectDate,id="Month",measure="Index")
  titleBP<-paste("ボックスプロット\n",colnames(histgramMonth[[ddd]])[2],"\n",head(meltDate[,1],1),"-",tail(meltDate[,1],1))  
  g<-ggplot(data=meltDate,aes(x=Month,y=value))
  g<-g+geom_boxplot(lwd=1)
  g<-g+theme(axis.text.x=element_text(size=30,angle=90,hjust=1,vjust=0.5,face="bold",family="Meiryo")) 
  g<-g+theme(axis.text.y=element_text(size=30,family="Meiryo")) 
  g<-g+theme(axis.title=element_text(size=30,face="bold")) 
  g<-g+theme(title=element_text(size=30,face="bold",family="Meiryo")) 
  g<-g+xlab("")
  g<-g+ylab("") 
  g<-g+scale_y_continuous(labels=comma)
  g<-g+ggtitle(paste(titleBP))
  print(g)
  dev.off()
  #chart05
  titleTS<-paste("時系列データ\n",colnames(buf)[2],"\n",
    format(head(buf[,1],1),"%Y/%m/%d"),"-",format(tail(buf[,1],1),"%Y/%m/%d"),
    "\n直近データ:",format(tail(buf[,1],1),"%Y/%m/%d"),"-",tail(buf[,2],1)
    )  
  ST<-Sys.time()  
  addVer<-gsub("\\.","",paste(year(SD),month(SD),day(SD),hour(ST),minute(ST),second(ST),sep=""))
  png.file<-paste(addVer,".png",sep="")
  png(file=png.file,width=1920,height=1080)
  g<-ggplot()
  g<-g+geom_line(data=buf,aes(x=Date,y=buf[,2]),size=2)
  g<-g+geom_smooth(data=buf,aes(x=Date,y=buf[,2]),method=lm)
  g<-g+geom_smooth(data=buf,aes(x=Date,y=buf[,2]),method=loess,color="red")
  g<-g+ggtitle(paste(titleTS))
  g<-g+xlab("") 
  g<-g+ylab("") 
  g<-g+theme(axis.text=element_text(size=30,face="bold",family="Meiryo"))          
  g<-g+theme(axis.title=element_text(size=30,face="bold",family="Meiryo"))          
  g<-g+theme(title=element_text(size=30,face="bold",family="Meiryo"))          
  g<-g+theme(legend.position="right")          
  g<-g+theme(legend.text=element_text(colour="black",size=40,face="bold",family="Meiryo"))          
  g<-g+theme(legend.title=element_text(colour="white",size=0,face="bold")) 
  g<-g+scale_x_date(labels=date_format("%Y/%m"))#当面日付タイプに係らず年-月とする
  g<-g+scale_y_continuous(labels=comma)
  print(g)
  dev.off() 
  #chart06
  ST<-Sys.time()  
  addVer<-gsub("\\.","",paste(year(SD),month(SD),day(SD),hour(ST),minute(ST),second(ST),sep=""))
  png.file<-paste(addVer,".png",sep="")
  png(file=png.file,width=1920,height=1080)
  par(oma=c(1,1,14,1),ps=20,mar=c(5,2,5,1),cex.main=1.5,cex.lab=1.5,cex.axis=1.0,family="Meiryo",mfrow=c(1,2)) 
  tmp<-subset(histgramData,histgramData[,2]!=0)
  dataOrder<-order(tmp[,2],decreasing=T)
  tmp<-tmp[dataOrder,]
  tmp[,1]<-ordered(tmp[,1],levels=tmp[,1][1:length(tmp[,1])])#Dateに適用するとNAに変換されるので注
  barplot(names.arg=tmp[,1],tmp[,2],horiz=F,las=2,main="Frequency",family="Meiryo",ylab="",xlab="",col="#0000ff40") 
  barplot(names.arg=tmp[,1],tmp[,3],horiz=F,las=2,main="Ratio(%)",family="Meiryo",ylab="",xlab="",col="#DF013A40") 
  title(paste(title,": bin幅=",binWidth),outer=TRUE,cex.main=2,family="Meiryo")
  dev.off()
  #####chart part
}
```