```{r}
requiredPackageList<-c(
  "ggplot2",
  "lubridate",
  "scales",
  "maps",
  "maptools",
  "RColorBrewer",
  "fields",
  "rworldmap",
  "classInt",
  "plotrix",
  "HH",
  "reshape",
  "quantmod",
  "lmtest",
  "forecast",
  "viridis",
  "tseries",
  "beepr",
  "knitr"
  )
notInstalledPackages<-requiredPackageList[!(requiredPackageList %in% installed.packages()[,"Package"])] 
#apply logical vector to requiredPackageList
if(length(notInstalledPackages)!=0){print(notInstalledPackages);install.packages(notInstalledPackages)}
lapply(requiredPackageList,require,character.only=T)
#Reference 
#http://stackoverflow.com/questions/4090169/elegant-way-to-check-for-missing-packages-and-install-them
#http://stackoverflow.com/questions/8175912/load-multiple-packages-at-once
username<-Sys.info()['user']
pathOutput<-paste("C:/Users/",username,"/Desktop/R_Data_Write/",sep="")
setwd(pathOutput)
windowsFonts(Meiryo=windowsFont("Meiryo"))
SD<-Sys.Date()
```

```{r}
##################################################### from FRED part ###########################################
fredData<-0
tsSource<-list()
dataset<-list()
tsSource[[1]]<-c(
  "FRED",
  1,
  "http://research.stlouisfed.org/",
  "DEXJPUS",
  "DJIA",
  "GOLDAMGBD228NLBM",
  "DCOILWTICO",
  "NIKKEI225",
  "DGS10"
)
for(lll in 1:length(tsSource)){
  for(iii in 4:length(tsSource[[lll]])){
    fredData<-fredData+1
    item<- tsSource[[lll]][iii]
    tmp<-getSymbols(item,src=tsSource[[lll]][1],auto.assign=FALSE)
    tmp<-tmp[,as.numeric(tsSource[[lll]][2])]
    dataset[[fredData]]<-data.frame(Date=index(tmp),tmp, row.names=NULL)
    if(tsSource[[lll]][iii]=="NIKKEI225"){colnames(dataset[[fredData]])[2] <- "日経平均株価"}
    if(tsSource[[lll]][iii]=="GOLDAMGBD228NLBM"){colnames(dataset[[fredData]])[2] <- "ゴールド価格(米ドル/トロイオンス)"}
    if(tsSource[[lll]][iii]=="DCOILWTICO"){colnames(dataset[[fredData]])[2] <- "WTI原油価格(クッシング,米ドル/バレル)"}
    if(tsSource[[lll]][iii]=="DJIA"){colnames(dataset[[fredData]])[2] <- "ダウ･ジョーンズ工業平均"}
    if(tsSource[[lll]][iii]=="DEXJPUS"){colnames(dataset[[fredData]])[2] <- "日本円-米ドル為替レート"}
    if(tsSource[[lll]][iii]=="DGS10"){colnames(dataset[[fredData]])[2] <- "10年物米国財務省証券金利(%)"}
    print(tail(dataset[[fredData]]))
  }
}
##################################################### from FRED part ###########################################
##################################################### JGB part #################################################
fredData<-fredData+1
url<-c(
 "http://www.mof.go.jp/english/jgbs/reference/interest_rate/historical/jgbcme_all.csv",
 "http://www.mof.go.jp/english/jgbs/reference/interest_rate/jgbcme.csv"
)
oldData<-read.csv(url[1],header=T,skip=1,stringsAsFactor=F,check.names=FALSE)
newData<-read.csv(url[2],header=T,skip=1,stringsAsFactor=F,check.names=FALSE)
colnames(oldData)
colnames(newData)
tmp01<-rbind(oldData,newData)
tmp01[,1]<-as.Date(tmp01[,1])
FUN.1<-function(x) as.numeric(x)
tmp01<-data.frame(tmp01[1],apply(tmp01[-1],2,FUN.1))
colnames(tmp01)<-gsub("Y","",colnames(tmp01))
colnames(tmp01)[2:length(tmp01)]<-paste("JGB.",gsub("X","",colnames(tmp01)[2:length(tmp01)]),"year",sep="")
colnames(tmp01)[1]<-"Date"
tmp01<-tmp01[,c(1,11)]#10年物のみを抽出
dataset[[fredData]]<-tmp01
colnames(dataset[[fredData]])[2] <- "10年物日本国債金利(%)"
head(dataset[[fredData]])
tail(dataset[[fredData]])
#日米金利差
tmpDGS10Data<-(dataset[[which(tsSource[[1]]=="DGS10")-3]])
tmpDiff<-na.omit(merge(dataset[[fredData]],tmpDGS10Data,all=T))
fredData<<-fredData+1
dataset[[fredData]]<-data.frame(tmpDiff[,1],tmpDiff[,3]-tmpDiff[,2])
colnames(dataset[[fredData]])<-c("Date","日米10年物国債金利差(%)")
fredData
#日米金利差
##################################################### JGB part #################################################
ST<-Sys.time()
```

```{r}
htmlFile<-"amcc_dailyIndicesAfterShinzoAbe.html"
cat("",file=htmlFile,append=F)
cat("
<html><head><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">
<meta http-equiv=\"Pragma\" content=\"no-cache\" />
<meta http-equiv=\"cache-control\" content=\"no-cache\" />
<meta http-equiv=\"expires\" content=\"0\" />
<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js\"></script>
<link href=\"http://cdn.datatables.net/1.10.11/css/jquery.dataTables.min.css\" rel=\"stylesheet\">
<script src=\"http://cdn.datatables.net/1.10.11/js/jquery.dataTables.min.js\"></script>
<style>
body{font-family:'Hiragino Kaku Gothic Pro','Meiryo UI',Verdana,sans-serif;}
table{width:100%;border-collapse:collapse;padding:0;border-spacing:1;margin-left:auto;margin-right:auto;font-size:100%;}
tr, td, th{white-space: nowrap;}
td.highlight{font-weight:plain;color:red;}
</style>
</head>
<body>",file=htmlFile,append=T)
cat(paste("<div align=\"right\">データ取得日時:",year(SD),"年",month(SD),"月",day(SD),"日",hour(ST),"時",minute(ST),"分",second(ST),"秒</div>"),
  file=htmlFile,append=T)
htmlFile<<-htmlFile
amchartsObj<<-c("NIKKEI225","DEXJPUS","DCOILWTICO")#,"DJIA","GOLDAMGBD228NLBM")
funAmcharts()
#kable part
kableData<-merge(amchartsAlldata,dataset[[fredData-1]],all=T)
kableData<-merge(kableData,dataset[[fredData-2]],all=T)
kableData[is.na(kableData)==T]<--9999
kableData<-subset(kableData,as.Date("2012-12-26")<=kableData[,1])  
kableData<-data.frame(kableData,Date=kableData[,1],check.names=F)
ST<-Sys.time();addVer<-gsub("\\.","",paste(year(SD),month(SD),day(SD),hour(ST),minute(ST),second(ST),sep=""))
tableID<-paste("amcc_",addVer,sep="")
table.argu<-paste("id=\"",tableID,"\" width=\"100%\" class=\"display compact\"",sep="")
cat(paste("<script type=\"text/javascript\" charset=\"utf-8\">
$(document).ready(function(){
$('#",tableID,"').dataTable({
\"lengthMenu\":[[10,-1],[10,\"All\"]],
\"order\":[[0,\"desc\"]],
\"searching\":true,
\"columnDefs\":[{\"width\":\"30%\",\"targets\":0}],
\"language\":{\"decimal\":\".\",\"thousands\":\",\"},
createdRow:function(row,data,index){\n",sep=""),file=htmlFile,append=T)
for(ccc in 1:ncol(kableData)){
  cat(paste("if ( data[",ccc-1,"].replace(',' , '') * 1 < 0 ) {\n",sep=""),file=htmlFile,append=T)
  cat(paste("$('td', row).eq(",ccc-1,").addClass('highlight');\n",sep=""),file=htmlFile,append=T)
  cat("}\n",file=htmlFile,append=T)
}
cat("}  
})});</script>\n\n",file=htmlFile,append=T)
cat("<div align=\"center\"><b>",colnames(dataset)[2],"</b></div>",file=htmlFile,append=T)
cat("<div style=\"overflow-x:scroll;\">\n",file=htmlFile,append=T)
cat(kable(kableData,'html',row.names=F,table.attr=table.argu,align=rep("r",ncol(kableData))),file=htmlFile,append=T)
cat("</div>\n",file=htmlFile,append=T)  
#kable part
cat("Powered By <br>amCharts - https://www.amcharts.com/<br>DataTables- https://datatables.net/",file=htmlFile,append=T)
cat("</body></html>",file=htmlFile,append=T)
beep(3)
```

```{r}
#amchartsPart
funAmcharts<-function(){
for(nnn in 1:length(amchartsObj)){
  tmp<-dataset[[which(tsSource[[1]]==amchartsObj[nnn])-3]]
  if(nnn==1){amchartsAlldata<-tmp}else{
  amchartsAlldata<-merge(amchartsAlldata,tmp,all=T)
  }  
}
amchartsAlldata<-merge(amchartsAlldata,dataset[[fredData-0]],all=T)
amchartsAlldata<<-amchartsAlldata
forAmcahrts<-na.omit(amchartsAlldata)
forAmcahrts<-subset(forAmcahrts,as.Date("2012-12-26")<=forAmcahrts[,1])  
forAmcahrts<-data.frame(Date=forAmcahrts[,1],apply(forAmcahrts[,-1,drop=F],2,function(x) x/head(x,1)))
colnames(forAmcahrts)<-colnames(amchartsAlldata)
head(forAmcahrts)
tail(forAmcahrts)
forAmcahrts<-head(forAmcahrts,nrow(forAmcahrts))
cat(paste("
<div style=\"text-align:center\"><b>第二次安倍政権発足以降の各種指標 - 2012年12月27日を1とする</b></div>
<script src=\"http://archive.am-consulting.co.jp/amcharts315/amcharts.js\"></script>
<script src=\"http://archive.am-consulting.co.jp/amcharts315/serial.js\"></script>
<script src=\"http://archive.am-consulting.co.jp/amcharts315/themes/light.js\"></script>
<style>#chartdiv{width:100%;height:800px;font-size:11px;}</style>
<div id=\"chartdiv\"></div>
<script>var chart = AmCharts.makeChart(\"chartdiv\",{
\"type\":  \"serial\",
\"theme\": \"light\",
\"marginRight\": 80,
\"autoMarginOffset\": 20,
\"dataDateFormat\": \"YYYY-MM-DD\",
\"valueAxes\": [{\"id\": \"v1\",\"axisAlpha\": 0,\"position\": \"left\"}],
\"balloon\": {\"maxWidth\":1000,\"borderThickness\": 1,\"shadowAlpha\": 0},
\"graphs\": [",sep=""),file=htmlFile,append=T)
for(ccc in 2:ncol(forAmcahrts)){
  cat(paste("
  { 
  \"id\": \"g",ccc,"\", 
  \"bullet\": \"round\", 
  \"bulletBorderAlpha\": 1, 
  \"bulletColor\": \"#FFFFFF\", 
  \"bulletSize\": 5, 
  \"hideBulletsCount\": 50, 
  \"lineThickness\": 2, 
  \"title\": \"red line\", 
  \"useLineColorForBulletBorder\": true,
  \"valueField\": \"value",ccc,"\", 
  \"balloonText\": \"<div style='margin:5px; font-size:19px;'><span style='font-size:13px;'>",colnames(forAmcahrts)[ccc],"</span> - [[value]]</div>\"
  }",sep=""),file=htmlFile,append=T) 
  if(ccc!=length(forAmcahrts)){cat(",",file=htmlFile,append=T)} 
}
cat(paste("
],
\"mouseWheelZoomEnabled\": true,
\"chartScrollbar\": {
\"scrollbarHeight\":2,
\"offset\":-1,
\"backgroundAlpha\":0.1,
\"backgroundColor\":\"#888888\",
\"selectedBackgroundColor\":\"#67b7dc\",
\"selectedBackgroundAlpha\":1
},
\"chartCursor\": {
/*  
\"pan\": true,
\"valueLineEnabled\": true,
\"valueLineBalloonEnabled\": true,
\"cursorAlpha\":0,
\"valueLineAlpha\":0.2
*/  
},
\"categoryField\": \"date\",
\"categoryAxis\": {
\"parseDates\": true,
\"dashLength\": 1,
\"minorGridEnabled\": true
},
\"export\": {
\"enabled\": true
},
\"dataProvider\": [\n",sep=""),file=htmlFile,append=T)
for(rrr in 1:nrow(forAmcahrts)){
  cat(paste("{\"date\": \"",forAmcahrts[rrr,1],"\",",sep=""),file=htmlFile,append=T)
  for(ccc in 2:ncol(forAmcahrts)){
    cat(paste("\"value",ccc,"\":",round(forAmcahrts[rrr,ccc],3),sep=""),file=htmlFile,append=T)
    if(ccc!=ncol(forAmcahrts)){cat(",",file=htmlFile,append=T)}
  }
  cat("}",file=htmlFile,append=T)
  if(rrr!=nrow(forAmcahrts)){cat(",\n",file=htmlFile,append=T)}
}
cat(paste("
]
});
chart.addListener(\"rendered\", zoomChart);
zoomChart();
function zoomChart() {
chart.zoomToIndexes(chart.dataProvider.length - ",nrow(forAmcahrts),", chart.dataProvider.length - 0);
}
</script>\n",sep=""),file=htmlFile,append=T)
}  
#amchartsPart
```