```{r}
library(lubridate)
username<-Sys.info()['user']
pathOutput<-paste("C:/Users/",username,"/Desktop/charts/",sep="")
SD<-Sys.Date()
windowsFonts(Meiryo=windowsFont("Meiryo"))
fun.readData<-function(){
  dataset<-read.table("clipboard",header=TRUE,sep="\t",stringsAsFactor=F)
  dataset<<-dataset # caution
  print(head(dataset))
  print(tail(dataset))
}
```

```{r}
fun.readData()#dataset<-dataset[order(dataset[,2],decreasing=T),]
```

```{r}
setwd(pathOutput)
ST<-Sys.time()  
addVer<-gsub("\\.","",paste(year(SD),month(SD),day(SD),hour(ST),minute(ST),second(ST),sep=""))
csvFile<-paste(addVer,".csv",sep="")    
write.csv(dataset,csvFile,col.names=T,row.names=F,append=F,quote=F,fileEncoding="UTF-8")
```

```{r}
tailNumber<-200
plotType<-2 #1:line , 2:bar
overallTitle<-"住民基本台帳人口移動報告 平成27年2月 年齢別転入超過数(データ出所：総務省統計局)"
orderColumn<-1
orderDirection<-"desc" #asc
dateFormat<-1 #1:as is , 2:scientific , 3:monthly , 4:dayly , 5:yearly
columnWidth<-"{\"width\":\"10%\",\"targets\":0}"
dateFormatType<-"%Y/%m"
setwd(pathOutput)
col<-list()
grandData<-NULL
header<-NULL
ST<-Sys.time()  
addVer<-gsub("\\.","",paste(year(SD),month(SD),day(SD),hour(ST),minute(ST),second(ST),sep=""))
htmlFile<-paste(addVer,".html",sep="")
mfrowTYpe<-c(2,ceiling((ncol(dataset)-1)/2))
png.file<-paste(addVer,".png",sep="")
png(file=png.file,width=1400,height=900)
par(oma=c(1,1,7,1),mfrow=mfrowTYpe,ps=20,mar=c(12,5,5,5),cex.main=1.0,cex.lab=1,cex.axis=0.8)
cat("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js\"></script>",file=htmlFile,append=F)
cat("<link href=\"http://code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css\" rel=\"stylesheet\">",file=htmlFile,append=T)
cat("<link href=\"http://cdn.datatables.net/plug-ins/f2c75b7247b/integration/jqueryui/dataTables.jqueryui.css\" rel=\"stylesheet\">",file=htmlFile,append=T) 
cat("<script src=\"http://cdn.datatables.net/1.10.5/js/jquery.dataTables.min.js\"></script>",file=htmlFile,append=T) 
cat("<script src=\"http://cdn.datatables.net/plug-ins/f2c75b7247b/integration/jqueryui/dataTables.jqueryui.js\"></script>",file=htmlFile,append=T)  
cat("<script type=\"text/javascript\" charset=\"utf-8\">$(document).ready( function(){",file=htmlFile,append=T)
cat("$('#am-consulting').dataTable( {",file=htmlFile,append=T)
cat("\"lengthMenu\": [[20,-1,100,200], [20,\"All\",100,200]],",file=htmlFile,append=T)
cat("\"order\": [[ ",orderColumn,", \"" ,orderDirection,"\" ]],",file=htmlFile,append=T)
cat("\"searching\": true,",file=htmlFile,append=T)
cat("\"columnDefs\":[",columnWidth,"],",file=htmlFile,append=T)
cat("\"language\": {\"decimal\": \".\",\"thousands\": \",\"}",file=htmlFile,append=T)
cat("});",file=htmlFile,append=T)
cat("});</script>",file=htmlFile,append=T)
if(colnames(dataset[1])!="Date"){
  dataset[,1]<-ordered(dataset[,1],levels=dataset[,1][1:length(dataset[,1])])
}
for(ccc in 1:ncol(dataset)){
  if(ccc==1){
    switch(dateFormat,
    col[[ccc]]<-paste("<td align=\"right\" valign=\"middle\">",dataset[,ccc],"</td>",sep=""),
    col[[ccc]]<-paste("<td align=\"right\" valign=\"middle\">",format(dataset[,ccc],big.mark=",",scientific=F),"</td>",sep=""),
    col[[ccc]]<-paste("<td align=\"right\" valign=\"middle\">",format(as.Date(dataset[,ccc]),"%Y/%m"),"</td>",sep=""),
    col[[ccc]]<-paste("<td align=\"right\" valign=\"middle\">",format(as.Date(dataset[,ccc]),"%Y/%m/%d"),"</td>",sep=""),
    col[[ccc]]<-paste("<td align=\"right\" valign=\"middle\">",format(as.Date(dataset[,ccc]),"%Y"),"</td>",sep="")
    )
  }else{  
    col[[ccc]]<-paste("<td align=\"right\" valign=\"middle\">",format(dataset[,ccc],big.mark=",",scientific=F),"</td>",sep="")
    #plot part
    tmp<-tail(dataset,tailNumber)
    if(3<=dateFormat){
      plotX<-as.Date(tmp[,1])
      mainTitle<-paste(colnames(tmp)[ccc],"\n期間:",
        format(as.Date(head(tmp[,1],1)),dateFormatType),"-",format(as.Date(tail(tmp[,1],1)),dateFormatType))
    }else{
      plotX<-tmp[,1]
      mainTitle<-paste(colnames(tmp)[ccc],"\n期間:",head(tmp[,1],1),"-",tail(tmp[,1],1))
    }
    if(plotType==1){
      plot(plotX,tmp[,ccc],type="l",main=mainTitle,family="Meiryo",ylab="",xlab="")
    }else{
      barplot(names.arg=tmp[,1],tmp[,ccc],horiz=F,las=2,main=mainTitle,family="Meiryo",ylab="",xlab="",col="blue",yaxt="n") 
      axis(side=2,at=axTicks(2),labels=formatC(axTicks(2), format="d", big.mark=','),las=2)
    }  
    #plot part
  }  
  grandData<-cbind(grandData,col[[ccc]])
  header<-paste(header,"<th>",colnames(dataset)[ccc],"</th>",sep="")  
}
title(overallTitle,outer=TRUE,cex.main=1.5,family="Meiryo")
dev.off()
tableHtml<-"<table cellpadding=\"0\" cellspacing=\"0\" id=\"am-consulting\" width=\"100%\" class=\"display\"><thead>"
tableHtml<-paste(tableHtml,header,"</thead>",sep="")
cat(tableHtml,file=htmlFile,append=T)
grandData<-data.frame("<tr>",grandData,"</tr>",row.names=NULL)
write.table(grandData,htmlFile,quote=F,col.names=F, append=T,row.names=F)
cat("</table>",file=htmlFile,append=T)
cat("Powered by DataTables( http://datatables.net/ )",file=htmlFile,append=T)
```

```{r}
overallTitle<-"日本の完全失業率(データ出所：総務省統計局)"
setwd(pathOutput)
cols<-c("red","black","blue")
ltys<-c(1,1,1)
labels<-c("1989年4月消費税導入前後4年間","1997年4月消費税増税前後4年間","2014年4月消費税増税前後4年間")
changePoint<-as.Date(c("1989/4/1","1997/4/1","2014/4/1"))
data<-list()
interval<-24
dataset[,1]<-as.Date(dataset[,1])  
ST<-Sys.time()  
addVer<-gsub("\\.","",paste(year(SD),month(SD),day(SD),hour(ST),minute(ST),second(ST),sep=""))
png.file<-paste(addVer,".png",sep="")
png(file=png.file,width=1400,height=900)
mfrowTYpe<-c(2,ceiling((ncol(dataset)-1)/2))
par(oma=c(1,1,7,1),mfrow=mfrowTYpe,ps=20,mar=c(3,3,5,3),cex.main=1.2,cex.lab=1,cex.axis=1.0,family="Meiryo")  
for(ccc in 2:ncol(dataset)){
  plot(0,0,type="n",xlim=c(-interval,interval),ylim=c(min(dataset[,ccc]),max(dataset[,ccc])),xlab="",ylab="",main=colnames(dataset)[ccc])
  tmp<-dataset[,c(1,ccc)]
  for(mmm in 1:length(changePoint)){
    data[[mmm]]<-subset(tmp,(changePoint[mmm]-months(interval))<=tmp[,1] & tmp[,1]<=(changePoint[mmm]+months(interval)))
    start<-nrow(subset(data[[mmm]],data[[mmm]][,1]<changePoint[mmm]))
    end<-nrow(subset(data[[mmm]],data[[mmm]][,1]>changePoint[mmm]))
    data[[mmm]]$monthID<-rep(-start:end,length=nrow(data[[mmm]]))
    points(data[[mmm]][,3],data[[mmm]][,2],col=cols[mmm])
    lines(data[[mmm]][,3],data[[mmm]][,2],type="l",col=cols[mmm])
    text(data[[mmm]][,3],data[[mmm]][,2],labels=paste(data[[mmm]][,2],sep=""),srt=90,cex=0.6,adj=0,col=cols[mmm],family="Meiryo")
  }
  legend("topleft",legend=labels,col=cols,lty=ltys)
}
title(overallTitle,outer=TRUE,cex.main=1.5,family="Meiryo")
dev.off()
```
