```{r}
requiredPackageList<-c("quantmod","PerformanceAnalytics","lubridate","ggplot2")
colnames(installed.packages())
notInstalledPackages<-requiredPackageList[!(requiredPackageList %in% installed.packages()[,"Package"])] #apply logical vector to requiredPackageList
if(length(notInstalledPackages)!=0){print(notInstalledPackages);install.packages(notInstalledPackages)}
lapply(requiredPackageList,require,character.only=T)
#Reference 
#http://stackoverflow.com/questions/4090169/elegant-way-to-check-for-missing-packages-and-install-them
#http://stackoverflow.com/questions/8175912/load-multiple-packages-at-once
username<-Sys.info()['user']
pathOutput<-paste("C:/Users/",username,"/Desktop/charts/",sep="")
SD<-Sys.Date()
windowsFonts(Meiryo=windowsFont("Meiryo"))
setwd(pathOutput)
```

```{r}
ts.source<-list()
dataset<-list()
reference<-list()
lineColor<-list()
allData<-xts()
ts.source[[1]]<-c("FRED",1,"http://research.stlouisfed.org/","DCOILWTICO")
ts.source[[2]]<-c("FRED",1,"http://research.stlouisfed.org/","DEXJPUS","DEXUSEU","DEXUSUK","DEXBZUS")
ts.source[[3]]<-c("FRED",1,"http://research.stlouisfed.org/","DEXSZUS","DEXKOUS","DEXMXUS")
ts.source[[4]]<-c("FRED",1,"http://research.stlouisfed.org/","DEXINUS","DEXTHUS","DEXHKUS","DEXSIUS","DEXMAUS","DEXSDUS")
ts.source[[5]]<-c("FRED",1,"http://research.stlouisfed.org/","DEXUSAL","DEXUSNZ","DEXCAUS","DEXSFUS","DEXNOUS","DEXDNUS")
cnt<-0
for(lll in 1:length(ts.source)){
  for(iii in 4:length(ts.source[[lll]])){
    cnt<-cnt+1
    if(ts.source[[lll]][1]=="oanda"){
      if(ts.source[[lll]][iii]=="JPY" | ts.source[[lll]][iii]=="CHF" | ts.source[[lll]][iii]=="ZAR" | ts.source[[lll]][iii]=="KRW"){
        item<-paste("USD/",ts.source[[lll]][iii],sep="")
      }else{
        item<-paste(ts.source[[lll]][iii],"/USD",sep="")
      }
    }
    else{
      item<- ts.source[[lll]][iii]
    }
    dataset[[cnt]]<-getSymbols(item,src=ts.source[[lll]][1],auto.assign=FALSE)
    dataset[[cnt]]<-dataset[[cnt]][,as.double(ts.source[[lll]][2])]
    allData<-merge(allData,dataset[[cnt]])
    reference[[cnt]]<-ts.source[[lll]][3]
    if(lll==1){lineColor[[cnt]]<-"red"}else if(lll==5){lineColor[[cnt]]<-"blue"}else{lineColor[[cnt]]<-"black"}
  }
}
```

```{r}
setwd(pathOutput)
data<-list()
ST<-Sys.time()  
addVer<-gsub("\\.","",paste(year(SD),month(SD),day(SD),hour(ST),minute(ST),second(ST),sep=""))
png.file<-paste(addVer,".png",sep="")
png(file=png.file,width=1920,height=1080)
par(oma=c(16,2,6,2),mfrow=c(4,5),family="Meiryo")
for(ddd in 1:cnt){
  data[[ddd]]<-na.omit(dataset[[ddd]])
  if(ddd!=1){linecol="black"}else{linecol="red"}
  chart.TimeSeries(data[[ddd]][,1],main=colnames(data[[ddd]])[1],date.format="%Y/%m/%d",
    ylab="",lwd=2,cex.legend=3,cex.axis=2,cex.lab=2,cex.main=3,col=lineColor[[ddd]])
}
mtext("\nWTI原油価格(米ドル/バレル)と米ドルストレートレート",side=3,line=1,cex=4,outer=TRUE)
mtext("D:Daily,COILWTICO:Crude Oil Prices WTI Cushing,Oklahoma\nEX:Exchange Rate,US:U.S.Dollar,JP:Japanese Yen,EU:Euro,CH:Chinese Yuan,UK:British Pound,CA:Canadian Dollar,BZ:Brazilian Real,\nMX:Mexican New Pesso,AL:Australian Dollar,KO:South Korean Won,SZ:Swiss Franc,IN:Indian Rupee,TH:Thai Baht,TA:New Taiwan Dollar,\nSF:South African Rand,NZ:New Zealand Dollar,HK:Hong Kong Dollar,SI:Singapore Dollar,SD:Swedish Kroner,NO:Norwegian Kroner,\nMA:Malaysian Ringgit,DN:Danish Kroner",side=1,line=15,cex=2,adj=0,outer=TRUE)
dev.off()
```

```{r}
setwd(pathOutput)
lagN<-300
rankData<-list()
buf<-list()
for(ccc in 1:3){
  minValue<-10^10
  maxValue<--1*10^10
  ST<-Sys.time()  
  addVer<-gsub("\\.","",paste(year(SD),month(SD),day(SD),hour(ST),minute(ST),second(ST),sep=""))
  png.file<-paste(addVer,".png",sep="")
  png(file=png.file,width=1920,height=1080)
  par(oma=c(2,2,15,2),mfrow=c(4,5),mar=c(4,5,9,5),family="Meiryo",ps=20,cex.axis=1,cex.lab=1,cex.main=1,cex.sub=1)
  switch(ccc,
    subtitle<-"1stDifference\n",
    subtitle<-"Rank of 1stDifference\n",
    subtitle<-"Original\n"
  )
  for(ddd in 1:cnt){
    tmp<-diff(data[[ddd]])#冗長要修正
    rankData[[ddd]]<-merge.xts(tmp,rank=rank(as.vector(tmp[,1]),na.last="keep"))
    colnames(rankData[[ddd]])[2]<-paste(colnames(rankData[[ddd]])[1],".rank",sep="")
    buf[[ddd]]<-na.omit(merge.xts(rankData[[ddd]],rankData[[1]],data[[ddd]],data[[1]]))
    if(ccc!=3){
      explanation<-as.vector(buf[[ddd]][,ccc])
      objective<-as.vector(buf[[ddd]][,ccc+2])  
    }else{
      explanation<-as.vector(buf[[ddd]][,5])
      objective<-as.vector(buf[[ddd]][,6])  
    }  
    print(tail(buf[[ddd]]))  
    resultCCF<-ccf(x=explanation,y=objective,lag.max=lagN,plot=F)
    acf<-resultCCF$acf[,,1]
    lag<-resultCCF$lag[,,1]
    resultDF<-data.frame(acf,lag)
    resultMax<-resultDF[which.max(abs(resultDF$acf)),]
    if(3<=ddd){
      if(abs(maxValue)<abs(resultMax[1])){maxValue<-resultMax[1];maxItem<-colnames(buf[[ddd]])[1];maxLag<-resultMax[2]}
    }else if(ddd==2){
      maxValue<-abs(resultMax[1]);maxItem<-colnames(buf[[ddd]])[1];maxLag<-resultMax[2] 
    }  
    ccf(x=explanation,y=objective,lag.max=lagN,lwd="2",col=lineColor[[ddd]],
      main=paste(
        colnames(buf[[ddd]])[1],
        "\nMax:lag=",resultMax[2],
        ",ACF=",resultMax[1],
        format(first(index(buf[[ddd]])),"%Y/%m/%d"),
        "-",
        format(last(index(buf[[ddd]])),"%Y/%m/%d"))
    )
  }
  mtext(paste("\nWTI原油価格(米ドル/バレル)と米ドルストレートレートの相互相関\n",subtitle,
    "Max of ACF:",maxItem,",ACF=",maxValue,",Lag=",maxLag,sep=""),
    side=3,line=0,cex=1.5,outer=TRUE)
  dev.off()
}
```

```{r}
lagwidth<-30
cor.fun=function(x){cor(x)[1,2]}
for(ccc in 1:3){
ST<-Sys.time()  
addVer<-gsub("\\.","",paste(year(SD),month(SD),day(SD),hour(ST),minute(ST),second(ST),sep=""))
png.file<-paste(addVer,".png",sep="")
png(file=png.file,width=1920,height=1080)
par(oma=c(2,2,13,2),mfrow=c(4,5),mar=c(3,5,5,5),family="Meiryo",ps=20,cex.axis=1,cex.lab=1,cex.main=1,cex.sub=1)
switch(ccc,
  subtitle<-paste("1stDifference\nローリング幅:",lagwidth),
  subtitle<-paste("Rank of 1stDifference\nローリング幅:",lagwidth),
  subtitle<-paste("Original\nローリング幅:",lagwidth)
)
  for(ddd in 1:cnt){
    if(ccc!=3){
      explanation<-buf[[ddd]][,ccc]
      objective<-buf[[ddd]][,ccc+2]
    }else{
      explanation<-buf[[ddd]][,5]
      objective<-buf[[ddd]][,6]
    }  
    rolldf<-data.frame(explanation,objective)
    correlation<-rollapply(rolldf,FUN=cor.fun,width=lagwidth,by.column=F,align="right")
    corrDF<-data.frame(Date=tail(index(buf[[ddd]]),length(correlation)),correlation)
    print(length(correlation)-nrow(rolldf))
    result<-corrDF[which.max(abs(corrDF[,2])),]
    title<-paste(colnames(buf[[ddd]])[1],"to",colnames(buf[[ddd]])[3])
    chartTitle<-paste(title,"\n",format(result[1],"%Y/%m/%d"),",",result[2])
    if(ccc!=3){
    chart.RollingCorrelation(buf[[ddd]][,ccc],buf[[ddd]][,ccc+2],width=lagwidth,type="h",cex.main=1,main=chartTitle,col=lineColor[[ddd]])
    }else{
    chart.RollingCorrelation(buf[[ddd]][,5],buf[[ddd]][,6],width=lagwidth,type="h",cex.main=1,main=chartTitle,col=lineColor[[ddd]])
    }  
  }
  mtext(paste("\nWTI原油価格(米ドル/バレル)と米ドルストレートレートのローリング回帰\n",subtitle,sep=""),
    side=3,line=0,cex=1.5,outer=TRUE)
  dev.off()
}
```
