```{r}
library(ggplot2)
library(PerformanceAnalytics)
library(lubridate)
library(reshape2)
library(scales)
windowsFonts(Meiryo=windowsFont("Meiryo"))
dataset<-list()
url<-list()
file.name<-c("d41ma","d51ma","d61ma")#51輸出,61輸入
base.url<-"http://www.customs.go.jp/toukei/suii/html/data/"
iii<-1
iii<-2
iii<-3
for(iii in 1:length(file.name)){
  url[[iii]]<-paste(base.url,file.name[iii],".csv",sep="")
  if(grepl("d41ma.csv",url[[iii]])==T){
    dataset[[iii]]<-read.csv(url[[iii]],header=F,skip=0,stringsAsFactor=F)
    colnames(dataset[[iii]])<-c("Date",dataset[[iii]][3,2],dataset[[iii]][3,3])
    colnames(dataset[[iii]])<-gsub("-",".",colnames(dataset[[iii]]))
    dataset[[iii]]<-dataset[[iii]][-c(1:4),]
    dataset[[iii]][,1]<-gsub("/","-",dataset[[iii]][,1])
    dataset[[iii]][,1]<-paste(dataset[[iii]][,1],"-01",sep="")
    FUN.1<-function(x){as.numeric(x)/(10^9)} #オリジナルの単位は千円、兆円に変換
    dataset[[iii]]<-cbind(dataset[[iii]][1],apply(dataset[[iii]][-1],2,FUN.1))
  }else if(grepl("d51ma.csv",url[[iii]])==T || grepl("d61ma.csv",url[[iii]])==T){
    tmp.data<-read.csv(url[[iii]],header=F,skip=0,stringsAsFactor=F)
    tmp.data[3,]<-gsub("．","",tmp.data[3,])
    tmp.data[3,]<-gsub("１","",tmp.data[3,])
    tmp.data[3,]<-gsub("２","",tmp.data[3,])
    tmp.data[3,]<-gsub("３","",tmp.data[3,])
    tmp.data[3,]<-gsub("４","",tmp.data[3,])
    tmp.data[3,]<-gsub("５","",tmp.data[3,])
    tmp.data[3,]<-gsub("６","",tmp.data[3,])
    tmp.data[3,]<-gsub("７","",tmp.data[3,])
    tmp.data[3,]<-gsub("８","",tmp.data[3,])
    tmp.data[3,]<-gsub("９","",tmp.data[3,])
    tmp.data[3,]<-gsub("([.-])|[[:punct:]]","",tmp.data[3,])
    tmp.data[4,]<-gsub("([.-])|[[:punct:]]","",tmp.data[4,])
    tmp.name<-""
    for(ccc in 2:length(tmp.data)){
      if(tmp.data[3,ccc]!=tmp.data[4,ccc]){
        if(tmp.data[3,ccc]=="" && tmp.data[4,ccc]!=""){
          tmp.name<-c(tmp.name,tmp.data[4,ccc])
        }else if(tmp.data[3,ccc]!="" && tmp.data[4,ccc]==""){
          tmp.name<-c(tmp.name,tmp.data[3,ccc])
        }else{
          tmp.name<-c(tmp.name,paste(tmp.data[3,ccc],".",tmp.data[4,ccc],sep=""))
        }
      }else{
        tmp.name<-c(tmp.name,tmp.data[3,ccc])
      }      
    }
    tmp.name<-tmp.name[tmp.name!=""]
    tmp.name
    tmp.logical<-tmp.data[6,]=="金額"  
    tmp.value<-tmp.data[,tmp.logical==TRUE]
    tmp.value<-tmp.value[-c(1:7),]
    tmp.date<-gsub("/","-",tmp.data[,1])
    tmp.date<-paste(tmp.date,"-01",sep="")
    tmp.date<-tmp.date[-c(1:7)]
    tmp.data<-cbind(date=tmp.date,tmp.value)
    colnames(tmp.data)<-c("date",tmp.name)
    dataset[[iii]]<-tmp.data
    FUN.1<-function(x){as.numeric(x)/(10^5)} #オリジナルの単位は千円、億円に変換
    dataset[[iii]]<-cbind(dataset[[iii]][1],apply(dataset[[iii]][-1],2,FUN.1))
  }
  dataset[[iii]][,1]<-as.Date(dataset[[iii]][,1])
########## 全系列ともゼロ値またはNAの行を削除(オリジナルデータは最新年の12月分まで枠が生成されている ##########
  FUN.2<-function(x){all(x!=0)}
  rowNotZero<-apply(dataset[[iii]][,-1],1,FUN.2)
  dataset[[iii]]<-dataset[[iii]][rowNotZero,]
  dataset[[iii]]<-na.omit(dataset[[iii]])
########## 全系列ともゼロ値またはNAの行を削除(オリジナルデータは最新年の12月分まで枠が生成されている ##########
}
username<-Sys.info()['user']
path<-paste("C:/Users/",username,"/Desktop/charts/",sep="")
```

```{r}
setwd(path)
imageWidth<-1600
imageHeight<-1000
###################### tschart part
lineColor<-c("blue","red")
dataSource<-" データ出所:財務省"
SD<-Sys.Date()
ST<-Sys.time()  
addVer<-gsub("\\.","",paste(year(SD),month(SD),day(SD),hour(ST),minute(ST),second(ST),sep=""))
png.file<-paste(addVer,".png",sep="")
png(file=png.file,width=imageWidth,height=imageHeight)
date.f<-format(dataset[[1]][1,1],"%Y/%m")  
date.e<-format(dataset[[1]][nrow(dataset[[1]]),1],"%Y/%m")
meltDataset<-melt(dataset[[1]],id="Date")
maxValue=max(max(dataset[[1]][,2]),max(dataset[[1]][,3]))
minValue=min(min(dataset[[1]][,2]),min(dataset[[1]][,3]))
g<-ggplot()
g<-g+geom_line(data=meltDataset,aes(x=Date,y=value,color=variable),size=0.7)
g<-g+scale_colour_manual("財務省貿易統計",values=lineColor)
g<-g+scale_y_continuous(labels=comma,limits=c(minValue,(maxValue-minValue)/5+maxValue))
g<-g+geom_smooth(data=dataset[[1]],aes(x=Date,y=dataset[[1]][,2]),method=loess,color=lineColor[1],size=2,linetype="dashed")
g<-g+geom_smooth(data=dataset[[1]],aes(x=Date,y=dataset[[1]][,3]),method=loess,color=lineColor[2],size=2,linetype="dashed")
g<-g+scale_x_date(labels=date_format("%Y/%m"))
g<-g+ggtitle(paste("財務省貿易統計(単位:兆円) 期間:",date.f,"-",date.e,dataSource))
g<-g+xlab("") 
g<-g+ylab("") 
g<-g+theme(axis.text=element_text(size=30,face="bold",family="Meiryo"))          
g<-g+theme(axis.title=element_text(size=30,face="bold",family="Meiryo"))          
g<-g+theme(title=element_text(size=30,face="bold",family="Meiryo"))          
g<-g+theme(legend.position="top")          
g<-g+theme(legend.text=element_text(colour="black",size=30,face="bold",family="Meiryo"))          
g<-g+theme(legend.title=element_text(colour="white",size=0,face="bold")) 
dateFormat<-"%Y/%m"
tmp.dataset<<-dataset[[1]]  
firstDate<<-format(as.Date(first(tmp.dataset[,1])),dateFormat)  
latestDate<<-format(as.Date(last(tmp.dataset[,1])),dateFormat)
plotText<-paste("Period:",firstDate,"-",latestDate)
for(ccc in 2:3){
subsetDataset<-subset(tmp.dataset,max(tmp.dataset[,ccc])==tmp.dataset[,ccc])  
maxDate<<-paste((format(subsetDataset[,1],dateFormat)),collapse=",")
maxValue<<-max(tmp.dataset[,ccc])
subsetDataset<-subset(tmp.dataset,min(tmp.dataset[,ccc])==tmp.dataset[,ccc])  
minDate<<-paste((format(subsetDataset[,1],dateFormat)),collapse=",")
minValue<<-min(tmp.dataset[,ccc])
latestValue<<-last(tmp.dataset[,ccc])
plotText<<-paste(
  plotText,
  "\nData:",colnames(tmp.dataset)[ccc],
  "\nHighest",maxDate,":",maxValue,
  "\nLowest",minDate,":",minValue,
  "\nLatest",latestDate,":",latestValue,
  "\n"
) 
}
g<-g+annotate("text",x=dataset[[1]][1,1],y=(maxValue-minValue)/5.5+maxValue,label=plotText,size=10,family="Meiryo",hjust=0,vjust=0.9,col="black")
print(g)
dev.off()
###################### tschart part
###################### table part
data<-list()
extractDate<-list()
cnt<-0
for(iii in 2:3){
  for(yyy in c(year(SD),year(SD)-5,year(SD)-10)){
    cnt<-cnt+1
    extractDate[[cnt]]<-as.Date(paste(yyy,"-",month(tail(dataset[[iii]][,1],1)),"-1",sep=""))
    buf<-subset(dataset[[iii]],dataset[[iii]][,1]==extractDate[[cnt]])
  #  r.dataset<-dataset[[iii]][nrow(dataset[[iii]]),c(3:ncol(dataset[[iii]]))]#日付と総額を除去、直近月のみ抽出
    r.dataset<-buf[,c(3:ncol(buf))]#日付と総額を除去、直近月のみ抽出
    r.dataset[1,]<-round(r.dataset[1,])
    r.dataset<-t(r.dataset)
    r.dataset<-data.frame(Item=rownames(r.dataset),r.dataset,row.names=NULL)
    rrr<-order(r.dataset[,2],decreasing=F)
    r.dataset<-r.dataset[rrr,]
    rownames(r.dataset)<-c(1:nrow(r.dataset))
    r.dataset[,1]<-ordered(r.dataset[,1],levels=r.dataset[,1][1:length(r.dataset[,1])])
    r.dataset[,3]<-as.numeric(format(r.dataset[,2]/max(r.dataset[,2])*100,digits=2))
    colnames(r.dataset)[3]<-"Maxas100"
    colnames(r.dataset)[2]<-"Value"
    data[[cnt]]<-r.dataset[,c(3,2,1)]
  }
}
#以降、冗長に過ぎるため要改良
mainTitle<-paste("財務省貿易統計:品目別輸出額:億円:",format(extractDate[[1]],"%Y/%m"),sep="")
g1<-ggplot()
g1<-g1+geom_bar(data=data[[1]],aes(x=Item,y=Value),stat="identity",position="identity",fill="blue",alpha=0.2)
g1<-g1+geom_text(data=data[[1]],aes(x=Item,y=Value,label=Value),hjust=0,size=5,family="Meiryo")
g1<-g1+theme(plot.title=element_text(size=30,family="Meiryo"))
g1<-g1+theme(axis.title.x=element_text(size=30,family="Meiryo")) 
g1<-g1+theme(axis.title.y=element_text(size=30,family="Meiryo")) 
g1<-g1+theme(axis.text.x=element_text(size=30,angle=0,hjust=1,vjust=0.5,family="Meiryo")) 
g1<-g1+theme(axis.text.y=element_text(size=20,family="Meiryo")) 
g1<-g1+ggtitle(mainTitle)
g1<-g1+scale_y_continuous(labels=comma)
g1<-g1+xlab("")
g1<-g1+ylab("") 
g1<-g1+coord_flip()
ST<-Sys.time()  
addVer<-gsub("\\.","",paste(year(SD),month(SD),day(SD),hour(ST),minute(ST),second(ST),sep=""))
png.file<-paste(addVer,".png",sep="")
png(file=png.file,width=imageWidth,height=imageHeight)
print(g1)
dev.off()
mainTitle<-paste("財務省貿易統計:品目別輸出額:億円:",format(extractDate[[2]],"%Y/%m"),sep="")
g2<-ggplot()
g2<-g2+geom_bar(data=data[[2]],aes(x=Item,y=Value),stat="identity",position="identity",fill="blue",alpha=0.2)
g2<-g2+geom_text(data=data[[2]],aes(x=Item,y=Value,label=Value),hjust=0,size=5,family="Meiryo")
g2<-g2+theme(plot.title=element_text(size=30,family="Meiryo"))
g2<-g2+theme(axis.title.x=element_text(size=30,family="Meiryo")) 
g2<-g2+theme(axis.title.y=element_text(size=30,family="Meiryo")) 
g2<-g2+theme(axis.text.x=element_text(size=30,angle=0,hjust=1,vjust=0.5,family="Meiryo")) 
g2<-g2+theme(axis.text.y=element_text(size=20,family="Meiryo")) 
g2<-g2+ggtitle(mainTitle)
g2<-g2+scale_y_continuous(labels=comma)
g2<-g2+xlab("")
g2<-g2+ylab("") 
g2<-g2+coord_flip()
ST<-Sys.time()  
addVer<-gsub("\\.","",paste(year(SD),month(SD),day(SD),hour(ST),minute(ST),second(ST),sep=""))
png.file<-paste(addVer,".png",sep="")
png(file=png.file,width=imageWidth,height=imageHeight)
print(g2)
dev.off()
mainTitle<-paste("財務省貿易統計:品目別輸出額:億円:",format(extractDate[[3]],"%Y/%m"),sep="")
g3<-ggplot()
g3<-g3+geom_bar(data=data[[3]],aes(x=Item,y=Value),stat="identity",position="identity",fill="blue",alpha=0.2)
g3<-g3+geom_text(data=data[[3]],aes(x=Item,y=Value,label=Value),hjust=0,size=5,family="Meiryo")
g3<-g3+theme(plot.title=element_text(size=30,family="Meiryo"))
g3<-g3+theme(axis.title.x=element_text(size=30,family="Meiryo")) 
g3<-g3+theme(axis.title.y=element_text(size=30,family="Meiryo")) 
g3<-g3+theme(axis.text.x=element_text(size=30,angle=0,hjust=1,vjust=0.5,family="Meiryo")) 
g3<-g3+theme(axis.text.y=element_text(size=20,family="Meiryo")) 
g3<-g3+ggtitle(mainTitle)
g3<-g3+scale_y_continuous(labels=comma)
g3<-g3+xlab("")
g3<-g3+ylab("") 
g3<-g3+coord_flip()
ST<-Sys.time()  
addVer<-gsub("\\.","",paste(year(SD),month(SD),day(SD),hour(ST),minute(ST),second(ST),sep=""))
png.file<-paste(addVer,".png",sep="")
png(file=png.file,width=imageWidth,height=imageHeight)
print(g3)
dev.off()
mainTitle<-paste("財務省貿易統計:品目別輸入額:億円:",format(extractDate[[4]],"%Y/%m"),sep="")
g4<-ggplot()
g4<-g4+geom_bar(data=data[[4]],aes(x=Item,y=Value),stat="identity",position="identity",fill="red",alpha=0.2)
g4<-g4+geom_text(data=data[[4]],aes(x=Item,y=Value,label=Value),hjust=0,size=5,family="Meiryo")
g4<-g4+theme(plot.title=element_text(size=30,family="Meiryo"))
g4<-g4+theme(axis.title.x=element_text(size=30,family="Meiryo")) 
g4<-g4+theme(axis.title.y=element_text(size=30,family="Meiryo")) 
g4<-g4+theme(axis.text.x=element_text(size=30,angle=0,hjust=1,vjust=0.5,family="Meiryo")) 
g4<-g4+theme(axis.text.y=element_text(size=20,family="Meiryo")) 
g4<-g4+ggtitle(mainTitle)
g4<-g4+scale_y_continuous(labels=comma)
g4<-g4+xlab("")
g4<-g4+ylab("") 
g4<-g4+coord_flip()
ST<-Sys.time()  
addVer<-gsub("\\.","",paste(year(SD),month(SD),day(SD),hour(ST),minute(ST),second(ST),sep=""))
png.file<-paste(addVer,".png",sep="")
png(file=png.file,width=imageWidth,height=imageHeight)
print(g4)
dev.off()
mainTitle<-paste("財務省貿易統計:品目別輸入額:億円:",format(extractDate[[5]],"%Y/%m"),sep="")
g5<-ggplot()
g5<-g5+geom_bar(data=data[[5]],aes(x=Item,y=Value),stat="identity",position="identity",fill="red",alpha=0.2)
g5<-g5+geom_text(data=data[[5]],aes(x=Item,y=Value,label=Value),hjust=0,size=5,family="Meiryo")
g5<-g5+theme(plot.title=element_text(size=30,family="Meiryo"))
g5<-g5+theme(axis.title.x=element_text(size=30,family="Meiryo")) 
g5<-g5+theme(axis.title.y=element_text(size=30,family="Meiryo")) 
g5<-g5+theme(axis.text.x=element_text(size=30,angle=0,hjust=1,vjust=0.5,family="Meiryo")) 
g5<-g5+theme(axis.text.y=element_text(size=20,family="Meiryo")) 
g5<-g5+ggtitle(mainTitle)
g5<-g5+scale_y_continuous(labels=comma)
g5<-g5+xlab("")
g5<-g5+ylab("") 
g5<-g5+coord_flip()
ST<-Sys.time()  
addVer<-gsub("\\.","",paste(year(SD),month(SD),day(SD),hour(ST),minute(ST),second(ST),sep=""))
png.file<-paste(addVer,".png",sep="")
png(file=png.file,width=imageWidth,height=imageHeight)
print(g5)
dev.off()
mainTitle<-paste("財務省貿易統計:品目別輸入額:億円:",format(extractDate[[6]],"%Y/%m"),sep="")
g6<-ggplot()
g6<-g6+geom_bar(data=data[[6]],aes(x=Item,y=Value),stat="identity",position="identity",fill="red",alpha=0.2)
g6<-g6+geom_text(data=data[[6]],aes(x=Item,y=Value,label=Value),hjust=0,size=5,family="Meiryo")
g6<-g6+theme(plot.title=element_text(size=30,family="Meiryo"))
g6<-g6+theme(axis.title.x=element_text(size=30,family="Meiryo")) 
g6<-g6+theme(axis.title.y=element_text(size=30,family="Meiryo")) 
g6<-g6+theme(axis.text.x=element_text(size=30,angle=0,hjust=1,vjust=0.5,family="Meiryo")) 
g6<-g6+theme(axis.text.y=element_text(size=20,family="Meiryo")) 
g6<-g6+ggtitle(mainTitle)
g6<-g6+scale_y_continuous(labels=comma)
g6<-g6+xlab("")
g6<-g6+ylab("") 
g6<-g6+coord_flip()
ST<-Sys.time()  
addVer<-gsub("\\.","",paste(year(SD),month(SD),day(SD),hour(ST),minute(ST),second(ST),sep=""))
png.file<-paste(addVer,".png",sep="")
png(file=png.file,width=imageWidth,height=imageHeight)
print(g6)
dev.off()
```