```{r}
username<-Sys.info()['user']
fileName <- "defaultPath.csv"
pathToFile <-
  paste("C:/Users/", username, "/Desktop/pathToCSV/", sep = "")
setwd(pathToFile)
buf0 <-
  read.csv(
    fileName,
    header = F,
    skip = 0,
    stringsAsFactor = F,
    check.names = F,
    na.strings = c(""),
    fileEncoding = "utf-8"
  )
```

```{r}
library(knitr)
library(lubridate)
library(stringr)
buf<-read.table("clipboard",header=T,sep="\t",stringsAsFactor=F,na.strings=c("-","－"," ---- ","…"),check.names=F)
#pathInput<-paste("C:/Users/",username,"/Desktop/R_Data_Read/",sep="")
#data.file<-"shikin_data_sjis.csv" #ラポール・ジャパン
#buf<- read.csv(paste( pathInput,data.file,sep = ""),header = T, skip = 0, stringsAsFactor = F, check.names = F, na.strings = c("-"))
buf[is.na(buf)==T]<--9999
#以降bufに変更は加えないこと
addColumn<-0
exception<-c(1)
dataset<-buf
dataset[,-exception]<-format(dataset[,-exception],big.mark=",",scientific=F)
#if(is.Date(dataset[,1])==T){dataset[,1]<-as.Date(dataset[,1])}
if(addColumn!=0){
dataset<-data.frame(dataset,dataset[,addColumn],check.names=F)
colnames(dataset)[ncol(dataset)]<-colnames(dataset)[addColumn]
}
#dataset<-data.frame(ID=seq(1,nrow(dataset),by=1),dataset,check.names=F)
tail(dataset)
```

```{r}
needRegular<-0 # 1 or other number
needLinktable<-0  # 1 or other number
individualPage<-1 # 1 or other number
RegularObj<-c(2)
title<-"毎月勤労統計調査 全国調査 原表 実数原表 2016年5月分"
source<-"厚生労働省"
alignarg<-rep("r",ncol(dataset))
alignarg<-c("r","l",rep("r",ncol(dataset)-3),"l")
ST<-Sys.time();SD<-Sys.Date()
pathOutput<-paste("C:/Users/",username,buf0[2,1],sep="")
setwd(pathOutput);getwd()
htmlFile<-paste("am-consulting.co.jp-",year(ST),"-",month(ST),"-",day(ST),"-",hour(ST),"-",minute(ST),"-",floor(second(ST)),".html",sep="")
table.argu<-paste("id=\"amcc_superSimpleTable",floor(as.numeric(ST)),"\" width=\"100%\" class=\"display compact\"",sep="")

block01<-block02<-block03<-block04<-block05<-block06<-block07<-block08<-block09<-block10<-block11<-""
if(individualPage==1){
block01<-"
<html><head><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">
<meta http-equiv=\"Pragma\" content=\"no-cache\">
<meta http-equiv=\"cache-control\" content=\"no-cache\">
<meta http-equiv=\"expires\" content=\"0\">
<style>
body{font-family:'Hiragino Kaku Gothic Pro','Meiryo UI',Verdana,sans-serif;}
.dataTables_filter input {width: 50%;}
</style>
</head>
<body>
<!---->" 
}

block02<-paste("
<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js\"></script>
<link  href=\"http://cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css\" rel=\"stylesheet\">
<script src=\"http://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js\"></script>
<link  href=\"http://knowledgevault.saecanet.com/components/pace.css\" rel=\"stylesheet\">
<script src=\"http://knowledgevault.saecanet.com/components/pace.min.js\"></script>
<style>
body{font-family:'Hiragino Kaku Gothic Pro','Meiryo UI',Verdana,sans-serif;}
table{width:100%;border-collapse:collapse;padding:0;border-spacing:1;margin-left:auto;margin-right:auto;font-size:100%;}
tr, td, th{white-space: nowrap;}
td.highlight{font-weight:plain;color:red;}
</style>
<div align=\"right\">作成日時:",as.character(Sys.time()),"</div><hr>
<script type=\"text/javascript\" charset=\"utf-8\">
$(document).ready(function(){
$('#amcc_superSimpleTable",floor(as.numeric(ST)),"').dataTable({
\"lengthMenu\":[[20,10,-1],[20,10,\"All\"]],
\"order\":[[0,\"asc\"]],
\"searching\":true,
\"columnDefs\":[{\"width\":\"5%\",\"targets\":0}],
\"language\":{\"decimal\":\".\",\"thousands\":\",\"},
initComplete: function () {
this.api().columns().every( function () {
var column = this;
var select = $('<select><option value=\"\"></option></select>')
.appendTo( $(column.footer()).empty() )
.on( 'change', function () {
var val = $.fn.dataTable.util.escapeRegex(
$(this).val()
);
column
.search( val ? '^'+val+'$' : '', true, false )
.draw();
} );
column.data().unique().sort().each( function ( d, j ) {
select.append( '<option value=\"'+d+'\">'+d+'</option>' )
} );
} );
}
,
createdRow:function(row,data,index){\n",sep="")

block03<-""
for(ccc in 1:ncol(dataset)){
  block03<-paste(block03 , paste("if ( data[",ccc-1,"].replace(',' , '') * 1 < 0 ) {\n",sep=""))
  block03<-paste(block03 , paste("$('td', row).eq(",ccc-1,").addClass('highlight');\n",sep=""))
  block03<-paste(block03 , "}\n")
}
block03<-paste(block03,"}})")

#正規表現
if(needRegular==1){
block04<-paste("
$('#amcc_superSimpleTable",floor(as.numeric(ST)),"').dataTable();
$('input.global_filter').on( 'keyup click', function () {
filterGlobal();
});
$('input.column_filter').on( 'keyup click', function () {
filterColumn( $(this).parents('tr').attr('data-column') );
});",sep="")
}
#正規表現

block05<-paste("});</script>\n\n",
paste("<div align=\"center\"><b>",title,"</b><br>データ出所:",source,"</div>"),
"-9999は「データなし」または「データ欠損」または「NA」を意味します<hr>")

#正規表現
if(needRegular==1){
block06<-"
<b>正規表現対応フィルターボックス</b>  
<table width=\"100%\">
<thead>
<tr>
<th width=\"15%\" style=\"text-align:center\">Target</th>
<th width=\"75%\" style=\"text-align:center\">Search text</th>
<th style=\"text-align:center\">Regex</th>
</tr>
</thead>
<tbody>"

block07<-""  
for(rccc in 1:ncol(dataset)){
if(length(grep(rccc,RegularObj))!=0){  
block07<-paste(block07 , paste("
<tr id=\"filter_col",rccc,"\" data-column=\"",rccc-1,"\">
<td>",colnames(dataset)[rccc],"</td>
<td align=\"center\"><input type=\"text\" class=\"column_filter\" id=\"col",rccc-1,"_filter\" style=\"width:100%\"></td>
<td align=\"center\"><input type=\"checkbox\" class=\"column_filter\" id=\"col",rccc-1,"_regex\" checked=\"checked\"></td>
</tr>",sep=""))
}
}  
block07<-paste(block07,"</tbody></table><hr>")  

block08<-"
<script>
function filterGlobal () {
$('#amcc_superSimpleTable').DataTable().search(
$('#global_filter').val(),
$('#global_regex').prop('checked'),
$('#global_smart').prop('checked')
).draw();
}
function filterColumn ( i ) {
$('#amcc_superSimpleTable').DataTable().column( i ).search(
$('#col'+i+'_filter').val(),
$('#col'+i+'_regex').prop('checked'),
$('#col'+i+'_smart').prop('checked')
).draw();
}
</script>"
}  

outputTable<-kable(dataset,'html',row.names=F,table.attr=table.argu,align=alignarg)
tfoot<- str_extract(outputTable, "<thead>[\\w\\W]*?</thead>")
tfoot<- paste(str_replace_all(tfoot, "thead","tfoot"),"</table>")
outputTable<-gsub("</table>","",outputTable)
block09<-paste("<div style=\"overflow-x:scroll;\">\n",outputTable,tfoot,"</div>\n",
"Powered by<br>-DataTables( http://datatables.net/ )<br>-jQuery( https://jquery.com )<br>-PACE( http://github.hubspot.com/pace/docs/welcome/ )")

if(needLinktable==1){
block10<-"
<hr>
<table style=\"border:none; table-layout:fixed;\">
<tbody>
<tr>
<td style=\"border:none\" width=\"10%\">
　Asset Management Consulting
　[browser-shot url=\"http://am-consulting.co.jp\"]
</td>
<td style=\"border:none\"  width=\"10%\">
　Curiosity
　[browser-shot url=\"http://curiosity.am-consulting.co.jp\"]
</td>
<td style=\"border:none\"  width=\"10%\">
　Equations
　[browser-shot url=\"http://equations.am-consulting.co.jp\"]
</td>
<td style=\"border:none\"  width=\"10%\">
　SaECaNet
　[browser-shot url=\"http://www.saecanet.com\"]
</td>
</tr>
<tr>
<td style=\"border:none\">
　youtube channel \"Curiosity\"
　[browser-shot url=\"https://www.youtube.com/user/michiomitake\"]
</td>
<td style=\"border:none\">
　Google Store
　[browser-shot url=\"https://play.google.com/store/apps/developer?id=%E3%82%A2%E3%82%BB%E3%83%83%E3%83%88%E3%83%BB%E3%83%9E%E3%83%8D%E3%82%B8%E3%83%A1%E3%83%B3%E3%83%88%E3%83%BB%E3%82%B3%E3%83%B3%E3%82%B5%E3%83%AB%E3%83%86%E3%82%A3%E3%83%B3%E3%82%B0%E6%A0%AA%E5%BC%8F%E4%BC%9A%E7%A4%BE&hl=ja\"]
</td>
<td style=\"border:none\">
　twitCasting
　[browser-shot url=\"http://twitcasting.tv/amc2_japan/show/\"]
</td>
<td style=\"border:none\">
　twitter:ID AMC2_Japan
　[browser-shot url=\"https://twitter.com/AMC2_Japan\"]
</td>
</tr>
<tr>
<td style=\"border:none\">
　GitHub
　[browser-shot url=\"https://github.com/am-consulting\"]
</td>
<td style=\"border:none\">
　facebook
　[browser-shot url=\"https://www.facebook.com/asset.management.consulting/\"]
</td>
<td style=\"border:none\">
　twilog:ID AMC2_Japan
　[browser-shot url=\"http://twilog.org/amc2_japan\"]
</td>
<td style=\"border:none\">
　Google Custom Search
　[browser-shot url=\"http://equations.am-consulting.co.jp/gcs.html\"]
</td>
</tr>
<tr>
<td style=\"border:none\">
　twitter:ID SaECaNet
　[browser-shot url=\"https://twitter.com/SaECaNet\"]
</td>
<td style=\"border:none\">
The Beam	
　[browser-shot url=\"http://www.saecanet.com/list_of_beamcalculation.php\"]
</td>
<td style=\"border:none\">
</td>
<td style=\"border:none\">
</td>
</tr>
</tbody>
</table>"
}

if(individualPage==1){
block11<-"
<!---->
<hr>
<div align=\"center\"><a href=\"http://am-consulting.co.jp\" target=\"_blank\">アセット・マネジメント・コンサルティング株式会社</a></div>
</body>
</html>" 
}  

code0 <- paste(block01, block02, block03, block04, block05, block06, block07, block08, block09, block10, block11)
cat(code0, file = (con <- file(htmlFile, "w", encoding = "UTF-8")), append = T)
close(con)
```