```{r}
library(lubridate)
username<-Sys.info()['user']
pathOutput<-paste("C:/Users/",username,"/Desktop/R_Data_Write/",sep="")
SD<-Sys.Date()
windowsFonts(Meiryo=windowsFont("Meiryo"))
```

```{r}
menulength<-17
orderColumn<-0
orderDirection<-"asc" #asc desc
columnWidth<-"{\"width\":\"17%\",\"targets\":0}"
```

```{r}
beeData<-list()
functionBEE<-function(weight){
  switch(sex,
    bee<-66.473+13.7516*weight+5.0033*height-6.755*age, #male
    bee<-655.0955+9.5634*weight+1.8496*height-4.6756*age #female
  )  
  return(bee)  
}
for(sex in 1:2){
  tmpDataset<-NULL
  if(sex==1){ #male
  	lowerLimitW<-50
    upperLimitW<-100
	}else{
		lowerLimitW<-50
		upperLimitW<-100
	}
  if(sex==1){ #male
    lowerLimitH<-150
    upperLimitH<-190
	}else{
		lowerLimitH<-150
		upperLimitH<-190
	}
  if(sex==1){ #male
    sexType<-"男"
  }else{
		sexType<-"女"
	}
  weight<-seq(lowerLimitW,upperLimitW,by=5)
  height<-seq(lowerLimitH,upperLimitH,by=2.5)
  for(age in seq(20,70,by=5)){
    tmp<-sapply(weight,functionBEE)
    buf<-data.frame(paste(sexType,"-",age,"歳-",height,"cm",sep=""),round(tmp,0))
    tmpDataset<-rbind(tmpDataset,buf)  
  }
  colnames(tmpDataset)<-c(paste("性別-年齢-身長",sep=""),paste(weight,"kg",sep=""))
  beeData[[sex]]<-tmpDataset
  print(beeData[[sex]])
}
```

```{r}
#only html
setwd(pathOutput)
col<-list()
ST<-Sys.time()  
addVer<-gsub("\\.","",paste(year(SD),month(SD),day(SD),hour(ST),minute(ST),second(ST),sep=""))
htmlFile<-paste(addVer,".html",sep="")
cat("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js\"></script>\n",file=htmlFile,append=F)
cat("<link href=\"http://cdn.datatables.net/1.10.7/css/jquery.dataTables.min.css\" rel=\"stylesheet\">\n",file=htmlFile,append=T)
cat("<script src=\"http://cdn.datatables.net/1.10.7/js/jquery.dataTables.min.js\"></script>\n",file=htmlFile,append=T)
cat("<b>ハリス-ベネディクトの式(Harris-Benedict Equation)による基礎エネルギー消費量(BEE,kcal/day)</b>\n",file=htmlFile,append=T)
for(sex in 1:2){
  grandData<-NULL
  header<-NULL
  dataset<-beeData[[sex]]
  tableID<-paste("am-consulting",sex,addVer,sep="")
  cat("<script type=\"text/javascript\" charset=\"utf-8\">\n$(document).ready( function(){\n",file=htmlFile,append=T)
  cat(paste("$('#",tableID,"').dataTable({\n",sep=""),file=htmlFile,append=T)
  cat("\"lengthMenu\": [[",menulength,",-1,100,200], [",menulength,",\"All\",100,200]],\n",file=htmlFile,append=T)
  cat(paste("\"order\": [[ ",orderColumn,", \"",orderDirection,"\" ]],\n",sep=""),file=htmlFile,append=T)
  cat("\"searching\": true,\n",file=htmlFile,append=T)
  cat("\"columnDefs\":[",columnWidth,"],\n",file=htmlFile,append=T)
  cat("\"language\": {\"decimal\": \".\",\"thousands\": \",\"}\n",file=htmlFile,append=T)
  cat("});\n",file=htmlFile,append=T)
  cat("});\n</script>\n",file=htmlFile,append=T)
  for(ccc in 1:ncol(dataset)){
    tmp0<-dataset[,ccc]
    col[[ccc]]<-paste("<td align=\"right\" valign=\"middle\">",format(tmp0,big.mark=",",scientific=F),"</td>",sep="")
    grandData<-cbind(grandData,col[[ccc]])
    header<-paste(header,"<th>",colnames(dataset)[ccc],"</th>",sep="")  
  }
  tableHtml<-paste("<table cellpadding=\"0\" cellspacing=\"0\" id=\"",tableID,"\" width=\"100%\" class=\"display\" style=\"font-size:15px;\"><thead>",sep="")
  tableHtml<-paste(tableHtml,header,"</thead>",sep="")
  cat(tableHtml,file=htmlFile,append=T)
  grandData<-data.frame("<tr>",grandData,"</tr>",row.names=NULL)
  write.table(grandData,htmlFile,quote=F,col.names=F,row.names=F,append=T)
  cat("</table>\n",file=htmlFile,append=T)
  cat("<hr>\n",file=htmlFile,append=T)
}
cat("Powered by DataTables( http://datatables.net/ )<br>\n",file=htmlFile,append=T)
cat("参照 - http://ja.wikipedia.org/wiki/%E3%83%8F%E3%83%AA%E3%82%B9-%E3%83%99%E3%83%8D%E3%83%87%E3%82%A3%E3%82%AF%E3%83%88%E3%81%AE%E5%BC%8F",file=htmlFile,append=T)
cat(paste("<br>Harris-Benedict Equation Ver.",addVer,"<br>\n",sep=""),file=htmlFile,append=T)
```