
```{r}
requiredPackageList<-c("quantmod","PerformanceAnalytics","lubridate","ggplot2")
colnames(installed.packages())
notInstalledPackages<-requiredPackageList[!(requiredPackageList %in% installed.packages()[,"Package"])] #apply logical vector to requiredPackageList
if(length(notInstalledPackages)!=0){print(notInstalledPackages);install.packages(notInstalledPackages)}
lapply(requiredPackageList,require,character.only=T)
#Reference 
#http://stackoverflow.com/questions/4090169/elegant-way-to-check-for-missing-packages-and-install-them
#http://stackoverflow.com/questions/8175912/load-multiple-packages-at-once
username<-Sys.info()['user']
pathOutput<-paste("C:/Users/",username,"/Desktop/charts/",sep="")
SD<-Sys.Date()
windowsFonts(Meiryo=windowsFont("Meiryo"))
setwd(pathOutput)
```

```{r}
ts.source<-list()
dataset<-list()
reference<-list()
allData<-xts()
ts.source[[1]]<-c("yahoo",4,"https://www.yahoo.com/","^N225","^HSI","^AXJO","^GSPC","^RUT","^FTSE")#"NDX",
ts.source[[2]]<-c("yahoo",4,"https://www.yahoo.com/","^STI","^KS11","^TWII","^GDAXI","^FCHI","^BVSP")
ts.source[[3]]<-c("oanda",1,"http://www.oanda.com/","AUD","JPY","EUR","GBP","NZD","ZAR","CHF","CAD","XAU","BRL","RUB")#,"KRW","CNY"
cnt<-0
for(lll in 1:length(ts.source)){
  for(iii in 4:length(ts.source[[lll]])){
    cnt<-cnt+1
    if(ts.source[[lll]][1]=="oanda"){
      if(ts.source[[lll]][iii]=="JPY" | ts.source[[lll]][iii]=="CHF" | ts.source[[lll]][iii]=="ZAR" | ts.source[[lll]][iii]=="KRW"){
        item<-paste("USD/",ts.source[[lll]][iii],sep="")
      }else{
        item<-paste(ts.source[[lll]][iii],"/USD",sep="")
      }
    }
    else{
      item<- ts.source[[lll]][iii]
    }
    dataset[[cnt]]<-getSymbols(item,src=ts.source[[lll]][1],auto.assign=FALSE)
    dataset[[cnt]]<-dataset[[cnt]][,as.double(ts.source[[lll]][2])]
    allData<-merge(allData,dataset[[cnt]])
    dataset[[cnt]]<-na.omit(dataset[[cnt]])
    dataset[[cnt]]<-merge.xts(dataset[[cnt]],INDEX=c(1:length(dataset[[cnt]])))
    reference[[cnt]]<-ts.source[[lll]][3]
  }
}
```

```{r}
pathInput<-paste("C:/Users/",username,"/Desktop/pathToCSV/",sep="")
folder.path<-file.path(pathInput)
setwd(folder.path)
tmp<-read.csv(file=dir(folder.path),header=F,as.is=T,skip=0,na.strings=c("", "NA"))
dir.list<-paste("C:/Users/",username,tmp[1,2],sep="")
cor.fun=function(x){cor(x)[1,2]}
firstDate<-Sys.Date()
year(firstDate)<-year(firstDate)-1
for(iii in seq(1,cnt,by=2)){
  setwd(pathOutput)
  ST<-Sys.time()  
  addVer<-gsub("\\.","",paste(year(SD),month(SD),day(SD),hour(ST),minute(ST),second(ST),sep=""))
  png.file<-paste(addVer,".png",sep="")
  png(file=png.file,width=1920,height=1080)
  par(mfrow=c(1,2),mar=c(5,8,10,8),family="Meiryo")
  for(ccc in seq(iii,iii+1)){
  if(cnt<ccc){break}  
  if(regexpr("oanda",reference[[ccc]])!=-1){
    lag<-30
  }else{
    lag<-30
  }  
  tmp<-dataset[[ccc]][paste(firstDate,"::",sep="")]
  correlation<-na.omit(rollapply(tmp,FUN=cor.fun,width=lag,by.column=F,align="right"))  
  lengthMinus<-length(correlation[correlation<0])  
  lengthPlus<-length(correlation[correlation>=0])  
  ratioMinus<-round(lengthMinus/(lengthMinus+lengthPlus)*100)
  print(colnames(tmp)[1])
  print(tail(correlation,10))
  cat("\n\n") 
  setwd(dir.list)
  csvFile<-paste(colnames(tmp)[1],".csv",sep="")
  csvData<-data.frame(date=index(correlation),correlation, row.names=NULL)
  colnames(csvData)[2]<-paste(colnames(tmp)[1],".",colnames(csvData)[2],sep="")  
  write.csv(tail(csvData,30),csvFile,row.names=F,append=F,quote=F,fileEncoding="UTF-8")
  mainTitle<-paste("ローリング回帰 ラグのスパン:",lag,"(日間)\n",colnames(tmp)[1],
    ", correlation<0:",lengthMinus,",Ratio(%):",ratioMinus,"\n",head(index(tmp),1),"-",tail(index(tmp),1),"\nData Source:",reference[[iii]])
  chart.RollingCorrelation(tmp[,2],tmp[,1],width=lag,
    main=mainTitle,type="h",col=grey(0.5),cex.legend=3,cex.axis=2,cex.main=2.5,cex.lab=3,ylab="correlation",xaxis=T,date.format="%Y/%m/%d")
  par(new=T)
  chart.TimeSeries(tmp[,1],main="",yaxis.right=T,xaxis=T,lwd=3,
    cex.legend=3,cex.axis=2,cex.lab=2,col="blue",grid.color="blue",ylab="",date.format="%Y/%m/%d") #共に,ylab=""とする。
  mtext(colnames(tmp)[1],side=4,line=3,cex=3)
  }
  dev.off()
}
```

```{r}
colnames(allData)
selectedObject<-c(1,4,6,10,11,12,13,14,15,16,18,21)
setwd(pathOutput)
tmp.allData<-list()
tmp.allData[[1]]<-na.omit(allData)
tmp.allData[[2]]<-na.omit(diff(tmp.allData[[1]],lag=1,diff=1))
#corrMethod<-c("pearson", "kendall", "spearman")
corrMethod<-c("spearman") #当面スピアマンのみとする。ピアソンを適用する際はデータの正規性に注意すること
for(iii in 2:2){ #一次階差のみとする
  if(iii==1){dataType="Level"}else{dataType="1stDifference"}
  selectedData<-tmp.allData[[iii]][,selectedObject]
  for(mmm in 1:length(corrMethod)){
    ST<-Sys.time()  
    addVer<-gsub("\\.","",paste(year(SD),month(SD),day(SD),hour(ST),minute(ST),second(ST),sep=""))
    png.file<-paste(addVer,".png",sep="")
    png(file=png.file,width=1920,height=1080)
    par(mar=c(10,10,10,10))
    mainTitle<-paste("Data:",dataType," , Method:",toupper(corrMethod[mmm]),
      " , Period:",format(head(index(selectedData),1),"%Y-%m-%d"),"-",format(tail(index(selectedData),1),"%Y-%m-%d"))
    chart.Correlation(selectedData,histogram=F,method=corrMethod[mmm],main=mainTitle,cex.main=3,cex.text=5)
    dev.off()
  }
}
```

```{r}
setwd(pathOutput)
corrMethod<-"spearman"
for(iii in 2:2){
  grand.result<-NULL
  if(iii==1){
    buf<-na.omit(allData)
    chart.title<-"Data:Level"
  }else{
    buf<-na.omit(diff(na.omit(allData),lag=1,diff=1))
    chart.title<-"Data:1stDifference"
  }  
  result.cor<-cor(buf,method=corrMethod)
  f.date<-format(first(index(buf)),"%Y-%m-%d")
  e.date<-format(last(index(buf)),"%Y-%m-%d")
#  mainTitle<-paste(chart.title,f.date,"-",e.date)
  for(ccc in 1:ncol(result.cor)){
    tmp<-paste(row.names(result.cor),"-",row.names(result.cor)[ccc],sep="")
    tmp.df<-data.frame(tmp[-(1:ccc)],result.cor[-(1:ccc),ccc],row.names=NULL)
    grand.result<-rbind(grand.result,tmp.df)
  }
  rrr<-order(grand.result[,2],decreasing=T)
  grand.result<-grand.result[rrr,]
  grand.result[,1]<-ordered(grand.result[,1],levels=grand.result[,1][1:length(grand.result[,1])])
  colnames(grand.result)<-c("xvalue","yvalue")
  for(ppp in 1:2){
    if(ppp==1){
      data<-head(grand.result,35)
      fillCol<-"blue"
    }else{
      data<-tail(grand.result,35)
      fillCol<-"red"
    } 
    ST<-Sys.time()  
    addVer<-gsub("\\.","",paste(year(SD),month(SD),day(SD),hour(ST),minute(ST),second(ST),sep=""))
    png.file<-paste(addVer,".png",sep="")
    png(file=png.file,width=1920,height=1080)
    g<-ggplot()
    g<-g+geom_bar(data=data,aes(x=xvalue,y=yvalue),stat="identity",position="identity",fill=fillCol,alpha=0.2,color="black")
    g<-g+theme(axis.text.x=element_text(size=30,angle=90,hjust=1,vjust=0.5)) 
    g<-g+theme(axis.text.y=element_text(size=30))
    g<-g+theme(plot.title=element_text(size=40,family="Meiryo"))
    g<-g+theme(axis.title.x=element_text(size=30,family="Meiryo")) 
    g<-g+theme(axis.title.y=element_text(size=30,family="Meiryo")) 
    g<-g+ggtitle(paste(chart.title," , Method:",toupper(corrMethod)," , Period:",f.date,"-",e.date))
    g<-g+xlab("")
    g<-g+ylab("") 
    print(g)
    dev.off()
  }
}
setwd(dir.list)
colnames(grand.result)<-c("Pair","Correlation")
csvFile<-paste("finance.correlation.1stDifference.spearman.csv",sep="")
write.csv(grand.result,csvFile,row.names=F,append=F,quote=F,fileEncoding="UTF-8")
```