```{r}
requiredPackageList<-c("ggplot2","lubridate","scales","maps","maptools","RColorBrewer","fields","rworldmap","classInt","plotrix","HH","reshape")
colnames(installed.packages())
notInstalledPackages<-requiredPackageList[!(requiredPackageList %in% installed.packages()[,"Package"])] #apply logical vector to requiredPackageList
if(length(notInstalledPackages)!=0){print(notInstalledPackages);install.packages(notInstalledPackages)}
lapply(requiredPackageList,require,character.only=T)
#Reference 
#http://stackoverflow.com/questions/4090169/elegant-way-to-check-for-missing-packages-and-install-them
#http://stackoverflow.com/questions/8175912/load-multiple-packages-at-once
username<-Sys.info()['user']
pathOutput<-paste("C:/Users/",username,"/Desktop/charts/",sep="")
pathJmap<<-paste("C:/Users/",username,"/Desktop/jpn/",sep="")
pathWmap<<-paste("C:/Users/",username,"/Desktop/ne_50m_admin_0_countries/",sep="")
SD<-Sys.Date()
creationDate<-paste("作成日:",year(SD),"-",month(SD),"-",day(SD),sep="")  
setwd(pathOutput)
windowsFonts(Meiryo=windowsFont("Meiryo"))
fun.readData<-function(){
  dataset<<-read.table("clipboard",header=TRUE,sep="\t",stringsAsFactor=F)
  head(dataset)
  tail(dataset)
}
fun.round<-function(buf){
  return.buf<<-round(buf/10^floor(log10(buf)),1)*10^floor(log10(buf))
}  
```

```{r}
fun.readData()
```

```{r}
########################################## time series ##########################################
dateType<-1
switch(dateType,
  dateFormat<-"%Y/%m/%d",
  dateFormat<-"%Y/%m"
)  
colorList<-c("blue","red")
mainTitle<-"週間石油在庫統計:USOICR:製油所原油処理量"
dataSource<-"\nData Source:U.S. Energy Information Administration"
chartType<-2 #1:line , 2:bar
fitType<-3 #1:lm , 2:loess ,3:none
tailNumber<-200
setwd(pathOutput)
if(colnames(dataset)[1]=="Date"){
  dataset[,1]<-as.Date(dataset[,1])
}else{
  dataset[,1]<-ordered(dataset[,1],levels=dataset[,1][1:length(dataset[,1])])
}
buf.dataset<-tail(dataset,tailNumber)  
melt.dataset<-melt(buf.dataset,id=colnames(buf.dataset)[1])#系列が一つでも強制的にmelt
ST<-Sys.time()  
addVer<-gsub("\\.","",paste(year(SD),month(SD),day(SD),hour(ST),minute(ST),second(ST),sep=""))
png.file<-paste(addVer,".png",sep="")
png(file=png.file,width=1920,height=1080)
g<-ggplot()
g<-g+scale_y_continuous(labels=comma)
switch(chartType,  
  g<-g+geom_line(data=melt.dataset,aes(x=Date,y=value,color=variable),size=2),
  g<-g+geom_bar(data=melt.dataset,aes(x=Date,y=value,fill=variable),stat="identity",position="identity",alpha=0.5)
)
switch(fitType,
  g<-g+geom_smooth(data=melt.dataset,aes(x=Date,y=value),method=lm,lwd=2),
  g<-g+geom_smooth(data=melt.dataset,aes(x=Date,y=value,group=1),method=loess,lwd=2,color="red"),
  g<-g
)
g<-g+scale_color_manual(values=colorList) 
g<-g+scale_fill_manual(values=colorList) 
g<-g+theme(plot.title=element_text(size=40,family="Meiryo"))
g<-g+theme(axis.title.x=element_text(size=30)) 
g<-g+theme(axis.title.y=element_text(size=30)) 
g<-g+theme(axis.text.x=element_text(size=40,angle=0,hjust=0.5,vjust=0.5)) 
g<-g+theme(axis.text.y=element_text(size=40,angle=90)) 
g<-g+theme(legend.text=element_text(colour="black",size=30,face="plain",family="Meiryo"))   
g<-g+theme(legend.title=element_text(colour="white",size=0,face="bold"))   
g<-g+theme(legend.position="top")          
g<-g+ggtitle(paste(mainTitle,"\n対象期間:",format(head(buf.dataset[,1],1),dateFormat),"-",format(tail(buf.dataset[,1],1),dateFormat),dataSource))
if(colnames(buf.dataset)[1]=="Date"){  
  g<-g+scale_x_date(labels=date_format(dateFormat))  
}  
g<-g+xlab("")
g<-g+ylab("")
g<-g+geom_text(aes(x=tail(buf.dataset[,1],1),y=as.numeric(tail(buf.dataset[,-1],1)),
  label=paste(format(tail(buf.dataset[,1],1),dateFormat),":",as.numeric(tail(buf.dataset[,-1],1)))),size=10,hjust=1)
print(g)
dev.off()
########################################## time series ##########################################
```

```{r}
##########################################  bar chart  ##########################################
grandTitle<-"建築着工統計調査:2015年3月:都道府県別"
dataSource<-"\nData Source:国土交通省"
titleCol<-2 
orderType<-2 # 1:as is(including "Date") , 2-:colnumber
fun.readData()
colorList<-c("blue","red") #改良余地あり
setwd(pathOutput)
if(colnames(dataset)[1]=="Date"){dataset[,1]<-as.Date(dataset[,1])}
buf.colnames<-colnames(dataset)
buf.dataset<-dataset
SD<-Sys.Date()
ST<-Sys.time()  
addVer<-gsub("\\.","",paste(year(SD),month(SD),day(SD),hour(ST),minute(ST),second(ST),sep=""))
png.file<-paste(addVer,".png",sep="")
png(file=png.file,width=1920,height=1080)
mainTitle<-buf.colnames[titleCol]
mainTitle<-gsub("source","\nData Source:",mainTitle)
mainTitle<-gsub("前年同月比","前年同月比(%)",mainTitle)
mainTitle<-gsub("割合","割合(%)",mainTitle)
mainTitle<-gsub("break","\n",mainTitle)
if(orderType!=1){
  rrr<-order(buf.dataset[,(orderType)],decreasing=FALSE)
  buf.dataset<-buf.dataset[rrr,]
  buf.dataset[,1]<-ordered(buf.dataset[,1],levels=buf.dataset[,1][length(buf.dataset[,1]):1])#Dateに適用するとNAに変換されるので注意
}  
if(ncol(buf.dataset)<=2){
  colnames(buf.dataset)<-c("xvalue","yvalue")
  buf.dataset[buf.dataset[,2]<0,3]<-"red"
  buf.dataset[buf.dataset[,2]>=0,3]<-"blue"
  colnames(buf.dataset)[3]<-"color"
  g<-ggplot()
  g<-g+geom_bar(data=buf.dataset,aes(x=xvalue,y=yvalue,fill=color),stat="identity",position="identity",alpha=0.2)
  g<-g+scale_fill_manual(values=colorList) 
  g<-g+geom_text(data=buf.dataset,aes(x=xvalue,y=yvalue,label=yvalue),hjust=0,size=10,family="Meiryo")
  g<-g+theme(legend.position="none")          
}else{
  melt.dataset<-melt(buf.dataset,id=colnames(buf.dataset)[1])  
  g<-ggplot(melt.dataset,aes(x=melt.dataset[,1],y=value,fill=variable))
  g<-g+geom_bar(stat="identity",position="dodge",alpha=0.3)  
  g<-g+theme(legend.text=element_text(colour="black",size=15,face="plain",family="Meiryo"))   
  g<-g+theme(legend.title=element_text(colour="white",size=0,face="bold"))   
  g<-g+scale_fill_manual(values=colorList) 
  g<-g+geom_text(data=melt.dataset,aes(label=value),hjust=-0.5,size=6,family="Meiryo",position=position_dodge(width=0.9))
}  
g<-g+theme(plot.title=element_text(size=40,family="Meiryo"))
g<-g+theme(axis.title.x=element_text(size=30)) 
g<-g+theme(axis.title.y=element_text(size=30)) 
g<-g+theme(axis.text.x=element_text(size=25,angle=0,hjust=1,vjust=0.5)) 
g<-g+theme(axis.text.y=element_text(size=25)) 
g<-g+ggtitle(paste(grandTitle,"\n",mainTitle,dataSource))
if(colnames(dataset)[1]=="Date" & regexpr("\\.月次",buf.colnames[2])!=-1){  
  g<-g+scale_x_date(labels=date_format("%Y-%m"))  
}  
g<-g+scale_y_continuous(labels=comma)
g<-g+xlab("")
g<-g+ylab("") 
g<-g+coord_flip()
print(g)
dev.off()
##########################################  bar chart  ##########################################
```

```{r}
##########################################  Japan Map  ##########################################
color.set<-c("#f8f8fc","#f1f1f8","#e2e2f1","#c7c7e2","#aaaad5","#8d8dc7","#7272b8","#5555aa","#47478d","#383872","#2b2b55","#1d1d38")
color.set<-c("#f8f8fc","#e2e2f1","#aaaad5","#7272b8","#47478d","#2b2b55")
lon.center<-NULL
lat.center<-NULL  
plotValue<-NULL
#####The following source codes and Japanese comments are the copyright of http://aoki2.si.gunma-u.ac.jp/.
# 塗り分け地図を描く
map <- function(code.list,                  # 描画する都道府県コード
density=NULL,                               # ハッチングの 1 インチあたりの線密度
color=NULL)                                 # 塗り分けに使用する色
{
  map0 <- function(data, dens, color)       # 描画関数
  {
    ### The following codes are added by AMCC.
      setwd(pathOutput)                         
      SD<-Sys.Date()
      ST<-Sys.time()  
      addVer<-gsub("\\.","",paste(year(SD),month(SD),day(SD),hour(ST),minute(ST),second(ST),sep=""))
      creationDate<-paste("作成日:",year(SD),"-",month(SD),"-",day(SD),sep="")  
      png.file<-paste(addVer,".png",sep="")      
      png(file=png.file,width=1920,height=1080) 
      par(mar=c(6,0,12,0),ps=40)
    ### The above codes are added by AMCC.
    continue <- apply(data, 1, any)         # 経度と緯度が共に 0 が描画の区切り
    plot(lon, lat, type = "n", axes=FALSE,  # 大枠を決める
    xlab="", ylab="", bty="n", asp=1,
    main=paste(mainTitle),cex.main="1.5",cex.sub="1.0",family="Meiryo",sub="Choropleth map is made by map.R(http://aoki2.si.gunma-u.ac.jp/)") # This code is added by AMCC.
    start <- 1
    k <- 0
    for (i in 2:nrow(data)) {
      if (continue[i] == FALSE) {           # 区切れ目
        k <- k+1                            # 何番目の描画か
        if (i-start == 4) {                 # 沖縄を描くときの区画線
          lines(data[start:(i-1),])
        }
        else {
          ### The following codes are added by AMCC.
          lon.center<-c(lon.center,(max(data[start:(i-1),1])+min(data[start:(i-1),1]))/2)
          lat.center<-c(lat.center,(max(data[start:(i-1),2])+min(data[start:(i-1),2]))/2)
          plotValue<-c(plotValue,tmp.1[k])
          if(fillType==1){
          ### The above codes are added by AMCC.
            polygon(data[start:(i-1),], density=dens[k], col=color[k], border="black")
          ### The following codes are added by AMCC.
          }else{
            polygon(data[start:(i-1),], density=dens[k],  border="black")
            draw.circle(lon.center,lat.center,(tmp.1[k]/min(tmp.1))*magnify,col=rgb(255,0,0,160,maxColorValue=255),border=rgb(255,0,0,maxColorValue=255))
          }  
          ### The above codes are added by AMCC.
        }
        start <- i+1
      }
    }
    if(textPlot==1){
      text(lon.center,lat.center,round(plotValue,2),cex=textSize,col="black",font=1) # This code is added by AMCC.         
    }
    ### The following codes are added by AMCC. Reference http://ds0.cc.yamaguchi-u.ac.jp/~fukuyo/r-map.html
      if(fillType==1){
      heightPoly<-30
      basePoly01<-100
      basePoly02<-basePoly01+heightPoly
      widthPoly<-40
      for (ppp in 1:(length(color.set))){
        #時計回りに長方形×1
        xPolygon<-c(0,0,widthPoly,widthPoly,0)
        yPolygon<-c(basePoly01+heightPoly*ppp,basePoly02+heightPoly*ppp,basePoly02+heightPoly*ppp,basePoly01+heightPoly*ppp,basePoly01+heightPoly*ppp)
        polygon(xPolygon, yPolygon, col=color.set[ppp],border="black")
        #時計回りに長方形×1
        if(ppp!=length(color.set)){
          text(widthPoly+5,basePoly02+heightPoly*ppp,labels=format(t[ppp],big.mark=",",scientific=F),adj=0)
        }  
      }
      }  
      dev.off()
    ### The above codes are added by AMCC. Reference http://ds0.cc.yamaguchi-u.ac.jp/~fukuyo/r-map.html
  }
  # 関数本体
  for (i in seq(along=code.list)) {               # 指定した全ての都道府県について
    if (code.list[i] %in% c(15, 28, 47)) {        # 新潟県，兵庫県，沖縄県は描画パーツが 2 つ
      code.list <- c(code.list, -code.list[i])    # コードリストの追加（目印とするために負の数で）
      density <- c(density, density[i])           # 線密度と
      color <- c(color, color[i])                 # 色も追加する
    }
  }
  code.list[code.list == -15] <- 48               # 追加のコードリストに直す
  code.list[code.list == -28] <- 49
  code.list[code.list == -47] <- 50
  lon <- lat <- NULL
  setwd(pathJmap)# This code is added by AMCC.
  for (i in code.list) {                                     # 指定した全ての都道府県について
    fn <- sprintf("jpn/%02i", i)                             # データファイル名を得る
    gwm <- matrix(scan(fn, quiet=TRUE), ncol=2, byrow=TRUE)  # データを読む
    lon <- c(lon, gwm[,1], 0)                                # 経度を蓄積
    lat <- c(lat, gwm[,2], 0)                                # 緯度を蓄積
  }
  mlon <- min(lon[lon != 0])                                    # 経度の最小値
  mlat <- max(lat[lat != 0])                                    # 緯度の最大値
  lon <- ifelse(lon == 0, 0, lon-mlon+1)                        # 経度の調整
  lat <- ifelse(lat == 0, 0, mlat-lat+1)                        # 緯度の調整
  map0(cbind(as.integer(lon), as.integer(lat)), density, color) # 描画関数を呼ぶ
}
# データにより塗り分け地図を描く
color.map3 <- function(x,  # 長さ 47 の統計データベクトル
t,                         # データを区分する値
color.set)                 # 各区分を塗る色
{
  if (length(t)+1 != length(color.set)) {
    stop("t の長さは color.set の長さより 1 だけ小さくなければならない")
  }
  map(1:47, color=color.set[findInterval(x, t)+1])
}
#########The above source codes and Japanese comments are the copyright of http://aoki2.si.gunma-u.ac.jp/.  
```

```{r}
#コロプレスマップの描画順序(k)とオリジナルデータの都道府県順序が一致しているか十分に気をつけること
textSize<-0.6
nSplit<-6
textPlot<-1
fillType<-1
magnify<-1
roundType<-2
Nsmall<-2
classStyle<-c("sd", "equal", "quantile", "kmeans", "hclust", "fisher")
classStyleJ<-c("標準偏差", "等間隔", "等量", "非階層クラスタリング", "階層クラスタリング", "Fisherの最適化")
classStyle<-c("equal", "quantile", "fisher")
classStyleJ<-c("等間隔", "等量", "Fisherの最適化")
tmp.0<-dataset 
for(iii in 2:length(tmp.0)){
  q<-vector()
  t<-vector()
  q<-NULL
  t<-NULL
  mid<-3 #奇数
  tmp.1<-dataset[,iii] 
  if(is.na(sum(tmp.1))==F){
    rrr<-order(tmp.0[,iii])
    tmp.0<-tmp.0[rrr,]
    rownames(tmp.0)<-c(1:nrow(tmp.0))
    tmp.0[,1]<-ordered(tmp.0[,1],levels=tmp.0[,1][1:length(tmp.0[,1])])
    mainTitle<-colnames(tmp.0)[iii]
    mainTitle<-gsub("source","\nData Source:",mainTitle)
    mainTitle<-gsub("前年同月比\\.","前年同月比(%)\n",mainTitle)
    mainTitle<-gsub("割合","割合(%)",mainTitle)
    mainTitle<-gsub("パーセント","%",mainTitle)
    mainTitle<-gsub("break","\n",mainTitle)
##################分類・凡例パート 参考資料 古谷知之.『Rによる空間データの統計分析』.朝倉書店.2011.pp168 
# fixed, sd, equal, pretty, quantile, kmeans, hclust, bclust, fisher, jenks  
# Blues BuGn BuPu GnBu Greens Greys Oranges OrRd PuBu PuBuGn PuRd Purples RdPu Reds YlGn YlGnBu YlOrBr YlOrRd    
# use nclass{grDevices} or n
# http://www.inside-r.org/packages/cran/classInt/docs/classIntervals    
    for(zzz in 1:length(classStyle)){
      t<-(classIntervals(tmp.0[,iii],style=classStyle[zzz],n=nSplit))$brks
      switch(roundType,
      t<-round(t,-(floor(log10(t))-1)), # t=10^log10(t)の場合の処理を挟むこと
      t<-format(t,digits=2) #改良余地あり
      )
      t<-as.numeric(t)
      t<-t[-1]
      t<-t[-length(t)]    
      color.set<-brewer.pal(length(t)+1,"Blues")
      tmp.mainTitle<-mainTitle
      mainTitle<-paste(mainTitle,", 分類方法:",classStyleJ[zzz])
      color.map3(tmp.1,t,color.set)
      mainTitle<-tmp.mainTitle
    }  
##################分類・凡例パート    
  }
}  
##########################################  Japan Map  ##########################################
```

```{r}
##########################################  World Map  ##########################################
##########################################  common part  ########################################
mapType<-2 # 1:shape data , 2:library(rworldmap)
classType<-2 # 1:auto break , 2:manual break
brew<-2 # 1:brewer , 2:auto(colorful)
mainTitle<-colnames(dataset)[2]
mainTitle<-gsub("source","\nData Source:",mainTitle)
mainTitle<-gsub("前年同月比\\.","前年同月比(%)\n",mainTitle)
mainTitle<-gsub("割合","割合(%)",mainTitle)
mainTitle<-gsub("break","\n",mainTitle)
SD<-Sys.Date()
creationDate<-paste("作成日:",year(SD),"-",month(SD),"-",day(SD),sep="")  
merge.by<-colnames(countryDataset)[1]
dataset[,2]<-as.numeric(dataset[,2])
buf.dataColname<-colnames(dataset)[2]
mergeDataset<-merge(countryDataset,dataset,by=merge.by)
colnames(mergeDataset)[3]<-"value"
if(mapType==1){
  valueForNA<-min(na.omit(mergeDataset[,3]))-10 ########## 要改良
  if(classType==1){
    n<-8  
    classInt<-NULL
    catMethod<-NULL
    classInt<-classIntervals(na.omit(mergeDataset[["value"]]),n=n,style="jenks")
    catMethod<-c(valueForNA,classInt[["brks"]])
    catMethod<-catMethod[-length(catMethod)]
    mergeDataset[,3][is.na(mergeDataset[,3])]<-valueForNA
  }else{  
    catMethod<-NULL
    catMethod<-c(valueForNA , min(na.omit(mergeDataset[,3])) , 2 , 4 , 6 , 8 , 10 , 15 , 20)
    n<-length(catMethod)
    mergeDataset[,3][is.na(mergeDataset[,3])]<-valueForNA
  }
  colourPalette<-c("black",brewer.pal(n-0,'RdPu'))
}else{
  n<-9  
  classInt<-NULL
  catMethod<-NULL
  classInt<-classIntervals(mergeDataset[["value"]],n=n,style="jenks") #,style="fixed",fixedBreaks=fiedBr ) #caution max(n)=9 
  colourPalette<-brewer.pal(n,"RdPu")
  catMethod<-classInt[["brks"]]
}  
##########################################  common part  ########################################
#######################  Read a ShapeData and create a merged data frame ########################
if(mapType==1){
setwd(pathWmap)
file.name<-dir(pathWmap,pattern=".shp")
map.obj<-readShapeSpatial(file.name)
names(map.obj)
plot(map.obj)
map.df<-fortify(map.obj,region="iso_a3")
colnames(map.df)[7]<-merge.by
mapData<-merge(map.df,mergeDataset,by=merge.by)
mapData<-mapData[order(mapData$order),]
tmp.0<-findInterval(mapData$value,catMethod) #findIntervalはA1<= x1 < A2,classIntはA1< x1 <= A2のため注意すること
mapData$classfied<-catMethod[tmp.0]
setwd(pathOutput)                         
SD<-Sys.Date()
ST<-Sys.time()  
addVer<-gsub("\\.","",paste(year(SD),month(SD),day(SD),hour(ST),minute(ST),second(ST),sep=""))
png.file<-paste(addVer,".png",sep="")      
png(file=png.file,width=1400,height=900) 
par(mar=c(0,0,12,0),ps=40)
q<-ggplot(mapData)
q<-q+aes(long,lat,group=group)+geom_polygon(aes(fill=factor(classfied)))+geom_path(color="white")+coord_equal()
if(brew==1){
  q<-q+scale_fill_manual(name="",values=colourPalette,guide="legend",labels=c("NA",paste(catMethod[-1],"～")))
}else{
  q<-q+scale_fill_discrete(name="",labels=c("NA",paste(catMethod[-1],"～")))
}  
q<-q+xlab("")+ylab("")
q<-q+ggtitle(paste(mainTitle,"\n",creationDate))
q<-q+theme(axis.text=element_text(size=30),axis.title=element_text(colour="white",size=1,face="bold"))   
q<-q+theme(title=element_text(size=40,face="bold"),legend.position="bottom")   
q<-q+theme(legend.text=element_text(colour="black",size=40,face="bold"))   
q<-q+theme(legend.title=element_text(colour="white",size=40,face="bold"))   
print(q)
dev.off()
################################# 確認用ループ。出力との直接の関係は無い ########################
for(zzz in 1:(length(catMethod))){
  if(zzz==1){  
    buf<-subset(mapData,catMethod[zzz]<=mapData$value & mapData$value<catMethod[zzz+1]) 
    cat(catMethod[zzz],"-",catMethod[zzz+1],"\n")  
  }else if(zzz==2){  
    buf<-subset(mapData,catMethod[zzz]<=mapData$value & mapData$value<=catMethod[zzz+1]) 
    cat(catMethod[zzz],"-",catMethod[zzz+1],"\n")  
  }else if(zzz!=(length(catMethod))){  
    buf<-subset(mapData,catMethod[zzz]<mapData$value & mapData$value<=catMethod[zzz+1]) 
    cat(catMethod[zzz],"-",catMethod[zzz+1],"\n")  
  }else{
    buf<-subset(mapData,catMethod[zzz]<mapData$value) 
    cat(catMethod[zzz],"-","\n")  
  }  
  print(unique(buf$cName))
  print(length(unique(buf$cName)))
  cat("\n\n")  
}  
for(zzz in 1:(length(unique(mapData$classfied)))){
  buf<-subset(mapData,catMethod[zzz]==mapData$classfied) 
  print(unique(buf$cName))
  print(length(unique(buf$cName)))
  cat("\n\n")  
}  
################################# 確認用ループ。出力との直接の関係は無い ########################
}  
#######################  Read a ShapeData and create a merged data frame ########################
#######################  Create a merged data and a map by 'rworldmap' ########################
if(mapType==2){
mapData<-joinCountryData2Map(mergeDataset,joinCode="ISO3",nameJoinColumn=merge.by)  
SD<-Sys.Date()
ST<-Sys.time()  
addVer<-gsub("\\.","",paste(year(SD),month(SD),day(SD),hour(ST),minute(ST),second(ST),sep=""))
png.file<-paste(addVer,".png",sep="")      
png(file=png.file,width=1500,height=1000) 
par(mai=c(0,0,1,0),xaxs="i",yaxs="i",ps=40)
buf.mapData<-mapCountryData(
  mapData,
  nameColumnToPlot="value",
  addLegend=FALSE,
  catMethod=catMethod,
  colourPalette=colourPalette,
  missingCountryCol="white",
  borderCol="black",
  oceanCol="lightblue",
  mapTitle=paste("\n\n",mainTitle,"\n",creationDate)
  )
do.call(
  addMapLegend,
  c(
    buf.mapData,
    legendLabels="all",
    legendIntervals="data",
    legendWidth=1,
    legendMar=2
  )
  )
dev.off()  
}  
###################################### make a chart #############################################
##########################################  World Map  ##########################################
```

```{r}
##########################################  World Map  ##########################################
countryName<-c(
"AFG","Afghanistan",
"ALB","Albania",
"DZA","Algeria",
"AGO","Angola",
"ATG","Antigua and Barbuda",
"ARG","Argentina",
"ARM","Armenia",
"AUS","Australia",
"AUT","Austria",
"AZE","Azerbaijan",
"BHS","The Bahamas",
"BHR","Bahrain",
"BGD","Bangladesh",
"BRB","Barbados",
"BLR","Belarus",
"BEL","Belgium",
"BLZ","Belize",
"BEN","Benin",
"BTN","Bhutan",
"BOL","Bolivia",
"BIH","Bosnia and Herzegovina",
"BWA","Botswana",
"BRA","Brazil",
"BRN","Brunei Darussalam",
"BGR","Bulgaria",
"BFA","Burkina Faso",
"BDI","Burundi",
"CPV","Cabo Verde",
"KHM","Cambodia",
"CMR","Cameroon",
"CAN","Canada",
"CAF","Central African Republic",
"TCD","Chad",
"CHL","Chile",
"CHN","China",
"COL","Colombia",
"COM","Comoros",
"COD","Democratic Republic of the Congo",
"COG","Republic of Congo",
"CRI","Costa Rica",
"CIV","Republic of Cote dIvoire",
"HRV","Croatia",
"CYP","Cyprus",
"CZE","Czech Republic",
"DNK","Denmark",
"DJI","Djibouti",
"DMA","Dominica",
"DOM","Dominican Republic",
"ECU","Ecuador",
"EGY","Egypt",
"SLV","El Salvador",
"GNQ","Equatorial Guinea",
"ERI","Eritrea",
"EST","Estonia",
"ETH","Ethiopia",
"FJI","Fiji",
"FIN","Finland",
"FRA","France",
"GAB","Gabon",
"GMB","The Gambia",
"GEO","Georgia",
"DEU","Germany",
"GHA","Ghana",
"GRC","Greece",
"GRD","Grenada",
"GTM","Guatemala",
"GIN","Guinea",
"GNB","Guinea-Bissau",
"GUY","Guyana",
"HTI","Haiti",
"HND","Honduras",
"HKG","Hong Kong SAR",
"HUN","Hungary",
"ISL","Iceland",
"IND","India",
"IDN","Indonesia",
"IRN","Islamic Republic of Iran",
"IRQ","Iraq",
"IRL","Ireland",
"ISR","Israel",
"ITA","Italy",
"JAM","Jamaica",
"JPN","Japan",
"JOR","Jordan",
"KAZ","Kazakhstan",
"KEN","Kenya",
"KIR","Kiribati",
"KOR","Korea",
"UVK","Kosovo",
"KWT","Kuwait",
"KGZ","Kyrgyz Republic",
"LAO","Lao P.D.R.",
"LVA","Latvia",
"LBN","Lebanon",
"LSO","Lesotho",
"LBR","Liberia",
"LBY","Libya",
"LTU","Lithuania",
"LUX","Luxembourg",
"MKD","FYR Macedonia",
"MDG","Madagascar",
"MWI","Malawi",
"MYS","Malaysia",
"MDV","Maldives",
"MLI","Mali",
"MLT","Malta",
"MHL","Marshall Islands",
"MRT","Mauritania",
"MUS","Mauritius",
"MEX","Mexico",
"FSM","Micronesia",
"MDA","Moldova",
"MNG","Mongolia",
"MNE","Montenegro",
"MAR","Morocco",
"MOZ","Mozambique",
"MMR","Myanmar",
"NAM","Namibia",
"NPL","Nepal",
"NLD","Netherlands",
"NZL","New Zealand",
"NIC","Nicaragua",
"NER","Niger",
"NGA","Nigeria",
"NOR","Norway",
"OMN","Oman",
"PAK","Pakistan",
"PLW","Palau",
"PAN","Panama",
"PNG","Papua New Guinea",
"PRY","Paraguay",
"PER","Peru",
"PHL","Philippines",
"POL","Poland",
"PRT","Portugal",
"QAT","Qatar",
"ROU","Romania",
"RUS","Russia",
"RWA","Rwanda",
"WSM","Samoa",
"SMR","San Marino",
"STP","Sao Tome and Pr incipe",
"SAU","Saudi Arabia",
"SEN","Senegal",
"SRB","Serbia",
"SYC","Seychelles",
"SLE","Sierra Leone",
"SGP","Singapore",
"SVK","Slovak Republic",
"SVN","Slovenia",
"SLB","Solomon Islands",
"ZAF","South Africa",
"SSD","South Sudan",
"ESP","Spain",
"LKA","Sri Lanka",
"KNA","St.Kitts and Nevis",
"LCA","St.Lucia",
"VCT","St.Vincent and the Grenadines",
"SDN","Sudan",
"SUR","Suriname",
"SWZ","Swaziland",
"SWE","Sweden",
"CHE","Switzerland",
"SYR","Syria",
"TWN","Taiwan Province of China",
"TJK","Tajikistan",
"TZA","Tanzania",
"THA","Thailand",
"TLS","Timor-Leste",
"TGO","Togo",
"TON","Tonga",
"TTO","Trinidad and Tobago",
"TUN","Tunisia",
"TUR","Turkey",
"TKM","Turkmenistan",
"TUV","Tuvalu",
"UGA","Uganda",
"UKR","Ukraine",
"ARE","United Arab Emirates",
"GBR","United Kingdom",
"USA","United States",
"URY","Uruguay",
"UZB","Uzbekistan",
"VUT","Vanuatu",
"VEN","Venezuela",
"VNM","Vietnam",
"YEM","Yemen",
"ZMB","Zambia",
"ZWE","Zimbabwe"
)
ISO<-countryName[seq(1,length(countryName),by=2)]
cName<-countryName[seq(2,length(countryName),by=2)]
countryDataset<-data.frame(ISO,cName)
##########################################  World Map  ##########################################
```

```{r}
########################################## pyramid plot #########################################
plotType<-1
setwd(pathOutput) 
SD<-Sys.Date()
ST<-Sys.time()  
addVer<-gsub("\\.","",paste(year(SD),month(SD),day(SD),hour(ST),minute(ST),second(ST),sep=""))
png.file<-paste(addVer,".png",sep="")      
png(file=png.file,width=1400,height=900) 
par(ps=30)
mainTitle<-paste("法人企業統計調査.金融業、保険業以外の業種(原数値)\nソフトウェアを除く設備投資(当期末新設固定資産).全規模.兆円","\n",creationDate)
########################################## pyramid.plot() #######################################
if(plotType==1){
xlimit<-12 #改良余地在り
xlabBy<-1  #改良余地在り　
displayN<-50  
lx<-tail(as.numeric(dataset[,2]),displayN)/10^0
rx<-tail(as.numeric(dataset[,3]),displayN)/10^0
labelsTitle<-tail(as.character(dataset[,1]),displayN)
labelsText<-c(colnames(dataset)[2],colnames(dataset)[1],colnames(dataset)[3])
unitText<-""
par(
  mar=pyramid.plot(
    lx,
    rx,
    labels=labelsTitle,
    top.labels=labelsText,
    unit=unitText,
    main=mainTitle,
    lxcol="#e27272",
    rxcol="#72aae2",
    space=0.3,
    ppmar=c(5,5,14,5),
    labelcex=0.8,
    xlim=c(xlimit,xlimit),
    laxlab=seq(from = 0, to = xlimit, by = xlabBy), #改良余地在り
    raxlab=seq(from = 0, to = xlimit, by = xlabBy), #改良余地在り
    gap=2 #改良余地在り
  )
)
}
########################################## pyramid.plot() #######################################
########################################## pyramidLikert() ######################################
if(plotType==2){
panelWidth<-0.4
main.cex<-1.2
xlab.cex<-1.5
xlabTitle<-"百万円" #改良余地在り
ylabTitle<-"期"     #改良余地在り
buf.plot<-plot(
  as.likert(dataset[,-1]),
  scales=list(
    y=list(
      limits=c(0,nrow(dataset)+1),
      at=seq(1,nrow(dataset),1),
      labels=rev(dataset[,1]),
      cex=1.2,
      tck=0.5
    ),
    x=list(
      cex=2,
      tck=0.5
    )
  ),
  main=list(
    mainTitle,
    cex=main.cex
  ),
  xlab=list(
    xlabTitle,
    cex=xlab.cex
  ),  
  ylab=list(
    ylabTitle
  )
)
as.pyramidLikert(
  buf.plot,
  px=list(
    L=c(0, panelWidth),
    R=c(1-panelWidth, 1),
    M=c(panelWidth, 1-panelWidth)
  )
)
}
########################################## pyramidLikert ########################################
dev.off()
########################################## pyramid plot #########################################
```

