```{r}
requiredPackageList<-c("ggplot2","lubridate","maptools")
colnames(installed.packages())
notInstalledPackages<-requiredPackageList[!(requiredPackageList %in% installed.packages()[,"Package"])] #apply logical vector to requiredPackageList
if(length(notInstalledPackages)!=0){print(notInstalledPackages);install.packages(notInstalledPackages)}
lapply(requiredPackageList,require,character.only=T)
#Reference 
#http://stackoverflow.com/questions/4090169/elegant-way-to-check-for-missing-packages-and-install-them
#http://stackoverflow.com/questions/8175912/load-multiple-packages-at-once
username<-Sys.info()['user']
pathOutput<-paste("C:/Users/",username,"/Desktop/charts/",sep="")
pathOutput<-paste("C:/Users/",username,"/Desktop/R_Data_Write/",sep="")
windowsFonts(Meiryo=windowsFont("Meiryo"))
```

```{r}
data.file<-"query.csv"
pathEarthquake<-paste("C:/Users/",username,"/Desktop/Earthquake_Data/",sep="")
buf<-read.table(file=paste(pathEarthquake,data.file,sep=""),sep=",",header=T,as.is=T,skip=0)
SD<-Sys.Date()
ST<-Sys.time() 
buf<-subset(buf,7<=buf$mag)
JST<-as.POSIXct(sub("Z","",sub("T"," ",buf$time)))+3600*9 #UTC+9
No<-seq(1,nrow(buf),by=1)
GoogleMap<-paste("<a href=\"http://maps.google.co.jp/maps?ll=",buf$latitude,",",buf$longitude,"&z=4&q=loc:",buf$latitude,"+",buf$longitude,"\" target=\"_blank\">Google Map</a>",sep="")
buf<-data.frame(No,JST,GoogleMap,buf)
colnames(buf)
print(head(buf))
print(tail(buf))
nrow(buf)
```

```{r}
tailLength<-100000
menulength<-10
orderColumn<-0
orderDirection<-"asc" #asc desc
dateFormat<-1 #1:as is , 2:scientific , 3:monthly , 4:dayly , 5:yearly
columnWidth<-"{\"width\":\"5%\",\"targets\":0},{\"width\":\"16%\",\"targets\":1},{\"width\":\"9%\",\"targets\":2},{\"width\":\"9%\",\"targets\":3},{\"width\":\"9%\",\"targets\":4} ,{\"width\":\"11%\",\"targets\":6}"
switch(dateFormat,
  dateFormatType<-"",
  dateFormatType<-"",
  dateFormatType<-"%Y/%m",
  dateFormatType<-"%Y/%m/%d",
  dateFormatType<-"%Y"
)
tmp<-buf[,c(1,2,5,6,7,8,9,17,3)]
colnames(tmp)<-c("No.","日本時間","緯度","経度","深さ","M","Mタイプ","地点","地図")
dataset<-tail(tmp,tailLength)
```

```{r}
#only html
setwd(pathOutput)
col<-list()
addVer<-gsub("\\.","",paste(year(SD),month(SD),day(SD),hour(ST),minute(ST),second(ST),sep=""))
htmlFile<-"earthquakeTable.html"
cat("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n",file=htmlFile,append=F)
cat("<style>\n",file=htmlFile,append=T)
cat("body{\n",file=htmlFile,append=T)
cat("font-family:'Hiragino Kaku Gothic Pro','Meiryo UI',Verdana,sans-serif;\n",file=htmlFile,append=T)
cat("}\n",file=htmlFile,append=T)
cat("</style>\n",file=htmlFile,append=T)
cat("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js\"></script>",file=htmlFile,append=T)
cat("<link href=\"http://cdn.datatables.net/1.10.7/css/jquery.dataTables.min.css\" rel=\"stylesheet\">",file=htmlFile,append=T)
cat("<script src=\"http://cdn.datatables.net/1.10.7/js/jquery.dataTables.min.js\"></script>",file=htmlFile,append=T) 
grandData<-NULL
header<-NULL
tableID<-paste("am-consulting",addVer,sep="")
cat("<body><b>西暦1900年以降に発生したマグニチュード7.0以上の地震リスト</b><br>\n",file=htmlFile,append=T) 
cat("- 表中\"M\"はマグニチュード<br>\n",file=htmlFile,append=T) 
cat("- マグニチュードタイプ(Mタイプ)はデータ毎に異なります<br>\n",file=htmlFile,append=T) 
cat("- ソースデータ:http://earthquake.usgs.gov/<br>\n",file=htmlFile,append=T) 
cat(paste("- データ確認日時:",year(SD),"年",month(SD),"月",day(SD),"日","<br>\n",sep=""),file=htmlFile,append=T) 
cat("<script type=\"text/javascript\" charset=\"utf-8\">$(document).ready( function(){",file=htmlFile,append=T)
cat(paste("$('#",tableID,"').dataTable( {",sep=""),file=htmlFile,append=T)
cat("\"lengthMenu\": [[",menulength,",-1,100,200], [",menulength,",\"All\",100,200]],",file=htmlFile,append=T)
cat(paste("\"order\": [[ ",orderColumn,", \"",orderDirection,"\" ]],",sep=""),file=htmlFile,append=T)
cat("\"searching\": true,",file=htmlFile,append=T)
cat("\"columnDefs\":[",columnWidth,"],",file=htmlFile,append=T)
cat("\"language\": {\"decimal\": \".\",\"thousands\": \",\"}",file=htmlFile,append=T)
cat("});",file=htmlFile,append=T)
#正規表現  
cat(paste("$('#",tableID,"').dataTable();",sep=""),file=htmlFile,append=T)
cat("$('input.global_filter').on( 'keyup click', function () {",file=htmlFile,append=T)
cat("filterGlobal();",file=htmlFile,append=T)
cat("} );",file=htmlFile,append=T)
cat("$('input.column_filter').on( 'keyup click', function () {",file=htmlFile,append=T)
cat("filterColumn( $(this).parents('tr').attr('data-column') );",file=htmlFile,append=T)
cat("} );  ",file=htmlFile,append=T)
#正規表現
cat("});</script>",file=htmlFile,append=T)
#正規表現
cat("<div style=\"text-align:center\"><b>正規表現対応フィルターボックス</b></div>",file=htmlFile,append=T)  
cat("\n<table width=\"100%\"><thead><tr><th width=\"15%\" style=\"text-align:right\">Target</th><th width=\"75%\" style=\"text-align:right\">Search text</th><th style=\"text-align:right\">Regex</th></tr></thead><tbody>\n",file=htmlFile,append=T)
for(rccc in 2:8){
cat(paste("<tr id=\"filter_col",rccc,"\" data-column=\"",rccc-1,"\">\n",sep=""),file=htmlFile,append=T)
cat(paste("<td style=\"text-align:right\">",colnames(dataset)[rccc],"</td>",sep=""),file=htmlFile,append=T)
cat(paste("<td align=\"center\"><input type=\"text\" class=\"column_filter\" id=\"col",rccc-1,"_filter\"  style=\"width:100%\"></td>\n",sep=""),file=htmlFile,append=T)
cat(paste("<td align=\"center\"><input type=\"checkbox\" class=\"column_filter\" id=\"col",rccc-1,"_regex\" checked=\"checked\"></td>\n",sep=""),file=htmlFile,append=T)
cat("</tr>\n",file=htmlFile,append=T)
}  
cat("\n</tbody></table>",file=htmlFile,append=T)  
cat("<script>\n",file=htmlFile,append=T)  
cat("function filterGlobal () {\n",file=htmlFile,append=T) 
cat(paste("$('#",tableID,"').DataTable().search(\n",sep=""),file=htmlFile,append=T) 
cat("$('#global_filter').val(),\n",file=htmlFile,append=T) 
cat("$('#global_regex').prop('checked'),\n",file=htmlFile,append=T) 
cat("$('#global_smart').prop('checked')\n",file=htmlFile,append=T) 
cat(").draw();\n",file=htmlFile,append=T) 
cat("}\n",file=htmlFile,append=T) 
cat("function filterColumn ( i ) {\n",file=htmlFile,append=T)
cat(paste("$('#",tableID,"').DataTable().column( i ).search(\n",sep=""),file=htmlFile,append=T)
cat("$('#col'+i+'_filter').val(),\n",file=htmlFile,append=T)
cat("$('#col'+i+'_regex').prop('checked'),\n",file=htmlFile,append=T)
cat("$('#col'+i+'_smart').prop('checked')\n",file=htmlFile,append=T)
cat(").draw();\n",file=htmlFile,append=T)
cat("}\n",file=htmlFile,append=T)
cat("</script>\n",file=htmlFile,append=T)  
#正規表現
for(ccc in 1:ncol(dataset)){
  if(ccc==1){
    switch(dateFormat,
    col[[ccc]]<-paste("<td align=\"right\" valign=\"middle\">",dataset[,ccc],"</td>",sep=""),
    col[[ccc]]<-paste("<td align=\"right\" valign=\"middle\">",format(dataset[,ccc],big.mark=",",scientific=F),"</td>",sep=""),
    col[[ccc]]<-paste("<td align=\"right\" valign=\"middle\">",format(as.Date(dataset[,ccc]),dateFormatType),"</td>",sep=""),
    col[[ccc]]<-paste("<td align=\"right\" valign=\"middle\">",format(as.Date(dataset[,ccc]),dateFormatType),"</td>",sep=""),
    col[[ccc]]<-paste("<td align=\"right\" valign=\"middle\">",format(as.Date(dataset[,ccc]),dateFormatType),"</td>",sep="")
    )
  }else{  
    col[[ccc]]<-paste("<td align=\"right\" valign=\"middle\">",format(dataset[,ccc],big.mark=",",scientific=F),"</td>",sep="")
  }  
  grandData<-cbind(grandData,col[[ccc]])
  header<-paste(header,"<th>",colnames(dataset)[ccc],"</th>",sep="")  
}
tableHtml<-paste("<table cellpadding=\"0\" cellspacing=\"0\" id=\"",tableID,"\" width=\"100%\" class=\"display\" style=\"font-size:13px;\"><thead>",sep="")
tableHtml<-paste(tableHtml,header,"</thead>",sep="")
cat(tableHtml,file=htmlFile,append=T)
grandData<-data.frame("<tr>",grandData,"</tr>",row.names=NULL)
write.table(grandData,htmlFile,quote=F,col.names=F, append=T,row.names=F)
cat("</table>",file=htmlFile,append=T)
cat("Powered by DataTables( http://datatables.net/ )<br></body></html>",file=htmlFile,append=T)
```

```{r}
#kml part
for(magBorder in 7:9){
kmlDataset<-dataset
kmlDataset<-subset(kmlDataset,magBorder<=kmlDataset[,6] & kmlDataset[,6]<(magBorder+1))
setwd(pathOutput)
kmlFile<-paste("earthquakesOverMagnitude",magBorder,"afterY1900",".kml",sep="")
cat("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n",file=kmlFile,append=F)
cat("<kml xmlns=\"http://www.opengis.net/kml/2.2\">\n",file=kmlFile,append=T)
cat("<Document>\n",file=kmlFile,append=T)
cat("<name>KmlFile</name>\n",file=kmlFile,append=T)
#cat("<Style id=\"amc-type01\">\n",file=kmlFile,append=T)
#cat("<BalloonStyle>\n",file=kmlFile,append=T)
#cat("<text>\n",file=kmlFile,append=T)
#cat("<![CDATA[\n",file=kmlFile,append=T)
#cat("$[Place]\n",file=kmlFile,append=T)
#cat("]]>\n",file=kmlFile,append=T)
#cat("</text>\n",file=kmlFile,append=T)
#cat("</BalloonStyle>\n",file=kmlFile,append=T)
#cat("</Style>\n",file=kmlFile,append=T)
#Placemark part
for(ccc in 1:nrow(kmlDataset)){
yText<-paste(year(kmlDataset[ccc,2]),"年",sep="")
mText<-paste(month(kmlDataset[ccc,2]),"月",day(kmlDataset[ccc,2]),"日",sep="")
urlY<-paste("https://ja.wikipedia.org/wiki/",yText,sep="")  
urlM<-paste("https://ja.wikipedia.org/wiki/",mText,sep="")  
cat("<Placemark>\n",file=kmlFile,append=T)
spec<-paste(
  "JST:",kmlDataset[ccc,2],
  " , Depth(km):",kmlDataset[ccc,5],
  " , M(",kmlDataset[ccc,7],"):",kmlDataset[ccc,6],
  " , Lon:",kmlDataset[ccc,4],
  " , Lat:",kmlDataset[ccc,3],
  " , ",kmlDataset[ccc,8],
  sep="")  
refURL<-paste(
  "参考 - ",
  "<a href=\"",urlY,"\" target=\"_blank\">",yText,"</a> , ",
  "<a href=\"",urlM,"\" target=\"_blank\">",mText,"</a>",
  sep="")
cat(paste("<name>",spec,"</name>\n",sep=""),file=kmlFile,append=T)
cat(paste("<description><![CDATA[",refURL,"]]></description>\n",sep=""),file=kmlFile,append=T)
cat("<styleUrl>#amc-type01</styleUrl>\n",file=kmlFile,append=T)
#cat("<ExtendedData>\n",file=kmlFile,append=T)
#cat("<Data name=\"Place\">\n",file=kmlFile,append=T)
#cat(paste("<value>",kmlDataset[ccc,8],"</value>\n",sep=""),file=kmlFile,append=T)
#cat("</Data>\n",file=kmlFile,append=T)
#cat("</ExtendedData>\n",file=kmlFile,append=T)
cat("<Style>\n",file=kmlFile,append=T)
cat("<IconStyle>\n",file=kmlFile,append=T)
cat("<Icon>\n",file=kmlFile,append=T)
if(magBorder+0.8<=kmlDataset[ccc,6]){  
  cat("<href>http://maps.google.com/mapfiles/kml/pushpin/red-pushpin.png</href>\n",file=kmlFile,append=T)
}else if(magBorder+0.6<=kmlDataset[ccc,6]){  
  cat("<href>http://maps.google.com/mapfiles/kml/pushpin/grn-pushpin.png</href>\n",file=kmlFile,append=T)
}else if(magBorder+0.4<=kmlDataset[ccc,6]){  
  cat("<href>http://maps.google.com/mapfiles/kml/pushpin/wht-pushpin.png</href>\n",file=kmlFile,append=T)
}else if(magBorder+0.2<=kmlDataset[ccc,6]){  
  cat("<href>http://maps.google.com/mapfiles/kml/pushpin/ylw-pushpin.png</href>\n",file=kmlFile,append=T)
}else if(magBorder<=kmlDataset[ccc,6]){  
  cat("<href>http://maps.google.com/mapfiles/kml/pushpin/pink-pushpin.png</href>\n",file=kmlFile,append=T)
} 
cat("</Icon>\n",file=kmlFile,append=T)
cat("</IconStyle>\n",file=kmlFile,append=T)
cat("</Style>\n",file=kmlFile,append=T)
cat("<Point>\n",file=kmlFile,append=T)
cat(paste("<coordinates>",kmlDataset[ccc,4],",",kmlDataset[ccc,3],",",0,"</coordinates>\n",sep=""),file=kmlFile,append=T)
cat("</Point>\n",file=kmlFile,append=T)
cat("</Placemark>\n",file=kmlFile,append=T)
}  
#Placemark part
cat("</Document>",file=kmlFile,append=T)
cat("</kml>",file=kmlFile,append=T)
}
#kml part
```

```{r}
#kml用html
for(magBorder in 7:9){
setwd(pathOutput)
kmlhtml<-paste("earthquakesOverMagnitude",magBorder,"afterY1900",".html",sep="")
cat("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n",file=kmlhtml,append=F)
cat("<style>\n",file=kmlhtml,append=T)
cat("body{\n",file=kmlhtml,append=T)
cat("font-family:'ヒラギノ角ゴ Pro W3','Hiragino Kaku Gothic Pro','Meiryo UI','メイリオ',Verdana,'ＭＳ Ｐゴシック',sans-serif;\n",file=kmlhtml,append=T)
cat("}\n",file=kmlhtml,append=T)
cat("</style>\n",file=kmlhtml,append=T)
cat("<!-- Reference\n",file=kmlhtml,append=T)
cat("http://apprentice.craic.com/tutorials/40\n",file=kmlhtml,append=T)
cat("-->\n",file=kmlhtml,append=T)
cat(paste("<div style=\"text-align:center\">1900年以降に発生したマグニチュード",magBorder,"以上",(magBorder+1),"未満の発生地震マップ. ソースデータ確認日:",year(SD),"年",month(SD),"月",day(SD),"日. Data Source:<a href=\"http://earthquake.usgs.gov/\" target=\"_blank\">http://earthquake.usgs.gov/</a>","</div>\n",sep=""),file=kmlhtml,append=T)
cat("<div id=\"map_canvas\"></div>\n",file=kmlhtml,append=T)
cat("<style>\n",file=kmlhtml,append=T)
cat("#map_canvas {\n",file=kmlhtml,append=T)
cat("margin-left: auto;\n",file=kmlhtml,append=T)
cat("margin-right: auto;\n",file=kmlhtml,append=T)
cat("padding: 0;\n",file=kmlhtml,append=T)
cat("width: 100%;\n",file=kmlhtml,append=T)
cat("height: 100%;\n",file=kmlhtml,append=T)
cat("}\n",file=kmlhtml,append=T)
cat("</style>\n",file=kmlhtml,append=T)
cat("<script src=\"https://maps.googleapis.com/maps/api/js?v=3.exp&signed_in=false\"></script>\n",file=kmlhtml,append=T)
cat("<script>\n",file=kmlhtml,append=T)
cat("var mylocation = {\n",file=kmlhtml,append=T)
cat("'latitude':  35.685175,\n",file=kmlhtml,append=T)
cat("'longitude': 139.7528\n",file=kmlhtml,append=T)
cat("};\n",file=kmlhtml,append=T)
cat("var map;\n",file=kmlhtml,append=T)
cat("function initialize() {\n",file=kmlhtml,append=T)
cat("var myLatlng = new google.maps.LatLng( mylocation.latitude, mylocation.longitude );\n",file=kmlhtml,append=T)
cat("var mapOptions = {\n",file=kmlhtml,append=T)
cat("zoom: 12,\n",file=kmlhtml,append=T)
cat("center: myLatlng,\n",file=kmlhtml,append=T)
cat("mapTypeId: google.maps.MapTypeId.ROADMAP,\n",file=kmlhtml,append=T)
cat("navigationControl: true,\n",file=kmlhtml,append=T)
cat("mapTypeControl: true,\n",file=kmlhtml,append=T)
#cat("mapTypeControlOptions:{\n",file=kmlhtml,append=T)
#cat("mapTypeIds:[\n",file=kmlhtml,append=T)
#cat("google.maps.MapTypeId.ROADMAP,\n",file=kmlhtml,append=T)
#cat("google.maps.MapTypeId.SATELLITE\n",file=kmlhtml,append=T)
#cat("]\n",file=kmlhtml,append=T)
#cat("}\n",file=kmlhtml,append=T)
cat("}\n",file=kmlhtml,append=T)
cat("var map = new google.maps.Map(document.getElementById('map_canvas'), mapOptions);\n",file=kmlhtml,append=T)
cat(paste("var kmlPath = \"http://archive.am-consulting.co.jp/earthquakesOverMagnitude",magBorder,"afterY1900.kml\";\n",sep=""),file=kmlhtml,append=T)
cat("var urlSuffix = (new Date).getTime().toString();\n",file=kmlhtml,append=T)
cat("var layer = new google.maps.KmlLayer(kmlPath + '?' + urlSuffix );\n",file=kmlhtml,append=T)
cat("layer.setMap(map);\n",file=kmlhtml,append=T)
cat("}\n",file=kmlhtml,append=T)
cat("google.maps.event.addDomListener(window, 'load', initialize);\n",file=kmlhtml,append=T)
cat("</script>\n",file=kmlhtml,append=T)
}  
#kml用html
```